// Code generated by ent, DO NOT EDIT.

package tenantpackagefeature

import (
	"entgo.io/ent/dialect/sql"
	"github.com/fudanda/zenith-admin/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TenantPackageFeature {
	return predicate.TenantPackageFeature(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TenantPackageFeature {
	return predicate.TenantPackageFeature(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TenantPackageFeature {
	return predicate.TenantPackageFeature(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TenantPackageFeature {
	return predicate.TenantPackageFeature(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TenantPackageFeature {
	return predicate.TenantPackageFeature(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TenantPackageFeature {
	return predicate.TenantPackageFeature(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TenantPackageFeature {
	return predicate.TenantPackageFeature(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TenantPackageFeature {
	return predicate.TenantPackageFeature(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TenantPackageFeature {
	return predicate.TenantPackageFeature(sql.FieldLTE(FieldID, id))
}

// PackageID applies equality check predicate on the "package_id" field. It's identical to PackageIDEQ.
func PackageID(v int) predicate.TenantPackageFeature {
	return predicate.TenantPackageFeature(sql.FieldEQ(FieldPackageID, v))
}

// FeatureKey applies equality check predicate on the "feature_key" field. It's identical to FeatureKeyEQ.
func FeatureKey(v string) predicate.TenantPackageFeature {
	return predicate.TenantPackageFeature(sql.FieldEQ(FieldFeatureKey, v))
}

// PackageIDEQ applies the EQ predicate on the "package_id" field.
func PackageIDEQ(v int) predicate.TenantPackageFeature {
	return predicate.TenantPackageFeature(sql.FieldEQ(FieldPackageID, v))
}

// PackageIDNEQ applies the NEQ predicate on the "package_id" field.
func PackageIDNEQ(v int) predicate.TenantPackageFeature {
	return predicate.TenantPackageFeature(sql.FieldNEQ(FieldPackageID, v))
}

// PackageIDIn applies the In predicate on the "package_id" field.
func PackageIDIn(vs ...int) predicate.TenantPackageFeature {
	return predicate.TenantPackageFeature(sql.FieldIn(FieldPackageID, vs...))
}

// PackageIDNotIn applies the NotIn predicate on the "package_id" field.
func PackageIDNotIn(vs ...int) predicate.TenantPackageFeature {
	return predicate.TenantPackageFeature(sql.FieldNotIn(FieldPackageID, vs...))
}

// PackageIDGT applies the GT predicate on the "package_id" field.
func PackageIDGT(v int) predicate.TenantPackageFeature {
	return predicate.TenantPackageFeature(sql.FieldGT(FieldPackageID, v))
}

// PackageIDGTE applies the GTE predicate on the "package_id" field.
func PackageIDGTE(v int) predicate.TenantPackageFeature {
	return predicate.TenantPackageFeature(sql.FieldGTE(FieldPackageID, v))
}

// PackageIDLT applies the LT predicate on the "package_id" field.
func PackageIDLT(v int) predicate.TenantPackageFeature {
	return predicate.TenantPackageFeature(sql.FieldLT(FieldPackageID, v))
}

// PackageIDLTE applies the LTE predicate on the "package_id" field.
func PackageIDLTE(v int) predicate.TenantPackageFeature {
	return predicate.TenantPackageFeature(sql.FieldLTE(FieldPackageID, v))
}

// FeatureKeyEQ applies the EQ predicate on the "feature_key" field.
func FeatureKeyEQ(v string) predicate.TenantPackageFeature {
	return predicate.TenantPackageFeature(sql.FieldEQ(FieldFeatureKey, v))
}

// FeatureKeyNEQ applies the NEQ predicate on the "feature_key" field.
func FeatureKeyNEQ(v string) predicate.TenantPackageFeature {
	return predicate.TenantPackageFeature(sql.FieldNEQ(FieldFeatureKey, v))
}

// FeatureKeyIn applies the In predicate on the "feature_key" field.
func FeatureKeyIn(vs ...string) predicate.TenantPackageFeature {
	return predicate.TenantPackageFeature(sql.FieldIn(FieldFeatureKey, vs...))
}

// FeatureKeyNotIn applies the NotIn predicate on the "feature_key" field.
func FeatureKeyNotIn(vs ...string) predicate.TenantPackageFeature {
	return predicate.TenantPackageFeature(sql.FieldNotIn(FieldFeatureKey, vs...))
}

// FeatureKeyGT applies the GT predicate on the "feature_key" field.
func FeatureKeyGT(v string) predicate.TenantPackageFeature {
	return predicate.TenantPackageFeature(sql.FieldGT(FieldFeatureKey, v))
}

// FeatureKeyGTE applies the GTE predicate on the "feature_key" field.
func FeatureKeyGTE(v string) predicate.TenantPackageFeature {
	return predicate.TenantPackageFeature(sql.FieldGTE(FieldFeatureKey, v))
}

// FeatureKeyLT applies the LT predicate on the "feature_key" field.
func FeatureKeyLT(v string) predicate.TenantPackageFeature {
	return predicate.TenantPackageFeature(sql.FieldLT(FieldFeatureKey, v))
}

// FeatureKeyLTE applies the LTE predicate on the "feature_key" field.
func FeatureKeyLTE(v string) predicate.TenantPackageFeature {
	return predicate.TenantPackageFeature(sql.FieldLTE(FieldFeatureKey, v))
}

// FeatureKeyContains applies the Contains predicate on the "feature_key" field.
func FeatureKeyContains(v string) predicate.TenantPackageFeature {
	return predicate.TenantPackageFeature(sql.FieldContains(FieldFeatureKey, v))
}

// FeatureKeyHasPrefix applies the HasPrefix predicate on the "feature_key" field.
func FeatureKeyHasPrefix(v string) predicate.TenantPackageFeature {
	return predicate.TenantPackageFeature(sql.FieldHasPrefix(FieldFeatureKey, v))
}

// FeatureKeyHasSuffix applies the HasSuffix predicate on the "feature_key" field.
func FeatureKeyHasSuffix(v string) predicate.TenantPackageFeature {
	return predicate.TenantPackageFeature(sql.FieldHasSuffix(FieldFeatureKey, v))
}

// FeatureKeyEqualFold applies the EqualFold predicate on the "feature_key" field.
func FeatureKeyEqualFold(v string) predicate.TenantPackageFeature {
	return predicate.TenantPackageFeature(sql.FieldEqualFold(FieldFeatureKey, v))
}

// FeatureKeyContainsFold applies the ContainsFold predicate on the "feature_key" field.
func FeatureKeyContainsFold(v string) predicate.TenantPackageFeature {
	return predicate.TenantPackageFeature(sql.FieldContainsFold(FieldFeatureKey, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TenantPackageFeature) predicate.TenantPackageFeature {
	return predicate.TenantPackageFeature(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TenantPackageFeature) predicate.TenantPackageFeature {
	return predicate.TenantPackageFeature(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TenantPackageFeature) predicate.TenantPackageFeature {
	return predicate.TenantPackageFeature(sql.NotPredicates(p))
}
