import { definePermissions } from '../core/permissions';

/**
 * mp 域权限码注册表：code → 按钮标题 / 所属页面（菜单 name）。
 * 种子 button 节点由此生成（@arcbase/shared/seed），契约操作 / 路由门禁 / 前端按钮以 `Permission` 类型引用。
 * `uiOnly` = 服务端没有任何接口检查该码（纯前端门控或待清理）。
 */
export const MP_PERMISSIONS = definePermissions({
  'mp:account:list': { label: '查询', menu: 'MpAccounts' },
  'mp:account:create': { label: '新增公众号', menu: 'MpAccounts' },
  'mp:account:update': { label: '编辑公众号', menu: 'MpAccounts' },
  'mp:account:delete': { label: '删除公众号', menu: 'MpAccounts' },
  'mp:account:default': { label: '设为默认', menu: 'MpAccounts' },
  'mp:account:token': { label: '测试连接', menu: 'MpAccounts' },
  'mp:security:check': { label: '内容安全检测', menu: 'MpAccounts' },
  'mp:tag:list': { label: '查询', menu: 'MpTags' },
  'mp:tag:create': { label: '新增标签', menu: 'MpTags' },
  'mp:tag:update': { label: '编辑标签', menu: 'MpTags' },
  'mp:tag:delete': { label: '删除标签', menu: 'MpTags' },
  'mp:tag:sync': { label: '同步标签', menu: 'MpTags' },
  'mp:fan:list': { label: '查询', menu: 'MpFans' },
  'mp:fan:sync': { label: '同步粉丝', menu: 'MpFans' },
  'mp:fan:update': { label: '编辑粉丝', menu: 'MpFans' },
  'mp:fan:bind': { label: '会员绑定', menu: 'MpFans' },
  'mp:fan:blacklist': { label: '黑名单管理', menu: 'MpFans' },
  'mp:message:list': { label: '查询', menu: 'MpMessages' },
  'mp:message:send': { label: '发送消息', menu: 'MpMessages' },
  'mp:reply:list': { label: '查询', menu: 'MpAutoReplies' },
  'mp:reply:create': { label: '新增回复', menu: 'MpAutoReplies' },
  'mp:reply:update': { label: '编辑回复', menu: 'MpAutoReplies' },
  'mp:reply:delete': { label: '删除回复', menu: 'MpAutoReplies' },
  'mp:menu:list': { label: '查询', menu: 'MpMenu' },
  'mp:menu:save': { label: '保存菜单', menu: 'MpMenu' },
  'mp:menu:publish': { label: '发布菜单', menu: 'MpMenu' },
  'mp:menu:pull': { label: '拉取菜单', menu: 'MpMenu' },
  'mp:menu:delete': { label: '删除菜单', menu: 'MpMenu' },
  'mp:material:list': { label: '查询', menu: 'MpMaterials' },
  'mp:material:create': { label: '新增素材', menu: 'MpMaterials' },
  'mp:material:update': { label: '重命名素材', menu: 'MpMaterials' },
  'mp:material:delete': { label: '删除素材', menu: 'MpMaterials' },
  'mp:material:sync': { label: '同步素材', menu: 'MpMaterials' },
  'mp:draft:list': { label: '查询', menu: 'MpDrafts' },
  'mp:draft:create': { label: '新增图文', menu: 'MpDrafts' },
  'mp:draft:update': { label: '编辑图文', menu: 'MpDrafts' },
  'mp:draft:delete': { label: '删除图文', menu: 'MpDrafts' },
  'mp:draft:push': { label: '推送图文', menu: 'MpDrafts' },
  'mp:template:list': { label: '查询', menu: 'MpTemplates' },
  'mp:template:sync': { label: '同步模板', menu: 'MpTemplates' },
  'mp:template:send': { label: '发送模板', menu: 'MpTemplates' },
  'mp:template:delete': { label: '删除模板', menu: 'MpTemplates' },
  'mp:statistics:view': { label: '查询', menu: 'MpStatistics' },
  'mp:broadcast:list': { label: '查询', menu: 'MpBroadcasts' },
  'mp:broadcast:create': { label: '新增群发', menu: 'MpBroadcasts' },
  'mp:broadcast:update': { label: '编辑群发', menu: 'MpBroadcasts' },
  'mp:broadcast:send': { label: '发送群发', menu: 'MpBroadcasts' },
  'mp:broadcast:delete': { label: '删除群发', menu: 'MpBroadcasts' },
  'mp:qrcode:list': { label: '查询', menu: 'MpQrcodes' },
  'mp:qrcode:create': { label: '生成二维码', menu: 'MpQrcodes' },
  'mp:qrcode:delete': { label: '删除二维码', menu: 'MpQrcodes' },
  'mp:oauth:build': { label: '查询', menu: 'MpOAuth' },
  'mp:jssdk:config': { label: 'JS-SDK签名', menu: 'MpOAuth' },
  'mp:kf:list': { label: '查询', menu: 'MpKfAccounts' },
  'mp:kf:create': { label: '添加客服', menu: 'MpKfAccounts' },
  'mp:kf:update': { label: '编辑客服', menu: 'MpKfAccounts' },
  'mp:kf:delete': { label: '删除客服', menu: 'MpKfAccounts' },
  'mp:kf:sync': { label: '同步客服', menu: 'MpKfAccounts' },
  'mp:kf:session:list': { label: '查询', menu: 'MpKfSessions' },
  'mp:kf:session:accept': { label: '接入会话', menu: 'MpKfSessions' },
  'mp:kf:session:transfer': { label: '转接会话', menu: 'MpKfSessions' },
  'mp:kf:session:close': { label: '结束会话', menu: 'MpKfSessions' },
  'mp:kf:session:reply': { label: '会话回复', menu: 'MpKfSessions' },
  'mp:kf:session:config': { label: '路由配置', menu: 'MpKfSessions' },
  'mp:condmenu:list': { label: '查询', menu: 'MpConditionalMenus' },
  'mp:condmenu:create': { label: '新增菜单', menu: 'MpConditionalMenus' },
  'mp:condmenu:update': { label: '编辑菜单', menu: 'MpConditionalMenus' },
  'mp:condmenu:publish': { label: '发布菜单', menu: 'MpConditionalMenus' },
  'mp:condmenu:delete': { label: '删除菜单', menu: 'MpConditionalMenus' },
});
