// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AuditLog is the predicate function for auditlog builders.
type AuditLog func(*sql.Selector)

// Captcha is the predicate function for captcha builders.
type Captcha func(*sql.Selector)

// Department is the predicate function for department builders.
type Department func(*sql.Selector)

// LoginAttempt is the predicate function for loginattempt builders.
type LoginAttempt func(*sql.Selector)

// LoginLog is the predicate function for loginlog builders.
type LoginLog func(*sql.Selector)

// Menu is the predicate function for menu builders.
type Menu func(*sql.Selector)

// Position is the predicate function for position builders.
type Position func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// RoleDepartment is the predicate function for roledepartment builders.
type RoleDepartment func(*sql.Selector)

// RoleMenu is the predicate function for rolemenu builders.
type RoleMenu func(*sql.Selector)

// RolePermission is the predicate function for rolepermission builders.
type RolePermission func(*sql.Selector)

// Session is the predicate function for session builders.
type Session func(*sql.Selector)

// Tenant is the predicate function for tenant builders.
type Tenant func(*sql.Selector)

// TenantPackage is the predicate function for tenantpackage builders.
type TenantPackage func(*sql.Selector)

// TenantPackageFeature is the predicate function for tenantpackagefeature builders.
type TenantPackageFeature func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserDepartmentScope is the predicate function for userdepartmentscope builders.
type UserDepartmentScope func(*sql.Selector)

// UserGroup is the predicate function for usergroup builders.
type UserGroup func(*sql.Selector)

// UserGroupMember is the predicate function for usergroupmember builders.
type UserGroupMember func(*sql.Selector)

// UserGroupRole is the predicate function for usergrouprole builders.
type UserGroupRole func(*sql.Selector)

// UserMenu is the predicate function for usermenu builders.
type UserMenu func(*sql.Selector)

// UserPermission is the predicate function for userpermission builders.
type UserPermission func(*sql.Selector)

// UserPosition is the predicate function for userposition builders.
type UserPosition func(*sql.Selector)

// UserRole is the predicate function for userrole builders.
type UserRole func(*sql.Selector)
