export { LoginPage } from './login';
export { HomePage } from './home';
export { ProfilePage } from './profile';
export { PositionsPage } from './positions';
export { TenantsPage } from './tenants';
export { TenantPackagesPage } from './tenant-packages';
export { LoginLogsPage, OperationLogsPage } from './logs';
export { DepartmentsPage } from './departments';
export { UsersPage } from './users';
export { RolesPage } from './roles';
export { UserGroupsPage } from './user-groups';
export { DictsPage } from './dicts';
export { FileConfigsPage } from './file-configs';
export { FilesPage } from './files';
export { FileSettingsPage } from './file-settings';
