-- Custom indexes and foreign keys required by the Ent baseline.
CREATE UNIQUE INDEX IF NOT EXISTS users_platform_username_unique ON users(username) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS positions_platform_code_unique ON positions(code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS departments_platform_code_unique ON departments(code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS roles_platform_code_unique ON roles(code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS user_groups_platform_code_unique ON user_groups(code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS dicts_platform_code_unique ON dicts(code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS file_storage_configs_default_unique ON file_storage_configs(is_default) WHERE is_default = true;
ALTER TABLE users ADD CONSTRAINT users_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE users ADD CONSTRAINT users_department_fk FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL;
ALTER TABLE tenants ADD CONSTRAINT tenants_package_fk FOREIGN KEY (package_id) REFERENCES tenant_packages(id) ON DELETE RESTRICT;
ALTER TABLE tenant_package_features ADD CONSTRAINT tenant_package_features_package_fk FOREIGN KEY (package_id) REFERENCES tenant_packages(id) ON DELETE CASCADE;
ALTER TABLE departments ADD CONSTRAINT departments_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE departments ADD CONSTRAINT departments_leader_fk FOREIGN KEY (leader_id) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE positions ADD CONSTRAINT positions_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE user_positions ADD CONSTRAINT user_positions_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE user_positions ADD CONSTRAINT user_positions_position_fk FOREIGN KEY (position_id) REFERENCES positions(id) ON DELETE CASCADE;
ALTER TABLE roles ADD CONSTRAINT roles_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE sessions ADD CONSTRAINT sessions_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE user_roles ADD CONSTRAINT user_roles_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE user_roles ADD CONSTRAINT user_roles_role_fk FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE;
ALTER TABLE role_permissions ADD CONSTRAINT role_permissions_role_fk FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE;
ALTER TABLE role_menus ADD CONSTRAINT role_menus_role_fk FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE;
ALTER TABLE role_menus ADD CONSTRAINT role_menus_menu_fk FOREIGN KEY (menu_id) REFERENCES menus(id) ON DELETE CASCADE;
ALTER TABLE user_menus ADD CONSTRAINT user_menus_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE user_menus ADD CONSTRAINT user_menus_menu_fk FOREIGN KEY (menu_id) REFERENCES menus(id) ON DELETE CASCADE;
ALTER TABLE role_departments ADD CONSTRAINT role_departments_role_fk FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE;
ALTER TABLE role_departments ADD CONSTRAINT role_departments_department_fk FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE CASCADE;
ALTER TABLE user_permissions ADD CONSTRAINT user_permissions_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE user_department_scopes ADD CONSTRAINT user_department_scopes_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE user_department_scopes ADD CONSTRAINT user_department_scopes_department_fk FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE CASCADE;
ALTER TABLE user_groups ADD CONSTRAINT user_groups_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE user_groups ADD CONSTRAINT user_groups_owner_fk FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE user_group_members ADD CONSTRAINT user_group_members_group_fk FOREIGN KEY (group_id) REFERENCES user_groups(id) ON DELETE CASCADE;
ALTER TABLE user_group_members ADD CONSTRAINT user_group_members_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE user_group_roles ADD CONSTRAINT user_group_roles_group_fk FOREIGN KEY (group_id) REFERENCES user_groups(id) ON DELETE CASCADE;
ALTER TABLE user_group_roles ADD CONSTRAINT user_group_roles_role_fk FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE;
ALTER TABLE dicts ADD CONSTRAINT dicts_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE dict_items ADD CONSTRAINT dict_items_dict_fk FOREIGN KEY (dict_id) REFERENCES dicts(id) ON DELETE CASCADE;
ALTER TABLE dict_items ADD CONSTRAINT dict_items_parent_fk FOREIGN KEY (parent_id) REFERENCES dict_items(id) ON DELETE SET NULL;
ALTER TABLE managed_files ADD CONSTRAINT managed_files_storage_fk FOREIGN KEY (storage_config_id) REFERENCES file_storage_configs(id) ON DELETE RESTRICT;
ALTER TABLE managed_files ADD CONSTRAINT managed_files_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE managed_files ADD CONSTRAINT managed_files_uploader_fk FOREIGN KEY (uploader_id) REFERENCES users(id) ON DELETE RESTRICT;
ALTER TABLE upload_sessions ADD CONSTRAINT upload_sessions_storage_fk FOREIGN KEY (storage_config_id) REFERENCES file_storage_configs(id) ON DELETE RESTRICT;
ALTER TABLE upload_sessions ADD CONSTRAINT upload_sessions_tenant_fk FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE;
ALTER TABLE upload_sessions ADD CONSTRAINT upload_sessions_uploader_fk FOREIGN KEY (uploader_id) REFERENCES users(id) ON DELETE RESTRICT;
ALTER TABLE upload_chunks ADD CONSTRAINT upload_chunks_session_fk FOREIGN KEY (upload_id) REFERENCES upload_sessions(id) ON DELETE CASCADE;
