CREATE TABLE "system_settings" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "module" character varying NOT NULL, "version" bigint NOT NULL, "data" jsonb NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "system_settings_module_key" ON "system_settings" ("module");
