// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fudanda/zenith-admin/backend/ent/auditlog"
	"github.com/fudanda/zenith-admin/backend/ent/predicate"
)

// AuditLogUpdate is the builder for updating AuditLog entities.
type AuditLogUpdate struct {
	config
	hooks    []Hook
	mutation *AuditLogMutation
}

// Where appends a list predicates to the AuditLogUpdate builder.
func (_u *AuditLogUpdate) Where(ps ...predicate.AuditLog) *AuditLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetActorID sets the "actor_id" field.
func (_u *AuditLogUpdate) SetActorID(v int) *AuditLogUpdate {
	_u.mutation.ResetActorID()
	_u.mutation.SetActorID(v)
	return _u
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableActorID(v *int) *AuditLogUpdate {
	if v != nil {
		_u.SetActorID(*v)
	}
	return _u
}

// AddActorID adds value to the "actor_id" field.
func (_u *AuditLogUpdate) AddActorID(v int) *AuditLogUpdate {
	_u.mutation.AddActorID(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *AuditLogUpdate) SetTenantID(v int) *AuditLogUpdate {
	_u.mutation.ResetTenantID()
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableTenantID(v *int) *AuditLogUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// AddTenantID adds value to the "tenant_id" field.
func (_u *AuditLogUpdate) AddTenantID(v int) *AuditLogUpdate {
	_u.mutation.AddTenantID(v)
	return _u
}

// ClearTenantID clears the value of the "tenant_id" field.
func (_u *AuditLogUpdate) ClearTenantID() *AuditLogUpdate {
	_u.mutation.ClearTenantID()
	return _u
}

// SetOperation sets the "operation" field.
func (_u *AuditLogUpdate) SetOperation(v string) *AuditLogUpdate {
	_u.mutation.SetOperation(v)
	return _u
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableOperation(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetOperation(*v)
	}
	return _u
}

// SetResource sets the "resource" field.
func (_u *AuditLogUpdate) SetResource(v string) *AuditLogUpdate {
	_u.mutation.SetResource(v)
	return _u
}

// SetNillableResource sets the "resource" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableResource(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetResource(*v)
	}
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *AuditLogUpdate) SetResourceID(v int) *AuditLogUpdate {
	_u.mutation.ResetResourceID()
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableResourceID(v *int) *AuditLogUpdate {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// AddResourceID adds value to the "resource_id" field.
func (_u *AuditLogUpdate) AddResourceID(v int) *AuditLogUpdate {
	_u.mutation.AddResourceID(v)
	return _u
}

// ClearResourceID clears the value of the "resource_id" field.
func (_u *AuditLogUpdate) ClearResourceID() *AuditLogUpdate {
	_u.mutation.ClearResourceID()
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *AuditLogUpdate) SetRequestID(v string) *AuditLogUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableRequestID(v *string) *AuditLogUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *AuditLogUpdate) ClearRequestID() *AuditLogUpdate {
	_u.mutation.ClearRequestID()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AuditLogUpdate) SetCreatedAt(v time.Time) *AuditLogUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AuditLogUpdate) SetNillableCreatedAt(v *time.Time) *AuditLogUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the AuditLogMutation object of the builder.
func (_u *AuditLogUpdate) Mutation() *AuditLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuditLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuditLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuditLogUpdate) check() error {
	if v, ok := _u.mutation.Operation(); ok {
		if err := auditlog.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "AuditLog.operation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Resource(); ok {
		if err := auditlog.ResourceValidator(v); err != nil {
			return &ValidationError{Name: "resource", err: fmt.Errorf(`ent: validator failed for field "AuditLog.resource": %w`, err)}
		}
	}
	return nil
}

func (_u *AuditLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(auditlog.Table, auditlog.Columns, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ActorID(); ok {
		_spec.SetField(auditlog.FieldActorID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedActorID(); ok {
		_spec.AddField(auditlog.FieldActorID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(auditlog.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTenantID(); ok {
		_spec.AddField(auditlog.FieldTenantID, field.TypeInt, value)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(auditlog.FieldTenantID, field.TypeInt)
	}
	if value, ok := _u.mutation.Operation(); ok {
		_spec.SetField(auditlog.FieldOperation, field.TypeString, value)
	}
	if value, ok := _u.mutation.Resource(); ok {
		_spec.SetField(auditlog.FieldResource, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(auditlog.FieldResourceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResourceID(); ok {
		_spec.AddField(auditlog.FieldResourceID, field.TypeInt, value)
	}
	if _u.mutation.ResourceIDCleared() {
		_spec.ClearField(auditlog.FieldResourceID, field.TypeInt)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(auditlog.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(auditlog.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(auditlog.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuditLogUpdateOne is the builder for updating a single AuditLog entity.
type AuditLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuditLogMutation
}

// SetActorID sets the "actor_id" field.
func (_u *AuditLogUpdateOne) SetActorID(v int) *AuditLogUpdateOne {
	_u.mutation.ResetActorID()
	_u.mutation.SetActorID(v)
	return _u
}

// SetNillableActorID sets the "actor_id" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableActorID(v *int) *AuditLogUpdateOne {
	if v != nil {
		_u.SetActorID(*v)
	}
	return _u
}

// AddActorID adds value to the "actor_id" field.
func (_u *AuditLogUpdateOne) AddActorID(v int) *AuditLogUpdateOne {
	_u.mutation.AddActorID(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *AuditLogUpdateOne) SetTenantID(v int) *AuditLogUpdateOne {
	_u.mutation.ResetTenantID()
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableTenantID(v *int) *AuditLogUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// AddTenantID adds value to the "tenant_id" field.
func (_u *AuditLogUpdateOne) AddTenantID(v int) *AuditLogUpdateOne {
	_u.mutation.AddTenantID(v)
	return _u
}

// ClearTenantID clears the value of the "tenant_id" field.
func (_u *AuditLogUpdateOne) ClearTenantID() *AuditLogUpdateOne {
	_u.mutation.ClearTenantID()
	return _u
}

// SetOperation sets the "operation" field.
func (_u *AuditLogUpdateOne) SetOperation(v string) *AuditLogUpdateOne {
	_u.mutation.SetOperation(v)
	return _u
}

// SetNillableOperation sets the "operation" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableOperation(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetOperation(*v)
	}
	return _u
}

// SetResource sets the "resource" field.
func (_u *AuditLogUpdateOne) SetResource(v string) *AuditLogUpdateOne {
	_u.mutation.SetResource(v)
	return _u
}

// SetNillableResource sets the "resource" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableResource(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetResource(*v)
	}
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *AuditLogUpdateOne) SetResourceID(v int) *AuditLogUpdateOne {
	_u.mutation.ResetResourceID()
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableResourceID(v *int) *AuditLogUpdateOne {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// AddResourceID adds value to the "resource_id" field.
func (_u *AuditLogUpdateOne) AddResourceID(v int) *AuditLogUpdateOne {
	_u.mutation.AddResourceID(v)
	return _u
}

// ClearResourceID clears the value of the "resource_id" field.
func (_u *AuditLogUpdateOne) ClearResourceID() *AuditLogUpdateOne {
	_u.mutation.ClearResourceID()
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *AuditLogUpdateOne) SetRequestID(v string) *AuditLogUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableRequestID(v *string) *AuditLogUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *AuditLogUpdateOne) ClearRequestID() *AuditLogUpdateOne {
	_u.mutation.ClearRequestID()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AuditLogUpdateOne) SetCreatedAt(v time.Time) *AuditLogUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AuditLogUpdateOne) SetNillableCreatedAt(v *time.Time) *AuditLogUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the AuditLogMutation object of the builder.
func (_u *AuditLogUpdateOne) Mutation() *AuditLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the AuditLogUpdate builder.
func (_u *AuditLogUpdateOne) Where(ps ...predicate.AuditLog) *AuditLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuditLogUpdateOne) Select(field string, fields ...string) *AuditLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuditLog entity.
func (_u *AuditLogUpdateOne) Save(ctx context.Context) (*AuditLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditLogUpdateOne) SaveX(ctx context.Context) *AuditLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuditLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuditLogUpdateOne) check() error {
	if v, ok := _u.mutation.Operation(); ok {
		if err := auditlog.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "AuditLog.operation": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Resource(); ok {
		if err := auditlog.ResourceValidator(v); err != nil {
			return &ValidationError{Name: "resource", err: fmt.Errorf(`ent: validator failed for field "AuditLog.resource": %w`, err)}
		}
	}
	return nil
}

func (_u *AuditLogUpdateOne) sqlSave(ctx context.Context) (_node *AuditLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(auditlog.Table, auditlog.Columns, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuditLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, auditlog.FieldID)
		for _, f := range fields {
			if !auditlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != auditlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ActorID(); ok {
		_spec.SetField(auditlog.FieldActorID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedActorID(); ok {
		_spec.AddField(auditlog.FieldActorID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(auditlog.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTenantID(); ok {
		_spec.AddField(auditlog.FieldTenantID, field.TypeInt, value)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(auditlog.FieldTenantID, field.TypeInt)
	}
	if value, ok := _u.mutation.Operation(); ok {
		_spec.SetField(auditlog.FieldOperation, field.TypeString, value)
	}
	if value, ok := _u.mutation.Resource(); ok {
		_spec.SetField(auditlog.FieldResource, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(auditlog.FieldResourceID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResourceID(); ok {
		_spec.AddField(auditlog.FieldResourceID, field.TypeInt, value)
	}
	if _u.mutation.ResourceIDCleared() {
		_spec.ClearField(auditlog.FieldResourceID, field.TypeInt)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(auditlog.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(auditlog.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(auditlog.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &AuditLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
