// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fudanda/arcbase/backend/ent/captcha"
	"github.com/fudanda/arcbase/backend/ent/predicate"
)

// CaptchaUpdate is the builder for updating Captcha entities.
type CaptchaUpdate struct {
	config
	hooks    []Hook
	mutation *CaptchaMutation
}

// Where appends a list predicates to the CaptchaUpdate builder.
func (_u *CaptchaUpdate) Where(ps ...predicate.Captcha) *CaptchaUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPublicID sets the "public_id" field.
func (_u *CaptchaUpdate) SetPublicID(v string) *CaptchaUpdate {
	_u.mutation.SetPublicID(v)
	return _u
}

// SetNillablePublicID sets the "public_id" field if the given value is not nil.
func (_u *CaptchaUpdate) SetNillablePublicID(v *string) *CaptchaUpdate {
	if v != nil {
		_u.SetPublicID(*v)
	}
	return _u
}

// SetAnswerHash sets the "answer_hash" field.
func (_u *CaptchaUpdate) SetAnswerHash(v string) *CaptchaUpdate {
	_u.mutation.SetAnswerHash(v)
	return _u
}

// SetNillableAnswerHash sets the "answer_hash" field if the given value is not nil.
func (_u *CaptchaUpdate) SetNillableAnswerHash(v *string) *CaptchaUpdate {
	if v != nil {
		_u.SetAnswerHash(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *CaptchaUpdate) SetExpiresAt(v time.Time) *CaptchaUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *CaptchaUpdate) SetNillableExpiresAt(v *time.Time) *CaptchaUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUsedAt sets the "used_at" field.
func (_u *CaptchaUpdate) SetUsedAt(v time.Time) *CaptchaUpdate {
	_u.mutation.SetUsedAt(v)
	return _u
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_u *CaptchaUpdate) SetNillableUsedAt(v *time.Time) *CaptchaUpdate {
	if v != nil {
		_u.SetUsedAt(*v)
	}
	return _u
}

// ClearUsedAt clears the value of the "used_at" field.
func (_u *CaptchaUpdate) ClearUsedAt() *CaptchaUpdate {
	_u.mutation.ClearUsedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CaptchaUpdate) SetCreatedAt(v time.Time) *CaptchaUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CaptchaUpdate) SetNillableCreatedAt(v *time.Time) *CaptchaUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the CaptchaMutation object of the builder.
func (_u *CaptchaUpdate) Mutation() *CaptchaMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CaptchaUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CaptchaUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CaptchaUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CaptchaUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CaptchaUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(captcha.Table, captcha.Columns, sqlgraph.NewFieldSpec(captcha.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PublicID(); ok {
		_spec.SetField(captcha.FieldPublicID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AnswerHash(); ok {
		_spec.SetField(captcha.FieldAnswerHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(captcha.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UsedAt(); ok {
		_spec.SetField(captcha.FieldUsedAt, field.TypeTime, value)
	}
	if _u.mutation.UsedAtCleared() {
		_spec.ClearField(captcha.FieldUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(captcha.FieldCreatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{captcha.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CaptchaUpdateOne is the builder for updating a single Captcha entity.
type CaptchaUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CaptchaMutation
}

// SetPublicID sets the "public_id" field.
func (_u *CaptchaUpdateOne) SetPublicID(v string) *CaptchaUpdateOne {
	_u.mutation.SetPublicID(v)
	return _u
}

// SetNillablePublicID sets the "public_id" field if the given value is not nil.
func (_u *CaptchaUpdateOne) SetNillablePublicID(v *string) *CaptchaUpdateOne {
	if v != nil {
		_u.SetPublicID(*v)
	}
	return _u
}

// SetAnswerHash sets the "answer_hash" field.
func (_u *CaptchaUpdateOne) SetAnswerHash(v string) *CaptchaUpdateOne {
	_u.mutation.SetAnswerHash(v)
	return _u
}

// SetNillableAnswerHash sets the "answer_hash" field if the given value is not nil.
func (_u *CaptchaUpdateOne) SetNillableAnswerHash(v *string) *CaptchaUpdateOne {
	if v != nil {
		_u.SetAnswerHash(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *CaptchaUpdateOne) SetExpiresAt(v time.Time) *CaptchaUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *CaptchaUpdateOne) SetNillableExpiresAt(v *time.Time) *CaptchaUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUsedAt sets the "used_at" field.
func (_u *CaptchaUpdateOne) SetUsedAt(v time.Time) *CaptchaUpdateOne {
	_u.mutation.SetUsedAt(v)
	return _u
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_u *CaptchaUpdateOne) SetNillableUsedAt(v *time.Time) *CaptchaUpdateOne {
	if v != nil {
		_u.SetUsedAt(*v)
	}
	return _u
}

// ClearUsedAt clears the value of the "used_at" field.
func (_u *CaptchaUpdateOne) ClearUsedAt() *CaptchaUpdateOne {
	_u.mutation.ClearUsedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CaptchaUpdateOne) SetCreatedAt(v time.Time) *CaptchaUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CaptchaUpdateOne) SetNillableCreatedAt(v *time.Time) *CaptchaUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// Mutation returns the CaptchaMutation object of the builder.
func (_u *CaptchaUpdateOne) Mutation() *CaptchaMutation {
	return _u.mutation
}

// Where appends a list predicates to the CaptchaUpdate builder.
func (_u *CaptchaUpdateOne) Where(ps ...predicate.Captcha) *CaptchaUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CaptchaUpdateOne) Select(field string, fields ...string) *CaptchaUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Captcha entity.
func (_u *CaptchaUpdateOne) Save(ctx context.Context) (*Captcha, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CaptchaUpdateOne) SaveX(ctx context.Context) *Captcha {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CaptchaUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CaptchaUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CaptchaUpdateOne) sqlSave(ctx context.Context) (_node *Captcha, err error) {
	_spec := sqlgraph.NewUpdateSpec(captcha.Table, captcha.Columns, sqlgraph.NewFieldSpec(captcha.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Captcha.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, captcha.FieldID)
		for _, f := range fields {
			if !captcha.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != captcha.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PublicID(); ok {
		_spec.SetField(captcha.FieldPublicID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AnswerHash(); ok {
		_spec.SetField(captcha.FieldAnswerHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(captcha.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UsedAt(); ok {
		_spec.SetField(captcha.FieldUsedAt, field.TypeTime, value)
	}
	if _u.mutation.UsedAtCleared() {
		_spec.ClearField(captcha.FieldUsedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(captcha.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &Captcha{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{captcha.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
