// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fudanda/arcbase/backend/ent/dictitem"
)

// DictItemCreate is the builder for creating a DictItem entity.
type DictItemCreate struct {
	config
	mutation *DictItemMutation
	hooks    []Hook
}

// SetDictID sets the "dict_id" field.
func (_c *DictItemCreate) SetDictID(v int) *DictItemCreate {
	_c.mutation.SetDictID(v)
	return _c
}

// SetParentID sets the "parent_id" field.
func (_c *DictItemCreate) SetParentID(v int) *DictItemCreate {
	_c.mutation.SetParentID(v)
	return _c
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_c *DictItemCreate) SetNillableParentID(v *int) *DictItemCreate {
	if v != nil {
		_c.SetParentID(*v)
	}
	return _c
}

// SetLabel sets the "label" field.
func (_c *DictItemCreate) SetLabel(v string) *DictItemCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *DictItemCreate) SetValue(v string) *DictItemCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetColor sets the "color" field.
func (_c *DictItemCreate) SetColor(v string) *DictItemCreate {
	_c.mutation.SetColor(v)
	return _c
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (_c *DictItemCreate) SetNillableColor(v *string) *DictItemCreate {
	if v != nil {
		_c.SetColor(*v)
	}
	return _c
}

// SetSort sets the "sort" field.
func (_c *DictItemCreate) SetSort(v int) *DictItemCreate {
	_c.mutation.SetSort(v)
	return _c
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_c *DictItemCreate) SetNillableSort(v *int) *DictItemCreate {
	if v != nil {
		_c.SetSort(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *DictItemCreate) SetStatus(v string) *DictItemCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *DictItemCreate) SetNillableStatus(v *string) *DictItemCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *DictItemCreate) SetRemark(v string) *DictItemCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *DictItemCreate) SetNillableRemark(v *string) *DictItemCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *DictItemCreate) SetMetadata(v map[string]interface{}) *DictItemCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *DictItemCreate) SetCreatedBy(v int) *DictItemCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *DictItemCreate) SetNillableCreatedBy(v *int) *DictItemCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *DictItemCreate) SetUpdatedBy(v int) *DictItemCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *DictItemCreate) SetNillableUpdatedBy(v *int) *DictItemCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DictItemCreate) SetCreatedAt(v time.Time) *DictItemCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DictItemCreate) SetNillableCreatedAt(v *time.Time) *DictItemCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DictItemCreate) SetUpdatedAt(v time.Time) *DictItemCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DictItemCreate) SetNillableUpdatedAt(v *time.Time) *DictItemCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the DictItemMutation object of the builder.
func (_c *DictItemCreate) Mutation() *DictItemMutation {
	return _c.mutation
}

// Save creates the DictItem in the database.
func (_c *DictItemCreate) Save(ctx context.Context) (*DictItem, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DictItemCreate) SaveX(ctx context.Context) *DictItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DictItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DictItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DictItemCreate) defaults() {
	if _, ok := _c.mutation.Sort(); !ok {
		v := dictitem.DefaultSort
		_c.mutation.SetSort(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := dictitem.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := dictitem.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := dictitem.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DictItemCreate) check() error {
	if _, ok := _c.mutation.DictID(); !ok {
		return &ValidationError{Name: "dict_id", err: errors.New(`ent: missing required field "DictItem.dict_id"`)}
	}
	if _, ok := _c.mutation.Label(); !ok {
		return &ValidationError{Name: "label", err: errors.New(`ent: missing required field "DictItem.label"`)}
	}
	if v, ok := _c.mutation.Label(); ok {
		if err := dictitem.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "DictItem.label": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "DictItem.value"`)}
	}
	if v, ok := _c.mutation.Value(); ok {
		if err := dictitem.ValueValidator(v); err != nil {
			return &ValidationError{Name: "value", err: fmt.Errorf(`ent: validator failed for field "DictItem.value": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Sort(); !ok {
		return &ValidationError{Name: "sort", err: errors.New(`ent: missing required field "DictItem.sort"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "DictItem.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DictItem.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DictItem.updated_at"`)}
	}
	return nil
}

func (_c *DictItemCreate) sqlSave(ctx context.Context) (*DictItem, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DictItemCreate) createSpec() (*DictItem, *sqlgraph.CreateSpec) {
	var (
		_node = &DictItem{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(dictitem.Table, sqlgraph.NewFieldSpec(dictitem.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.DictID(); ok {
		_spec.SetField(dictitem.FieldDictID, field.TypeInt, value)
		_node.DictID = value
	}
	if value, ok := _c.mutation.ParentID(); ok {
		_spec.SetField(dictitem.FieldParentID, field.TypeInt, value)
		_node.ParentID = &value
	}
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(dictitem.FieldLabel, field.TypeString, value)
		_node.Label = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(dictitem.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if value, ok := _c.mutation.Color(); ok {
		_spec.SetField(dictitem.FieldColor, field.TypeString, value)
		_node.Color = &value
	}
	if value, ok := _c.mutation.Sort(); ok {
		_spec.SetField(dictitem.FieldSort, field.TypeInt, value)
		_node.Sort = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(dictitem.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(dictitem.FieldRemark, field.TypeString, value)
		_node.Remark = &value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(dictitem.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(dictitem.FieldCreatedBy, field.TypeInt, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(dictitem.FieldUpdatedBy, field.TypeInt, value)
		_node.UpdatedBy = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(dictitem.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(dictitem.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// DictItemCreateBulk is the builder for creating many DictItem entities in bulk.
type DictItemCreateBulk struct {
	config
	err      error
	builders []*DictItemCreate
}

// Save creates the DictItem entities in the database.
func (_c *DictItemCreateBulk) Save(ctx context.Context) ([]*DictItem, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DictItem, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DictItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DictItemCreateBulk) SaveX(ctx context.Context) []*DictItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DictItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DictItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
