// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fudanda/arcbase/backend/ent/filestorageconfig"
)

// FileStorageConfigCreate is the builder for creating a FileStorageConfig entity.
type FileStorageConfigCreate struct {
	config
	mutation *FileStorageConfigMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *FileStorageConfigCreate) SetName(v string) *FileStorageConfigCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *FileStorageConfigCreate) SetProvider(v string) *FileStorageConfigCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_c *FileStorageConfigCreate) SetNillableProvider(v *string) *FileStorageConfigCreate {
	if v != nil {
		_c.SetProvider(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *FileStorageConfigCreate) SetStatus(v string) *FileStorageConfigCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *FileStorageConfigCreate) SetNillableStatus(v *string) *FileStorageConfigCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetIsDefault sets the "is_default" field.
func (_c *FileStorageConfigCreate) SetIsDefault(v bool) *FileStorageConfigCreate {
	_c.mutation.SetIsDefault(v)
	return _c
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_c *FileStorageConfigCreate) SetNillableIsDefault(v *bool) *FileStorageConfigCreate {
	if v != nil {
		_c.SetIsDefault(*v)
	}
	return _c
}

// SetLocalRootPath sets the "local_root_path" field.
func (_c *FileStorageConfigCreate) SetLocalRootPath(v string) *FileStorageConfigCreate {
	_c.mutation.SetLocalRootPath(v)
	return _c
}

// SetRemark sets the "remark" field.
func (_c *FileStorageConfigCreate) SetRemark(v string) *FileStorageConfigCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *FileStorageConfigCreate) SetNillableRemark(v *string) *FileStorageConfigCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetS3Region sets the "s3_region" field.
func (_c *FileStorageConfigCreate) SetS3Region(v string) *FileStorageConfigCreate {
	_c.mutation.SetS3Region(v)
	return _c
}

// SetNillableS3Region sets the "s3_region" field if the given value is not nil.
func (_c *FileStorageConfigCreate) SetNillableS3Region(v *string) *FileStorageConfigCreate {
	if v != nil {
		_c.SetS3Region(*v)
	}
	return _c
}

// SetS3Endpoint sets the "s3_endpoint" field.
func (_c *FileStorageConfigCreate) SetS3Endpoint(v string) *FileStorageConfigCreate {
	_c.mutation.SetS3Endpoint(v)
	return _c
}

// SetNillableS3Endpoint sets the "s3_endpoint" field if the given value is not nil.
func (_c *FileStorageConfigCreate) SetNillableS3Endpoint(v *string) *FileStorageConfigCreate {
	if v != nil {
		_c.SetS3Endpoint(*v)
	}
	return _c
}

// SetS3Bucket sets the "s3_bucket" field.
func (_c *FileStorageConfigCreate) SetS3Bucket(v string) *FileStorageConfigCreate {
	_c.mutation.SetS3Bucket(v)
	return _c
}

// SetNillableS3Bucket sets the "s3_bucket" field if the given value is not nil.
func (_c *FileStorageConfigCreate) SetNillableS3Bucket(v *string) *FileStorageConfigCreate {
	if v != nil {
		_c.SetS3Bucket(*v)
	}
	return _c
}

// SetS3AccessKeyID sets the "s3_access_key_id" field.
func (_c *FileStorageConfigCreate) SetS3AccessKeyID(v string) *FileStorageConfigCreate {
	_c.mutation.SetS3AccessKeyID(v)
	return _c
}

// SetNillableS3AccessKeyID sets the "s3_access_key_id" field if the given value is not nil.
func (_c *FileStorageConfigCreate) SetNillableS3AccessKeyID(v *string) *FileStorageConfigCreate {
	if v != nil {
		_c.SetS3AccessKeyID(*v)
	}
	return _c
}

// SetS3SecretCipher sets the "s3_secret_cipher" field.
func (_c *FileStorageConfigCreate) SetS3SecretCipher(v string) *FileStorageConfigCreate {
	_c.mutation.SetS3SecretCipher(v)
	return _c
}

// SetNillableS3SecretCipher sets the "s3_secret_cipher" field if the given value is not nil.
func (_c *FileStorageConfigCreate) SetNillableS3SecretCipher(v *string) *FileStorageConfigCreate {
	if v != nil {
		_c.SetS3SecretCipher(*v)
	}
	return _c
}

// SetS3ForcePathStyle sets the "s3_force_path_style" field.
func (_c *FileStorageConfigCreate) SetS3ForcePathStyle(v bool) *FileStorageConfigCreate {
	_c.mutation.SetS3ForcePathStyle(v)
	return _c
}

// SetNillableS3ForcePathStyle sets the "s3_force_path_style" field if the given value is not nil.
func (_c *FileStorageConfigCreate) SetNillableS3ForcePathStyle(v *bool) *FileStorageConfigCreate {
	if v != nil {
		_c.SetS3ForcePathStyle(*v)
	}
	return _c
}

// SetBasePath sets the "base_path" field.
func (_c *FileStorageConfigCreate) SetBasePath(v string) *FileStorageConfigCreate {
	_c.mutation.SetBasePath(v)
	return _c
}

// SetNillableBasePath sets the "base_path" field if the given value is not nil.
func (_c *FileStorageConfigCreate) SetNillableBasePath(v *string) *FileStorageConfigCreate {
	if v != nil {
		_c.SetBasePath(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *FileStorageConfigCreate) SetCreatedAt(v time.Time) *FileStorageConfigCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *FileStorageConfigCreate) SetNillableCreatedAt(v *time.Time) *FileStorageConfigCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *FileStorageConfigCreate) SetUpdatedAt(v time.Time) *FileStorageConfigCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *FileStorageConfigCreate) SetNillableUpdatedAt(v *time.Time) *FileStorageConfigCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the FileStorageConfigMutation object of the builder.
func (_c *FileStorageConfigCreate) Mutation() *FileStorageConfigMutation {
	return _c.mutation
}

// Save creates the FileStorageConfig in the database.
func (_c *FileStorageConfigCreate) Save(ctx context.Context) (*FileStorageConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FileStorageConfigCreate) SaveX(ctx context.Context) *FileStorageConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FileStorageConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FileStorageConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FileStorageConfigCreate) defaults() {
	if _, ok := _c.mutation.Provider(); !ok {
		v := filestorageconfig.DefaultProvider
		_c.mutation.SetProvider(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := filestorageconfig.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.IsDefault(); !ok {
		v := filestorageconfig.DefaultIsDefault
		_c.mutation.SetIsDefault(v)
	}
	if _, ok := _c.mutation.S3Region(); !ok {
		v := filestorageconfig.DefaultS3Region
		_c.mutation.SetS3Region(v)
	}
	if _, ok := _c.mutation.S3Endpoint(); !ok {
		v := filestorageconfig.DefaultS3Endpoint
		_c.mutation.SetS3Endpoint(v)
	}
	if _, ok := _c.mutation.S3Bucket(); !ok {
		v := filestorageconfig.DefaultS3Bucket
		_c.mutation.SetS3Bucket(v)
	}
	if _, ok := _c.mutation.S3AccessKeyID(); !ok {
		v := filestorageconfig.DefaultS3AccessKeyID
		_c.mutation.SetS3AccessKeyID(v)
	}
	if _, ok := _c.mutation.S3SecretCipher(); !ok {
		v := filestorageconfig.DefaultS3SecretCipher
		_c.mutation.SetS3SecretCipher(v)
	}
	if _, ok := _c.mutation.S3ForcePathStyle(); !ok {
		v := filestorageconfig.DefaultS3ForcePathStyle
		_c.mutation.SetS3ForcePathStyle(v)
	}
	if _, ok := _c.mutation.BasePath(); !ok {
		v := filestorageconfig.DefaultBasePath
		_c.mutation.SetBasePath(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := filestorageconfig.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := filestorageconfig.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FileStorageConfigCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "FileStorageConfig.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := filestorageconfig.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "FileStorageConfig.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "FileStorageConfig.provider"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "FileStorageConfig.status"`)}
	}
	if _, ok := _c.mutation.IsDefault(); !ok {
		return &ValidationError{Name: "is_default", err: errors.New(`ent: missing required field "FileStorageConfig.is_default"`)}
	}
	if _, ok := _c.mutation.LocalRootPath(); !ok {
		return &ValidationError{Name: "local_root_path", err: errors.New(`ent: missing required field "FileStorageConfig.local_root_path"`)}
	}
	if v, ok := _c.mutation.LocalRootPath(); ok {
		if err := filestorageconfig.LocalRootPathValidator(v); err != nil {
			return &ValidationError{Name: "local_root_path", err: fmt.Errorf(`ent: validator failed for field "FileStorageConfig.local_root_path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.S3Region(); !ok {
		return &ValidationError{Name: "s3_region", err: errors.New(`ent: missing required field "FileStorageConfig.s3_region"`)}
	}
	if _, ok := _c.mutation.S3Endpoint(); !ok {
		return &ValidationError{Name: "s3_endpoint", err: errors.New(`ent: missing required field "FileStorageConfig.s3_endpoint"`)}
	}
	if _, ok := _c.mutation.S3Bucket(); !ok {
		return &ValidationError{Name: "s3_bucket", err: errors.New(`ent: missing required field "FileStorageConfig.s3_bucket"`)}
	}
	if _, ok := _c.mutation.S3AccessKeyID(); !ok {
		return &ValidationError{Name: "s3_access_key_id", err: errors.New(`ent: missing required field "FileStorageConfig.s3_access_key_id"`)}
	}
	if _, ok := _c.mutation.S3SecretCipher(); !ok {
		return &ValidationError{Name: "s3_secret_cipher", err: errors.New(`ent: missing required field "FileStorageConfig.s3_secret_cipher"`)}
	}
	if _, ok := _c.mutation.S3ForcePathStyle(); !ok {
		return &ValidationError{Name: "s3_force_path_style", err: errors.New(`ent: missing required field "FileStorageConfig.s3_force_path_style"`)}
	}
	if _, ok := _c.mutation.BasePath(); !ok {
		return &ValidationError{Name: "base_path", err: errors.New(`ent: missing required field "FileStorageConfig.base_path"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "FileStorageConfig.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "FileStorageConfig.updated_at"`)}
	}
	return nil
}

func (_c *FileStorageConfigCreate) sqlSave(ctx context.Context) (*FileStorageConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FileStorageConfigCreate) createSpec() (*FileStorageConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &FileStorageConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(filestorageconfig.Table, sqlgraph.NewFieldSpec(filestorageconfig.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(filestorageconfig.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(filestorageconfig.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(filestorageconfig.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.IsDefault(); ok {
		_spec.SetField(filestorageconfig.FieldIsDefault, field.TypeBool, value)
		_node.IsDefault = value
	}
	if value, ok := _c.mutation.LocalRootPath(); ok {
		_spec.SetField(filestorageconfig.FieldLocalRootPath, field.TypeString, value)
		_node.LocalRootPath = value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(filestorageconfig.FieldRemark, field.TypeString, value)
		_node.Remark = &value
	}
	if value, ok := _c.mutation.S3Region(); ok {
		_spec.SetField(filestorageconfig.FieldS3Region, field.TypeString, value)
		_node.S3Region = value
	}
	if value, ok := _c.mutation.S3Endpoint(); ok {
		_spec.SetField(filestorageconfig.FieldS3Endpoint, field.TypeString, value)
		_node.S3Endpoint = value
	}
	if value, ok := _c.mutation.S3Bucket(); ok {
		_spec.SetField(filestorageconfig.FieldS3Bucket, field.TypeString, value)
		_node.S3Bucket = value
	}
	if value, ok := _c.mutation.S3AccessKeyID(); ok {
		_spec.SetField(filestorageconfig.FieldS3AccessKeyID, field.TypeString, value)
		_node.S3AccessKeyID = value
	}
	if value, ok := _c.mutation.S3SecretCipher(); ok {
		_spec.SetField(filestorageconfig.FieldS3SecretCipher, field.TypeString, value)
		_node.S3SecretCipher = value
	}
	if value, ok := _c.mutation.S3ForcePathStyle(); ok {
		_spec.SetField(filestorageconfig.FieldS3ForcePathStyle, field.TypeBool, value)
		_node.S3ForcePathStyle = value
	}
	if value, ok := _c.mutation.BasePath(); ok {
		_spec.SetField(filestorageconfig.FieldBasePath, field.TypeString, value)
		_node.BasePath = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(filestorageconfig.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(filestorageconfig.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// FileStorageConfigCreateBulk is the builder for creating many FileStorageConfig entities in bulk.
type FileStorageConfigCreateBulk struct {
	config
	err      error
	builders []*FileStorageConfigCreate
}

// Save creates the FileStorageConfig entities in the database.
func (_c *FileStorageConfigCreateBulk) Save(ctx context.Context) ([]*FileStorageConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FileStorageConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FileStorageConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FileStorageConfigCreateBulk) SaveX(ctx context.Context) []*FileStorageConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FileStorageConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FileStorageConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
