// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fudanda/arcbase/backend/ent/loginlog"
)

// LoginLogCreate is the builder for creating a LoginLog entity.
type LoginLogCreate struct {
	config
	mutation *LoginLogMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *LoginLogCreate) SetUserID(v int) *LoginLogCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *LoginLogCreate) SetNillableUserID(v *int) *LoginLogCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetUsername sets the "username" field.
func (_c *LoginLogCreate) SetUsername(v string) *LoginLogCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetIP sets the "ip" field.
func (_c *LoginLogCreate) SetIP(v string) *LoginLogCreate {
	_c.mutation.SetIP(v)
	return _c
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_c *LoginLogCreate) SetNillableIP(v *string) *LoginLogCreate {
	if v != nil {
		_c.SetIP(*v)
	}
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *LoginLogCreate) SetEventType(v string) *LoginLogCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_c *LoginLogCreate) SetNillableEventType(v *string) *LoginLogCreate {
	if v != nil {
		_c.SetEventType(*v)
	}
	return _c
}

// SetUserAgent sets the "user_agent" field.
func (_c *LoginLogCreate) SetUserAgent(v string) *LoginLogCreate {
	_c.mutation.SetUserAgent(v)
	return _c
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_c *LoginLogCreate) SetNillableUserAgent(v *string) *LoginLogCreate {
	if v != nil {
		_c.SetUserAgent(*v)
	}
	return _c
}

// SetBrowser sets the "browser" field.
func (_c *LoginLogCreate) SetBrowser(v string) *LoginLogCreate {
	_c.mutation.SetBrowser(v)
	return _c
}

// SetNillableBrowser sets the "browser" field if the given value is not nil.
func (_c *LoginLogCreate) SetNillableBrowser(v *string) *LoginLogCreate {
	if v != nil {
		_c.SetBrowser(*v)
	}
	return _c
}

// SetOs sets the "os" field.
func (_c *LoginLogCreate) SetOs(v string) *LoginLogCreate {
	_c.mutation.SetOs(v)
	return _c
}

// SetNillableOs sets the "os" field if the given value is not nil.
func (_c *LoginLogCreate) SetNillableOs(v *string) *LoginLogCreate {
	if v != nil {
		_c.SetOs(*v)
	}
	return _c
}

// SetSuccess sets the "success" field.
func (_c *LoginLogCreate) SetSuccess(v bool) *LoginLogCreate {
	_c.mutation.SetSuccess(v)
	return _c
}

// SetReason sets the "reason" field.
func (_c *LoginLogCreate) SetReason(v string) *LoginLogCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *LoginLogCreate) SetNillableReason(v *string) *LoginLogCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LoginLogCreate) SetCreatedAt(v time.Time) *LoginLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LoginLogCreate) SetNillableCreatedAt(v *time.Time) *LoginLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the LoginLogMutation object of the builder.
func (_c *LoginLogCreate) Mutation() *LoginLogMutation {
	return _c.mutation
}

// Save creates the LoginLog in the database.
func (_c *LoginLogCreate) Save(ctx context.Context) (*LoginLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LoginLogCreate) SaveX(ctx context.Context) *LoginLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LoginLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LoginLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LoginLogCreate) defaults() {
	if _, ok := _c.mutation.EventType(); !ok {
		v := loginlog.DefaultEventType
		_c.mutation.SetEventType(v)
	}
	if _, ok := _c.mutation.UserAgent(); !ok {
		v := loginlog.DefaultUserAgent
		_c.mutation.SetUserAgent(v)
	}
	if _, ok := _c.mutation.Browser(); !ok {
		v := loginlog.DefaultBrowser
		_c.mutation.SetBrowser(v)
	}
	if _, ok := _c.mutation.Os(); !ok {
		v := loginlog.DefaultOs
		_c.mutation.SetOs(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := loginlog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LoginLogCreate) check() error {
	if _, ok := _c.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "LoginLog.username"`)}
	}
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "LoginLog.event_type"`)}
	}
	if _, ok := _c.mutation.UserAgent(); !ok {
		return &ValidationError{Name: "user_agent", err: errors.New(`ent: missing required field "LoginLog.user_agent"`)}
	}
	if _, ok := _c.mutation.Browser(); !ok {
		return &ValidationError{Name: "browser", err: errors.New(`ent: missing required field "LoginLog.browser"`)}
	}
	if _, ok := _c.mutation.Os(); !ok {
		return &ValidationError{Name: "os", err: errors.New(`ent: missing required field "LoginLog.os"`)}
	}
	if _, ok := _c.mutation.Success(); !ok {
		return &ValidationError{Name: "success", err: errors.New(`ent: missing required field "LoginLog.success"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LoginLog.created_at"`)}
	}
	return nil
}

func (_c *LoginLogCreate) sqlSave(ctx context.Context) (*LoginLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LoginLogCreate) createSpec() (*LoginLog, *sqlgraph.CreateSpec) {
	var (
		_node = &LoginLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(loginlog.Table, sqlgraph.NewFieldSpec(loginlog.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(loginlog.FieldUserID, field.TypeInt, value)
		_node.UserID = &value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(loginlog.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.IP(); ok {
		_spec.SetField(loginlog.FieldIP, field.TypeString, value)
		_node.IP = value
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(loginlog.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.UserAgent(); ok {
		_spec.SetField(loginlog.FieldUserAgent, field.TypeString, value)
		_node.UserAgent = value
	}
	if value, ok := _c.mutation.Browser(); ok {
		_spec.SetField(loginlog.FieldBrowser, field.TypeString, value)
		_node.Browser = value
	}
	if value, ok := _c.mutation.Os(); ok {
		_spec.SetField(loginlog.FieldOs, field.TypeString, value)
		_node.Os = value
	}
	if value, ok := _c.mutation.Success(); ok {
		_spec.SetField(loginlog.FieldSuccess, field.TypeBool, value)
		_node.Success = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(loginlog.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(loginlog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// LoginLogCreateBulk is the builder for creating many LoginLog entities in bulk.
type LoginLogCreateBulk struct {
	config
	err      error
	builders []*LoginLogCreate
}

// Save creates the LoginLog entities in the database.
func (_c *LoginLogCreateBulk) Save(ctx context.Context) ([]*LoginLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LoginLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LoginLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LoginLogCreateBulk) SaveX(ctx context.Context) []*LoginLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LoginLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LoginLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
