// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fudanda/arcbase/backend/ent/menu"
	"github.com/fudanda/arcbase/backend/ent/predicate"
)

// MenuUpdate is the builder for updating Menu entities.
type MenuUpdate struct {
	config
	hooks    []Hook
	mutation *MenuMutation
}

// Where appends a list predicates to the MenuUpdate builder.
func (_u *MenuUpdate) Where(ps ...predicate.Menu) *MenuUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *MenuUpdate) SetParentID(v int) *MenuUpdate {
	_u.mutation.ResetParentID()
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *MenuUpdate) SetNillableParentID(v *int) *MenuUpdate {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// AddParentID adds value to the "parent_id" field.
func (_u *MenuUpdate) AddParentID(v int) *MenuUpdate {
	_u.mutation.AddParentID(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *MenuUpdate) SetTitle(v string) *MenuUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *MenuUpdate) SetNillableTitle(v *string) *MenuUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *MenuUpdate) SetName(v string) *MenuUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MenuUpdate) SetNillableName(v *string) *MenuUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *MenuUpdate) ClearName() *MenuUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetPath sets the "path" field.
func (_u *MenuUpdate) SetPath(v string) *MenuUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *MenuUpdate) SetNillablePath(v *string) *MenuUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// ClearPath clears the value of the "path" field.
func (_u *MenuUpdate) ClearPath() *MenuUpdate {
	_u.mutation.ClearPath()
	return _u
}

// SetComponent sets the "component" field.
func (_u *MenuUpdate) SetComponent(v string) *MenuUpdate {
	_u.mutation.SetComponent(v)
	return _u
}

// SetNillableComponent sets the "component" field if the given value is not nil.
func (_u *MenuUpdate) SetNillableComponent(v *string) *MenuUpdate {
	if v != nil {
		_u.SetComponent(*v)
	}
	return _u
}

// ClearComponent clears the value of the "component" field.
func (_u *MenuUpdate) ClearComponent() *MenuUpdate {
	_u.mutation.ClearComponent()
	return _u
}

// SetIcon sets the "icon" field.
func (_u *MenuUpdate) SetIcon(v string) *MenuUpdate {
	_u.mutation.SetIcon(v)
	return _u
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_u *MenuUpdate) SetNillableIcon(v *string) *MenuUpdate {
	if v != nil {
		_u.SetIcon(*v)
	}
	return _u
}

// ClearIcon clears the value of the "icon" field.
func (_u *MenuUpdate) ClearIcon() *MenuUpdate {
	_u.mutation.ClearIcon()
	return _u
}

// SetType sets the "type" field.
func (_u *MenuUpdate) SetType(v string) *MenuUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *MenuUpdate) SetNillableType(v *string) *MenuUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetPermission sets the "permission" field.
func (_u *MenuUpdate) SetPermission(v string) *MenuUpdate {
	_u.mutation.SetPermission(v)
	return _u
}

// SetNillablePermission sets the "permission" field if the given value is not nil.
func (_u *MenuUpdate) SetNillablePermission(v *string) *MenuUpdate {
	if v != nil {
		_u.SetPermission(*v)
	}
	return _u
}

// ClearPermission clears the value of the "permission" field.
func (_u *MenuUpdate) ClearPermission() *MenuUpdate {
	_u.mutation.ClearPermission()
	return _u
}

// SetQuery sets the "query" field.
func (_u *MenuUpdate) SetQuery(v string) *MenuUpdate {
	_u.mutation.SetQuery(v)
	return _u
}

// SetNillableQuery sets the "query" field if the given value is not nil.
func (_u *MenuUpdate) SetNillableQuery(v *string) *MenuUpdate {
	if v != nil {
		_u.SetQuery(*v)
	}
	return _u
}

// ClearQuery clears the value of the "query" field.
func (_u *MenuUpdate) ClearQuery() *MenuUpdate {
	_u.mutation.ClearQuery()
	return _u
}

// SetIsExternal sets the "is_external" field.
func (_u *MenuUpdate) SetIsExternal(v bool) *MenuUpdate {
	_u.mutation.SetIsExternal(v)
	return _u
}

// SetNillableIsExternal sets the "is_external" field if the given value is not nil.
func (_u *MenuUpdate) SetNillableIsExternal(v *bool) *MenuUpdate {
	if v != nil {
		_u.SetIsExternal(*v)
	}
	return _u
}

// SetEmbed sets the "embed" field.
func (_u *MenuUpdate) SetEmbed(v bool) *MenuUpdate {
	_u.mutation.SetEmbed(v)
	return _u
}

// SetNillableEmbed sets the "embed" field if the given value is not nil.
func (_u *MenuUpdate) SetNillableEmbed(v *bool) *MenuUpdate {
	if v != nil {
		_u.SetEmbed(*v)
	}
	return _u
}

// SetKeepAlive sets the "keep_alive" field.
func (_u *MenuUpdate) SetKeepAlive(v bool) *MenuUpdate {
	_u.mutation.SetKeepAlive(v)
	return _u
}

// SetNillableKeepAlive sets the "keep_alive" field if the given value is not nil.
func (_u *MenuUpdate) SetNillableKeepAlive(v *bool) *MenuUpdate {
	if v != nil {
		_u.SetKeepAlive(*v)
	}
	return _u
}

// SetSort sets the "sort" field.
func (_u *MenuUpdate) SetSort(v int) *MenuUpdate {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *MenuUpdate) SetNillableSort(v *int) *MenuUpdate {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *MenuUpdate) AddSort(v int) *MenuUpdate {
	_u.mutation.AddSort(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *MenuUpdate) SetStatus(v string) *MenuUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MenuUpdate) SetNillableStatus(v *string) *MenuUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetVisible sets the "visible" field.
func (_u *MenuUpdate) SetVisible(v bool) *MenuUpdate {
	_u.mutation.SetVisible(v)
	return _u
}

// SetNillableVisible sets the "visible" field if the given value is not nil.
func (_u *MenuUpdate) SetNillableVisible(v *bool) *MenuUpdate {
	if v != nil {
		_u.SetVisible(*v)
	}
	return _u
}

// SetFeatureKey sets the "feature_key" field.
func (_u *MenuUpdate) SetFeatureKey(v string) *MenuUpdate {
	_u.mutation.SetFeatureKey(v)
	return _u
}

// SetNillableFeatureKey sets the "feature_key" field if the given value is not nil.
func (_u *MenuUpdate) SetNillableFeatureKey(v *string) *MenuUpdate {
	if v != nil {
		_u.SetFeatureKey(*v)
	}
	return _u
}

// ClearFeatureKey clears the value of the "feature_key" field.
func (_u *MenuUpdate) ClearFeatureKey() *MenuUpdate {
	_u.mutation.ClearFeatureKey()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *MenuUpdate) SetCreatedAt(v time.Time) *MenuUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *MenuUpdate) SetNillableCreatedAt(v *time.Time) *MenuUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MenuUpdate) SetUpdatedAt(v time.Time) *MenuUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the MenuMutation object of the builder.
func (_u *MenuUpdate) Mutation() *MenuMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MenuUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MenuUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MenuUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MenuUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MenuUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := menu.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MenuUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := menu.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Menu.title": %w`, err)}
		}
	}
	return nil
}

func (_u *MenuUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(menu.Table, menu.Columns, sqlgraph.NewFieldSpec(menu.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ParentID(); ok {
		_spec.SetField(menu.FieldParentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedParentID(); ok {
		_spec.AddField(menu.FieldParentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(menu.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(menu.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(menu.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(menu.FieldPath, field.TypeString, value)
	}
	if _u.mutation.PathCleared() {
		_spec.ClearField(menu.FieldPath, field.TypeString)
	}
	if value, ok := _u.mutation.Component(); ok {
		_spec.SetField(menu.FieldComponent, field.TypeString, value)
	}
	if _u.mutation.ComponentCleared() {
		_spec.ClearField(menu.FieldComponent, field.TypeString)
	}
	if value, ok := _u.mutation.Icon(); ok {
		_spec.SetField(menu.FieldIcon, field.TypeString, value)
	}
	if _u.mutation.IconCleared() {
		_spec.ClearField(menu.FieldIcon, field.TypeString)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(menu.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Permission(); ok {
		_spec.SetField(menu.FieldPermission, field.TypeString, value)
	}
	if _u.mutation.PermissionCleared() {
		_spec.ClearField(menu.FieldPermission, field.TypeString)
	}
	if value, ok := _u.mutation.Query(); ok {
		_spec.SetField(menu.FieldQuery, field.TypeString, value)
	}
	if _u.mutation.QueryCleared() {
		_spec.ClearField(menu.FieldQuery, field.TypeString)
	}
	if value, ok := _u.mutation.IsExternal(); ok {
		_spec.SetField(menu.FieldIsExternal, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Embed(); ok {
		_spec.SetField(menu.FieldEmbed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.KeepAlive(); ok {
		_spec.SetField(menu.FieldKeepAlive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(menu.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(menu.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(menu.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Visible(); ok {
		_spec.SetField(menu.FieldVisible, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FeatureKey(); ok {
		_spec.SetField(menu.FieldFeatureKey, field.TypeString, value)
	}
	if _u.mutation.FeatureKeyCleared() {
		_spec.ClearField(menu.FieldFeatureKey, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(menu.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(menu.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{menu.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MenuUpdateOne is the builder for updating a single Menu entity.
type MenuUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MenuMutation
}

// SetParentID sets the "parent_id" field.
func (_u *MenuUpdateOne) SetParentID(v int) *MenuUpdateOne {
	_u.mutation.ResetParentID()
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *MenuUpdateOne) SetNillableParentID(v *int) *MenuUpdateOne {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// AddParentID adds value to the "parent_id" field.
func (_u *MenuUpdateOne) AddParentID(v int) *MenuUpdateOne {
	_u.mutation.AddParentID(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *MenuUpdateOne) SetTitle(v string) *MenuUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *MenuUpdateOne) SetNillableTitle(v *string) *MenuUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *MenuUpdateOne) SetName(v string) *MenuUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *MenuUpdateOne) SetNillableName(v *string) *MenuUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *MenuUpdateOne) ClearName() *MenuUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetPath sets the "path" field.
func (_u *MenuUpdateOne) SetPath(v string) *MenuUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *MenuUpdateOne) SetNillablePath(v *string) *MenuUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// ClearPath clears the value of the "path" field.
func (_u *MenuUpdateOne) ClearPath() *MenuUpdateOne {
	_u.mutation.ClearPath()
	return _u
}

// SetComponent sets the "component" field.
func (_u *MenuUpdateOne) SetComponent(v string) *MenuUpdateOne {
	_u.mutation.SetComponent(v)
	return _u
}

// SetNillableComponent sets the "component" field if the given value is not nil.
func (_u *MenuUpdateOne) SetNillableComponent(v *string) *MenuUpdateOne {
	if v != nil {
		_u.SetComponent(*v)
	}
	return _u
}

// ClearComponent clears the value of the "component" field.
func (_u *MenuUpdateOne) ClearComponent() *MenuUpdateOne {
	_u.mutation.ClearComponent()
	return _u
}

// SetIcon sets the "icon" field.
func (_u *MenuUpdateOne) SetIcon(v string) *MenuUpdateOne {
	_u.mutation.SetIcon(v)
	return _u
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_u *MenuUpdateOne) SetNillableIcon(v *string) *MenuUpdateOne {
	if v != nil {
		_u.SetIcon(*v)
	}
	return _u
}

// ClearIcon clears the value of the "icon" field.
func (_u *MenuUpdateOne) ClearIcon() *MenuUpdateOne {
	_u.mutation.ClearIcon()
	return _u
}

// SetType sets the "type" field.
func (_u *MenuUpdateOne) SetType(v string) *MenuUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *MenuUpdateOne) SetNillableType(v *string) *MenuUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetPermission sets the "permission" field.
func (_u *MenuUpdateOne) SetPermission(v string) *MenuUpdateOne {
	_u.mutation.SetPermission(v)
	return _u
}

// SetNillablePermission sets the "permission" field if the given value is not nil.
func (_u *MenuUpdateOne) SetNillablePermission(v *string) *MenuUpdateOne {
	if v != nil {
		_u.SetPermission(*v)
	}
	return _u
}

// ClearPermission clears the value of the "permission" field.
func (_u *MenuUpdateOne) ClearPermission() *MenuUpdateOne {
	_u.mutation.ClearPermission()
	return _u
}

// SetQuery sets the "query" field.
func (_u *MenuUpdateOne) SetQuery(v string) *MenuUpdateOne {
	_u.mutation.SetQuery(v)
	return _u
}

// SetNillableQuery sets the "query" field if the given value is not nil.
func (_u *MenuUpdateOne) SetNillableQuery(v *string) *MenuUpdateOne {
	if v != nil {
		_u.SetQuery(*v)
	}
	return _u
}

// ClearQuery clears the value of the "query" field.
func (_u *MenuUpdateOne) ClearQuery() *MenuUpdateOne {
	_u.mutation.ClearQuery()
	return _u
}

// SetIsExternal sets the "is_external" field.
func (_u *MenuUpdateOne) SetIsExternal(v bool) *MenuUpdateOne {
	_u.mutation.SetIsExternal(v)
	return _u
}

// SetNillableIsExternal sets the "is_external" field if the given value is not nil.
func (_u *MenuUpdateOne) SetNillableIsExternal(v *bool) *MenuUpdateOne {
	if v != nil {
		_u.SetIsExternal(*v)
	}
	return _u
}

// SetEmbed sets the "embed" field.
func (_u *MenuUpdateOne) SetEmbed(v bool) *MenuUpdateOne {
	_u.mutation.SetEmbed(v)
	return _u
}

// SetNillableEmbed sets the "embed" field if the given value is not nil.
func (_u *MenuUpdateOne) SetNillableEmbed(v *bool) *MenuUpdateOne {
	if v != nil {
		_u.SetEmbed(*v)
	}
	return _u
}

// SetKeepAlive sets the "keep_alive" field.
func (_u *MenuUpdateOne) SetKeepAlive(v bool) *MenuUpdateOne {
	_u.mutation.SetKeepAlive(v)
	return _u
}

// SetNillableKeepAlive sets the "keep_alive" field if the given value is not nil.
func (_u *MenuUpdateOne) SetNillableKeepAlive(v *bool) *MenuUpdateOne {
	if v != nil {
		_u.SetKeepAlive(*v)
	}
	return _u
}

// SetSort sets the "sort" field.
func (_u *MenuUpdateOne) SetSort(v int) *MenuUpdateOne {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *MenuUpdateOne) SetNillableSort(v *int) *MenuUpdateOne {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *MenuUpdateOne) AddSort(v int) *MenuUpdateOne {
	_u.mutation.AddSort(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *MenuUpdateOne) SetStatus(v string) *MenuUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MenuUpdateOne) SetNillableStatus(v *string) *MenuUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetVisible sets the "visible" field.
func (_u *MenuUpdateOne) SetVisible(v bool) *MenuUpdateOne {
	_u.mutation.SetVisible(v)
	return _u
}

// SetNillableVisible sets the "visible" field if the given value is not nil.
func (_u *MenuUpdateOne) SetNillableVisible(v *bool) *MenuUpdateOne {
	if v != nil {
		_u.SetVisible(*v)
	}
	return _u
}

// SetFeatureKey sets the "feature_key" field.
func (_u *MenuUpdateOne) SetFeatureKey(v string) *MenuUpdateOne {
	_u.mutation.SetFeatureKey(v)
	return _u
}

// SetNillableFeatureKey sets the "feature_key" field if the given value is not nil.
func (_u *MenuUpdateOne) SetNillableFeatureKey(v *string) *MenuUpdateOne {
	if v != nil {
		_u.SetFeatureKey(*v)
	}
	return _u
}

// ClearFeatureKey clears the value of the "feature_key" field.
func (_u *MenuUpdateOne) ClearFeatureKey() *MenuUpdateOne {
	_u.mutation.ClearFeatureKey()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *MenuUpdateOne) SetCreatedAt(v time.Time) *MenuUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *MenuUpdateOne) SetNillableCreatedAt(v *time.Time) *MenuUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MenuUpdateOne) SetUpdatedAt(v time.Time) *MenuUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the MenuMutation object of the builder.
func (_u *MenuUpdateOne) Mutation() *MenuMutation {
	return _u.mutation
}

// Where appends a list predicates to the MenuUpdate builder.
func (_u *MenuUpdateOne) Where(ps ...predicate.Menu) *MenuUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MenuUpdateOne) Select(field string, fields ...string) *MenuUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Menu entity.
func (_u *MenuUpdateOne) Save(ctx context.Context) (*Menu, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MenuUpdateOne) SaveX(ctx context.Context) *Menu {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MenuUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MenuUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MenuUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := menu.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MenuUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := menu.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Menu.title": %w`, err)}
		}
	}
	return nil
}

func (_u *MenuUpdateOne) sqlSave(ctx context.Context) (_node *Menu, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(menu.Table, menu.Columns, sqlgraph.NewFieldSpec(menu.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Menu.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, menu.FieldID)
		for _, f := range fields {
			if !menu.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != menu.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ParentID(); ok {
		_spec.SetField(menu.FieldParentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedParentID(); ok {
		_spec.AddField(menu.FieldParentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(menu.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(menu.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(menu.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(menu.FieldPath, field.TypeString, value)
	}
	if _u.mutation.PathCleared() {
		_spec.ClearField(menu.FieldPath, field.TypeString)
	}
	if value, ok := _u.mutation.Component(); ok {
		_spec.SetField(menu.FieldComponent, field.TypeString, value)
	}
	if _u.mutation.ComponentCleared() {
		_spec.ClearField(menu.FieldComponent, field.TypeString)
	}
	if value, ok := _u.mutation.Icon(); ok {
		_spec.SetField(menu.FieldIcon, field.TypeString, value)
	}
	if _u.mutation.IconCleared() {
		_spec.ClearField(menu.FieldIcon, field.TypeString)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(menu.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Permission(); ok {
		_spec.SetField(menu.FieldPermission, field.TypeString, value)
	}
	if _u.mutation.PermissionCleared() {
		_spec.ClearField(menu.FieldPermission, field.TypeString)
	}
	if value, ok := _u.mutation.Query(); ok {
		_spec.SetField(menu.FieldQuery, field.TypeString, value)
	}
	if _u.mutation.QueryCleared() {
		_spec.ClearField(menu.FieldQuery, field.TypeString)
	}
	if value, ok := _u.mutation.IsExternal(); ok {
		_spec.SetField(menu.FieldIsExternal, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Embed(); ok {
		_spec.SetField(menu.FieldEmbed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.KeepAlive(); ok {
		_spec.SetField(menu.FieldKeepAlive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(menu.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(menu.FieldSort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(menu.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Visible(); ok {
		_spec.SetField(menu.FieldVisible, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FeatureKey(); ok {
		_spec.SetField(menu.FieldFeatureKey, field.TypeString, value)
	}
	if _u.mutation.FeatureKeyCleared() {
		_spec.ClearField(menu.FieldFeatureKey, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(menu.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(menu.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Menu{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{menu.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
