// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fudanda/arcbase/backend/ent/session"
)

// SessionCreate is the builder for creating a Session entity.
type SessionCreate struct {
	config
	mutation *SessionMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *SessionCreate) SetUserID(v int) *SessionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetTokenHash sets the "token_hash" field.
func (_c *SessionCreate) SetTokenHash(v string) *SessionCreate {
	_c.mutation.SetTokenHash(v)
	return _c
}

// SetCsrfHash sets the "csrf_hash" field.
func (_c *SessionCreate) SetCsrfHash(v string) *SessionCreate {
	_c.mutation.SetCsrfHash(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *SessionCreate) SetExpiresAt(v time.Time) *SessionCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *SessionCreate) SetRevokedAt(v time.Time) *SessionCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *SessionCreate) SetNillableRevokedAt(v *time.Time) *SessionCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// SetIP sets the "ip" field.
func (_c *SessionCreate) SetIP(v string) *SessionCreate {
	_c.mutation.SetIP(v)
	return _c
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_c *SessionCreate) SetNillableIP(v *string) *SessionCreate {
	if v != nil {
		_c.SetIP(*v)
	}
	return _c
}

// SetClient sets the "client" field.
func (_c *SessionCreate) SetClient(v string) *SessionCreate {
	_c.mutation.SetClient(v)
	return _c
}

// SetNillableClient sets the "client" field if the given value is not nil.
func (_c *SessionCreate) SetNillableClient(v *string) *SessionCreate {
	if v != nil {
		_c.SetClient(*v)
	}
	return _c
}

// SetBrowser sets the "browser" field.
func (_c *SessionCreate) SetBrowser(v string) *SessionCreate {
	_c.mutation.SetBrowser(v)
	return _c
}

// SetNillableBrowser sets the "browser" field if the given value is not nil.
func (_c *SessionCreate) SetNillableBrowser(v *string) *SessionCreate {
	if v != nil {
		_c.SetBrowser(*v)
	}
	return _c
}

// SetOs sets the "os" field.
func (_c *SessionCreate) SetOs(v string) *SessionCreate {
	_c.mutation.SetOs(v)
	return _c
}

// SetNillableOs sets the "os" field if the given value is not nil.
func (_c *SessionCreate) SetNillableOs(v *string) *SessionCreate {
	if v != nil {
		_c.SetOs(*v)
	}
	return _c
}

// SetLastActiveAt sets the "last_active_at" field.
func (_c *SessionCreate) SetLastActiveAt(v time.Time) *SessionCreate {
	_c.mutation.SetLastActiveAt(v)
	return _c
}

// SetNillableLastActiveAt sets the "last_active_at" field if the given value is not nil.
func (_c *SessionCreate) SetNillableLastActiveAt(v *time.Time) *SessionCreate {
	if v != nil {
		_c.SetLastActiveAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SessionCreate) SetCreatedAt(v time.Time) *SessionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SessionCreate) SetNillableCreatedAt(v *time.Time) *SessionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the SessionMutation object of the builder.
func (_c *SessionCreate) Mutation() *SessionMutation {
	return _c.mutation
}

// Save creates the Session in the database.
func (_c *SessionCreate) Save(ctx context.Context) (*Session, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SessionCreate) SaveX(ctx context.Context) *Session {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SessionCreate) defaults() {
	if _, ok := _c.mutation.IP(); !ok {
		v := session.DefaultIP
		_c.mutation.SetIP(v)
	}
	if _, ok := _c.mutation.GetClient(); !ok {
		v := session.DefaultClient
		_c.mutation.SetClient(v)
	}
	if _, ok := _c.mutation.Browser(); !ok {
		v := session.DefaultBrowser
		_c.mutation.SetBrowser(v)
	}
	if _, ok := _c.mutation.Os(); !ok {
		v := session.DefaultOs
		_c.mutation.SetOs(v)
	}
	if _, ok := _c.mutation.LastActiveAt(); !ok {
		v := session.DefaultLastActiveAt()
		_c.mutation.SetLastActiveAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := session.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SessionCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Session.user_id"`)}
	}
	if _, ok := _c.mutation.TokenHash(); !ok {
		return &ValidationError{Name: "token_hash", err: errors.New(`ent: missing required field "Session.token_hash"`)}
	}
	if _, ok := _c.mutation.CsrfHash(); !ok {
		return &ValidationError{Name: "csrf_hash", err: errors.New(`ent: missing required field "Session.csrf_hash"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "Session.expires_at"`)}
	}
	if _, ok := _c.mutation.IP(); !ok {
		return &ValidationError{Name: "ip", err: errors.New(`ent: missing required field "Session.ip"`)}
	}
	if _, ok := _c.mutation.GetClient(); !ok {
		return &ValidationError{Name: "client", err: errors.New(`ent: missing required field "Session.client"`)}
	}
	if _, ok := _c.mutation.Browser(); !ok {
		return &ValidationError{Name: "browser", err: errors.New(`ent: missing required field "Session.browser"`)}
	}
	if _, ok := _c.mutation.Os(); !ok {
		return &ValidationError{Name: "os", err: errors.New(`ent: missing required field "Session.os"`)}
	}
	if _, ok := _c.mutation.LastActiveAt(); !ok {
		return &ValidationError{Name: "last_active_at", err: errors.New(`ent: missing required field "Session.last_active_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Session.created_at"`)}
	}
	return nil
}

func (_c *SessionCreate) sqlSave(ctx context.Context) (*Session, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SessionCreate) createSpec() (*Session, *sqlgraph.CreateSpec) {
	var (
		_node = &Session{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(session.Table, sqlgraph.NewFieldSpec(session.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(session.FieldUserID, field.TypeInt, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.TokenHash(); ok {
		_spec.SetField(session.FieldTokenHash, field.TypeString, value)
		_node.TokenHash = value
	}
	if value, ok := _c.mutation.CsrfHash(); ok {
		_spec.SetField(session.FieldCsrfHash, field.TypeString, value)
		_node.CsrfHash = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(session.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(session.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	if value, ok := _c.mutation.IP(); ok {
		_spec.SetField(session.FieldIP, field.TypeString, value)
		_node.IP = value
	}
	if value, ok := _c.mutation.GetClient(); ok {
		_spec.SetField(session.FieldClient, field.TypeString, value)
		_node.Client = value
	}
	if value, ok := _c.mutation.Browser(); ok {
		_spec.SetField(session.FieldBrowser, field.TypeString, value)
		_node.Browser = value
	}
	if value, ok := _c.mutation.Os(); ok {
		_spec.SetField(session.FieldOs, field.TypeString, value)
		_node.Os = value
	}
	if value, ok := _c.mutation.LastActiveAt(); ok {
		_spec.SetField(session.FieldLastActiveAt, field.TypeTime, value)
		_node.LastActiveAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(session.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// SessionCreateBulk is the builder for creating many Session entities in bulk.
type SessionCreateBulk struct {
	config
	err      error
	builders []*SessionCreate
}

// Save creates the Session entities in the database.
func (_c *SessionCreateBulk) Save(ctx context.Context) ([]*Session, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Session, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SessionCreateBulk) SaveX(ctx context.Context) []*Session {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
