// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fudanda/zenith-admin/backend/ent/tenantpackage"
)

// TenantPackageCreate is the builder for creating a TenantPackage entity.
type TenantPackageCreate struct {
	config
	mutation *TenantPackageMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *TenantPackageCreate) SetName(v string) *TenantPackageCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *TenantPackageCreate) SetStatus(v string) *TenantPackageCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *TenantPackageCreate) SetNillableStatus(v *string) *TenantPackageCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetQuotas sets the "quotas" field.
func (_c *TenantPackageCreate) SetQuotas(v map[string]interface{}) *TenantPackageCreate {
	_c.mutation.SetQuotas(v)
	return _c
}

// SetRemark sets the "remark" field.
func (_c *TenantPackageCreate) SetRemark(v string) *TenantPackageCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *TenantPackageCreate) SetNillableRemark(v *string) *TenantPackageCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TenantPackageCreate) SetCreatedAt(v time.Time) *TenantPackageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TenantPackageCreate) SetNillableCreatedAt(v *time.Time) *TenantPackageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TenantPackageCreate) SetUpdatedAt(v time.Time) *TenantPackageCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TenantPackageCreate) SetNillableUpdatedAt(v *time.Time) *TenantPackageCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the TenantPackageMutation object of the builder.
func (_c *TenantPackageCreate) Mutation() *TenantPackageMutation {
	return _c.mutation
}

// Save creates the TenantPackage in the database.
func (_c *TenantPackageCreate) Save(ctx context.Context) (*TenantPackage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TenantPackageCreate) SaveX(ctx context.Context) *TenantPackage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TenantPackageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TenantPackageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TenantPackageCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := tenantpackage.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := tenantpackage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := tenantpackage.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TenantPackageCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "TenantPackage.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := tenantpackage.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "TenantPackage.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "TenantPackage.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TenantPackage.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TenantPackage.updated_at"`)}
	}
	return nil
}

func (_c *TenantPackageCreate) sqlSave(ctx context.Context) (*TenantPackage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TenantPackageCreate) createSpec() (*TenantPackage, *sqlgraph.CreateSpec) {
	var (
		_node = &TenantPackage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tenantpackage.Table, sqlgraph.NewFieldSpec(tenantpackage.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(tenantpackage.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(tenantpackage.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Quotas(); ok {
		_spec.SetField(tenantpackage.FieldQuotas, field.TypeJSON, value)
		_node.Quotas = value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(tenantpackage.FieldRemark, field.TypeString, value)
		_node.Remark = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(tenantpackage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(tenantpackage.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// TenantPackageCreateBulk is the builder for creating many TenantPackage entities in bulk.
type TenantPackageCreateBulk struct {
	config
	err      error
	builders []*TenantPackageCreate
}

// Save creates the TenantPackage entities in the database.
func (_c *TenantPackageCreateBulk) Save(ctx context.Context) ([]*TenantPackage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TenantPackage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TenantPackageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TenantPackageCreateBulk) SaveX(ctx context.Context) []*TenantPackage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TenantPackageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TenantPackageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
