// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fudanda/zenith-admin/backend/ent/predicate"
	"github.com/fudanda/zenith-admin/backend/ent/uploadsession"
)

// UploadSessionUpdate is the builder for updating UploadSession entities.
type UploadSessionUpdate struct {
	config
	hooks    []Hook
	mutation *UploadSessionMutation
}

// Where appends a list predicates to the UploadSessionUpdate builder.
func (_u *UploadSessionUpdate) Where(ps ...predicate.UploadSession) *UploadSessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStorageConfigID sets the "storage_config_id" field.
func (_u *UploadSessionUpdate) SetStorageConfigID(v int) *UploadSessionUpdate {
	_u.mutation.ResetStorageConfigID()
	_u.mutation.SetStorageConfigID(v)
	return _u
}

// SetNillableStorageConfigID sets the "storage_config_id" field if the given value is not nil.
func (_u *UploadSessionUpdate) SetNillableStorageConfigID(v *int) *UploadSessionUpdate {
	if v != nil {
		_u.SetStorageConfigID(*v)
	}
	return _u
}

// AddStorageConfigID adds value to the "storage_config_id" field.
func (_u *UploadSessionUpdate) AddStorageConfigID(v int) *UploadSessionUpdate {
	_u.mutation.AddStorageConfigID(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *UploadSessionUpdate) SetTenantID(v int) *UploadSessionUpdate {
	_u.mutation.ResetTenantID()
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *UploadSessionUpdate) SetNillableTenantID(v *int) *UploadSessionUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// AddTenantID adds value to the "tenant_id" field.
func (_u *UploadSessionUpdate) AddTenantID(v int) *UploadSessionUpdate {
	_u.mutation.AddTenantID(v)
	return _u
}

// ClearTenantID clears the value of the "tenant_id" field.
func (_u *UploadSessionUpdate) ClearTenantID() *UploadSessionUpdate {
	_u.mutation.ClearTenantID()
	return _u
}

// SetUploaderID sets the "uploader_id" field.
func (_u *UploadSessionUpdate) SetUploaderID(v int) *UploadSessionUpdate {
	_u.mutation.ResetUploaderID()
	_u.mutation.SetUploaderID(v)
	return _u
}

// SetNillableUploaderID sets the "uploader_id" field if the given value is not nil.
func (_u *UploadSessionUpdate) SetNillableUploaderID(v *int) *UploadSessionUpdate {
	if v != nil {
		_u.SetUploaderID(*v)
	}
	return _u
}

// AddUploaderID adds value to the "uploader_id" field.
func (_u *UploadSessionUpdate) AddUploaderID(v int) *UploadSessionUpdate {
	_u.mutation.AddUploaderID(v)
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *UploadSessionUpdate) SetFileName(v string) *UploadSessionUpdate {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *UploadSessionUpdate) SetNillableFileName(v *string) *UploadSessionUpdate {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *UploadSessionUpdate) SetFileSize(v int64) *UploadSessionUpdate {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *UploadSessionUpdate) SetNillableFileSize(v *int64) *UploadSessionUpdate {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *UploadSessionUpdate) AddFileSize(v int64) *UploadSessionUpdate {
	_u.mutation.AddFileSize(v)
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *UploadSessionUpdate) SetMimeType(v string) *UploadSessionUpdate {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *UploadSessionUpdate) SetNillableMimeType(v *string) *UploadSessionUpdate {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// ClearMimeType clears the value of the "mime_type" field.
func (_u *UploadSessionUpdate) ClearMimeType() *UploadSessionUpdate {
	_u.mutation.ClearMimeType()
	return _u
}

// SetChunkSize sets the "chunk_size" field.
func (_u *UploadSessionUpdate) SetChunkSize(v int64) *UploadSessionUpdate {
	_u.mutation.ResetChunkSize()
	_u.mutation.SetChunkSize(v)
	return _u
}

// SetNillableChunkSize sets the "chunk_size" field if the given value is not nil.
func (_u *UploadSessionUpdate) SetNillableChunkSize(v *int64) *UploadSessionUpdate {
	if v != nil {
		_u.SetChunkSize(*v)
	}
	return _u
}

// AddChunkSize adds value to the "chunk_size" field.
func (_u *UploadSessionUpdate) AddChunkSize(v int64) *UploadSessionUpdate {
	_u.mutation.AddChunkSize(v)
	return _u
}

// SetTotalChunks sets the "total_chunks" field.
func (_u *UploadSessionUpdate) SetTotalChunks(v int) *UploadSessionUpdate {
	_u.mutation.ResetTotalChunks()
	_u.mutation.SetTotalChunks(v)
	return _u
}

// SetNillableTotalChunks sets the "total_chunks" field if the given value is not nil.
func (_u *UploadSessionUpdate) SetNillableTotalChunks(v *int) *UploadSessionUpdate {
	if v != nil {
		_u.SetTotalChunks(*v)
	}
	return _u
}

// AddTotalChunks adds value to the "total_chunks" field.
func (_u *UploadSessionUpdate) AddTotalChunks(v int) *UploadSessionUpdate {
	_u.mutation.AddTotalChunks(v)
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *UploadSessionUpdate) SetVisibility(v string) *UploadSessionUpdate {
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *UploadSessionUpdate) SetNillableVisibility(v *string) *UploadSessionUpdate {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *UploadSessionUpdate) SetStatus(v string) *UploadSessionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UploadSessionUpdate) SetNillableStatus(v *string) *UploadSessionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UploadSessionUpdate) SetExpiresAt(v time.Time) *UploadSessionUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UploadSessionUpdate) SetNillableExpiresAt(v *time.Time) *UploadSessionUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UploadSessionUpdate) SetCreatedAt(v time.Time) *UploadSessionUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UploadSessionUpdate) SetNillableCreatedAt(v *time.Time) *UploadSessionUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UploadSessionUpdate) SetUpdatedAt(v time.Time) *UploadSessionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UploadSessionMutation object of the builder.
func (_u *UploadSessionUpdate) Mutation() *UploadSessionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UploadSessionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UploadSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UploadSessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UploadSessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UploadSessionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := uploadsession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UploadSessionUpdate) check() error {
	if v, ok := _u.mutation.FileName(); ok {
		if err := uploadsession.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "UploadSession.file_name": %w`, err)}
		}
	}
	return nil
}

func (_u *UploadSessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(uploadsession.Table, uploadsession.Columns, sqlgraph.NewFieldSpec(uploadsession.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.StorageConfigID(); ok {
		_spec.SetField(uploadsession.FieldStorageConfigID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStorageConfigID(); ok {
		_spec.AddField(uploadsession.FieldStorageConfigID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(uploadsession.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTenantID(); ok {
		_spec.AddField(uploadsession.FieldTenantID, field.TypeInt, value)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(uploadsession.FieldTenantID, field.TypeInt)
	}
	if value, ok := _u.mutation.UploaderID(); ok {
		_spec.SetField(uploadsession.FieldUploaderID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUploaderID(); ok {
		_spec.AddField(uploadsession.FieldUploaderID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(uploadsession.FieldFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(uploadsession.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(uploadsession.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(uploadsession.FieldMimeType, field.TypeString, value)
	}
	if _u.mutation.MimeTypeCleared() {
		_spec.ClearField(uploadsession.FieldMimeType, field.TypeString)
	}
	if value, ok := _u.mutation.ChunkSize(); ok {
		_spec.SetField(uploadsession.FieldChunkSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChunkSize(); ok {
		_spec.AddField(uploadsession.FieldChunkSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalChunks(); ok {
		_spec.SetField(uploadsession.FieldTotalChunks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalChunks(); ok {
		_spec.AddField(uploadsession.FieldTotalChunks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(uploadsession.FieldVisibility, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(uploadsession.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(uploadsession.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(uploadsession.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(uploadsession.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{uploadsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UploadSessionUpdateOne is the builder for updating a single UploadSession entity.
type UploadSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UploadSessionMutation
}

// SetStorageConfigID sets the "storage_config_id" field.
func (_u *UploadSessionUpdateOne) SetStorageConfigID(v int) *UploadSessionUpdateOne {
	_u.mutation.ResetStorageConfigID()
	_u.mutation.SetStorageConfigID(v)
	return _u
}

// SetNillableStorageConfigID sets the "storage_config_id" field if the given value is not nil.
func (_u *UploadSessionUpdateOne) SetNillableStorageConfigID(v *int) *UploadSessionUpdateOne {
	if v != nil {
		_u.SetStorageConfigID(*v)
	}
	return _u
}

// AddStorageConfigID adds value to the "storage_config_id" field.
func (_u *UploadSessionUpdateOne) AddStorageConfigID(v int) *UploadSessionUpdateOne {
	_u.mutation.AddStorageConfigID(v)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *UploadSessionUpdateOne) SetTenantID(v int) *UploadSessionUpdateOne {
	_u.mutation.ResetTenantID()
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *UploadSessionUpdateOne) SetNillableTenantID(v *int) *UploadSessionUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// AddTenantID adds value to the "tenant_id" field.
func (_u *UploadSessionUpdateOne) AddTenantID(v int) *UploadSessionUpdateOne {
	_u.mutation.AddTenantID(v)
	return _u
}

// ClearTenantID clears the value of the "tenant_id" field.
func (_u *UploadSessionUpdateOne) ClearTenantID() *UploadSessionUpdateOne {
	_u.mutation.ClearTenantID()
	return _u
}

// SetUploaderID sets the "uploader_id" field.
func (_u *UploadSessionUpdateOne) SetUploaderID(v int) *UploadSessionUpdateOne {
	_u.mutation.ResetUploaderID()
	_u.mutation.SetUploaderID(v)
	return _u
}

// SetNillableUploaderID sets the "uploader_id" field if the given value is not nil.
func (_u *UploadSessionUpdateOne) SetNillableUploaderID(v *int) *UploadSessionUpdateOne {
	if v != nil {
		_u.SetUploaderID(*v)
	}
	return _u
}

// AddUploaderID adds value to the "uploader_id" field.
func (_u *UploadSessionUpdateOne) AddUploaderID(v int) *UploadSessionUpdateOne {
	_u.mutation.AddUploaderID(v)
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *UploadSessionUpdateOne) SetFileName(v string) *UploadSessionUpdateOne {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *UploadSessionUpdateOne) SetNillableFileName(v *string) *UploadSessionUpdateOne {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *UploadSessionUpdateOne) SetFileSize(v int64) *UploadSessionUpdateOne {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *UploadSessionUpdateOne) SetNillableFileSize(v *int64) *UploadSessionUpdateOne {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *UploadSessionUpdateOne) AddFileSize(v int64) *UploadSessionUpdateOne {
	_u.mutation.AddFileSize(v)
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *UploadSessionUpdateOne) SetMimeType(v string) *UploadSessionUpdateOne {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *UploadSessionUpdateOne) SetNillableMimeType(v *string) *UploadSessionUpdateOne {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// ClearMimeType clears the value of the "mime_type" field.
func (_u *UploadSessionUpdateOne) ClearMimeType() *UploadSessionUpdateOne {
	_u.mutation.ClearMimeType()
	return _u
}

// SetChunkSize sets the "chunk_size" field.
func (_u *UploadSessionUpdateOne) SetChunkSize(v int64) *UploadSessionUpdateOne {
	_u.mutation.ResetChunkSize()
	_u.mutation.SetChunkSize(v)
	return _u
}

// SetNillableChunkSize sets the "chunk_size" field if the given value is not nil.
func (_u *UploadSessionUpdateOne) SetNillableChunkSize(v *int64) *UploadSessionUpdateOne {
	if v != nil {
		_u.SetChunkSize(*v)
	}
	return _u
}

// AddChunkSize adds value to the "chunk_size" field.
func (_u *UploadSessionUpdateOne) AddChunkSize(v int64) *UploadSessionUpdateOne {
	_u.mutation.AddChunkSize(v)
	return _u
}

// SetTotalChunks sets the "total_chunks" field.
func (_u *UploadSessionUpdateOne) SetTotalChunks(v int) *UploadSessionUpdateOne {
	_u.mutation.ResetTotalChunks()
	_u.mutation.SetTotalChunks(v)
	return _u
}

// SetNillableTotalChunks sets the "total_chunks" field if the given value is not nil.
func (_u *UploadSessionUpdateOne) SetNillableTotalChunks(v *int) *UploadSessionUpdateOne {
	if v != nil {
		_u.SetTotalChunks(*v)
	}
	return _u
}

// AddTotalChunks adds value to the "total_chunks" field.
func (_u *UploadSessionUpdateOne) AddTotalChunks(v int) *UploadSessionUpdateOne {
	_u.mutation.AddTotalChunks(v)
	return _u
}

// SetVisibility sets the "visibility" field.
func (_u *UploadSessionUpdateOne) SetVisibility(v string) *UploadSessionUpdateOne {
	_u.mutation.SetVisibility(v)
	return _u
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (_u *UploadSessionUpdateOne) SetNillableVisibility(v *string) *UploadSessionUpdateOne {
	if v != nil {
		_u.SetVisibility(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *UploadSessionUpdateOne) SetStatus(v string) *UploadSessionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UploadSessionUpdateOne) SetNillableStatus(v *string) *UploadSessionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *UploadSessionUpdateOne) SetExpiresAt(v time.Time) *UploadSessionUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *UploadSessionUpdateOne) SetNillableExpiresAt(v *time.Time) *UploadSessionUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UploadSessionUpdateOne) SetCreatedAt(v time.Time) *UploadSessionUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UploadSessionUpdateOne) SetNillableCreatedAt(v *time.Time) *UploadSessionUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UploadSessionUpdateOne) SetUpdatedAt(v time.Time) *UploadSessionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UploadSessionMutation object of the builder.
func (_u *UploadSessionUpdateOne) Mutation() *UploadSessionMutation {
	return _u.mutation
}

// Where appends a list predicates to the UploadSessionUpdate builder.
func (_u *UploadSessionUpdateOne) Where(ps ...predicate.UploadSession) *UploadSessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UploadSessionUpdateOne) Select(field string, fields ...string) *UploadSessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UploadSession entity.
func (_u *UploadSessionUpdateOne) Save(ctx context.Context) (*UploadSession, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UploadSessionUpdateOne) SaveX(ctx context.Context) *UploadSession {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UploadSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UploadSessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UploadSessionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := uploadsession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UploadSessionUpdateOne) check() error {
	if v, ok := _u.mutation.FileName(); ok {
		if err := uploadsession.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`ent: validator failed for field "UploadSession.file_name": %w`, err)}
		}
	}
	return nil
}

func (_u *UploadSessionUpdateOne) sqlSave(ctx context.Context) (_node *UploadSession, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(uploadsession.Table, uploadsession.Columns, sqlgraph.NewFieldSpec(uploadsession.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UploadSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, uploadsession.FieldID)
		for _, f := range fields {
			if !uploadsession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != uploadsession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.StorageConfigID(); ok {
		_spec.SetField(uploadsession.FieldStorageConfigID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStorageConfigID(); ok {
		_spec.AddField(uploadsession.FieldStorageConfigID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(uploadsession.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTenantID(); ok {
		_spec.AddField(uploadsession.FieldTenantID, field.TypeInt, value)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(uploadsession.FieldTenantID, field.TypeInt)
	}
	if value, ok := _u.mutation.UploaderID(); ok {
		_spec.SetField(uploadsession.FieldUploaderID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUploaderID(); ok {
		_spec.AddField(uploadsession.FieldUploaderID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(uploadsession.FieldFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(uploadsession.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(uploadsession.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(uploadsession.FieldMimeType, field.TypeString, value)
	}
	if _u.mutation.MimeTypeCleared() {
		_spec.ClearField(uploadsession.FieldMimeType, field.TypeString)
	}
	if value, ok := _u.mutation.ChunkSize(); ok {
		_spec.SetField(uploadsession.FieldChunkSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChunkSize(); ok {
		_spec.AddField(uploadsession.FieldChunkSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.TotalChunks(); ok {
		_spec.SetField(uploadsession.FieldTotalChunks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalChunks(); ok {
		_spec.AddField(uploadsession.FieldTotalChunks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Visibility(); ok {
		_spec.SetField(uploadsession.FieldVisibility, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(uploadsession.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(uploadsession.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(uploadsession.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(uploadsession.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &UploadSession{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{uploadsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
