// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/fudanda/arcbase/backend/ent/uploadchunk"
)

// UploadChunkCreate is the builder for creating a UploadChunk entity.
type UploadChunkCreate struct {
	config
	mutation *UploadChunkMutation
	hooks    []Hook
}

// SetUploadID sets the "upload_id" field.
func (_c *UploadChunkCreate) SetUploadID(v string) *UploadChunkCreate {
	_c.mutation.SetUploadID(v)
	return _c
}

// SetChunkIndex sets the "chunk_index" field.
func (_c *UploadChunkCreate) SetChunkIndex(v int) *UploadChunkCreate {
	_c.mutation.SetChunkIndex(v)
	return _c
}

// SetSize sets the "size" field.
func (_c *UploadChunkCreate) SetSize(v int64) *UploadChunkCreate {
	_c.mutation.SetSize(v)
	return _c
}

// SetHash sets the "hash" field.
func (_c *UploadChunkCreate) SetHash(v string) *UploadChunkCreate {
	_c.mutation.SetHash(v)
	return _c
}

// Mutation returns the UploadChunkMutation object of the builder.
func (_c *UploadChunkCreate) Mutation() *UploadChunkMutation {
	return _c.mutation
}

// Save creates the UploadChunk in the database.
func (_c *UploadChunkCreate) Save(ctx context.Context) (*UploadChunk, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UploadChunkCreate) SaveX(ctx context.Context) *UploadChunk {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UploadChunkCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UploadChunkCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UploadChunkCreate) check() error {
	if _, ok := _c.mutation.UploadID(); !ok {
		return &ValidationError{Name: "upload_id", err: errors.New(`ent: missing required field "UploadChunk.upload_id"`)}
	}
	if v, ok := _c.mutation.UploadID(); ok {
		if err := uploadchunk.UploadIDValidator(v); err != nil {
			return &ValidationError{Name: "upload_id", err: fmt.Errorf(`ent: validator failed for field "UploadChunk.upload_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ChunkIndex(); !ok {
		return &ValidationError{Name: "chunk_index", err: errors.New(`ent: missing required field "UploadChunk.chunk_index"`)}
	}
	if _, ok := _c.mutation.Size(); !ok {
		return &ValidationError{Name: "size", err: errors.New(`ent: missing required field "UploadChunk.size"`)}
	}
	if _, ok := _c.mutation.Hash(); !ok {
		return &ValidationError{Name: "hash", err: errors.New(`ent: missing required field "UploadChunk.hash"`)}
	}
	return nil
}

func (_c *UploadChunkCreate) sqlSave(ctx context.Context) (*UploadChunk, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UploadChunkCreate) createSpec() (*UploadChunk, *sqlgraph.CreateSpec) {
	var (
		_node = &UploadChunk{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(uploadchunk.Table, sqlgraph.NewFieldSpec(uploadchunk.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.UploadID(); ok {
		_spec.SetField(uploadchunk.FieldUploadID, field.TypeString, value)
		_node.UploadID = value
	}
	if value, ok := _c.mutation.ChunkIndex(); ok {
		_spec.SetField(uploadchunk.FieldChunkIndex, field.TypeInt, value)
		_node.ChunkIndex = value
	}
	if value, ok := _c.mutation.Size(); ok {
		_spec.SetField(uploadchunk.FieldSize, field.TypeInt64, value)
		_node.Size = value
	}
	if value, ok := _c.mutation.Hash(); ok {
		_spec.SetField(uploadchunk.FieldHash, field.TypeString, value)
		_node.Hash = value
	}
	return _node, _spec
}

// UploadChunkCreateBulk is the builder for creating many UploadChunk entities in bulk.
type UploadChunkCreateBulk struct {
	config
	err      error
	builders []*UploadChunkCreate
}

// Save creates the UploadChunk entities in the database.
func (_c *UploadChunkCreateBulk) Save(ctx context.Context) ([]*UploadChunk, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UploadChunk, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UploadChunkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UploadChunkCreateBulk) SaveX(ctx context.Context) []*UploadChunk {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UploadChunkCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UploadChunkCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
