// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/fudanda/zenith-admin/backend/ent/predicate"
	"github.com/fudanda/zenith-admin/backend/ent/user"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUsername sets the "username" field.
func (_u *UserUpdate) SetUsername(v string) *UserUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *UserUpdate) SetNillableUsername(v *string) *UserUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetNickname sets the "nickname" field.
func (_u *UserUpdate) SetNickname(v string) *UserUpdate {
	_u.mutation.SetNickname(v)
	return _u
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (_u *UserUpdate) SetNillableNickname(v *string) *UserUpdate {
	if v != nil {
		_u.SetNickname(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *UserUpdate) SetPasswordHash(v string) *UserUpdate {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePasswordHash(v *string) *UserUpdate {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserUpdate) SetStatus(v string) *UserUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserUpdate) SetNillableStatus(v *string) *UserUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAvatar sets the "avatar" field.
func (_u *UserUpdate) SetAvatar(v string) *UserUpdate {
	_u.mutation.SetAvatar(v)
	return _u
}

// SetNillableAvatar sets the "avatar" field if the given value is not nil.
func (_u *UserUpdate) SetNillableAvatar(v *string) *UserUpdate {
	if v != nil {
		_u.SetAvatar(*v)
	}
	return _u
}

// ClearAvatar clears the value of the "avatar" field.
func (_u *UserUpdate) ClearAvatar() *UserUpdate {
	_u.mutation.ClearAvatar()
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdate) SetEmail(v string) *UserUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdate) SetNillableEmail(v *string) *UserUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *UserUpdate) ClearEmail() *UserUpdate {
	_u.mutation.ClearEmail()
	return _u
}

// SetPhone sets the "phone" field.
func (_u *UserUpdate) SetPhone(v string) *UserUpdate {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePhone(v *string) *UserUpdate {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "phone" field.
func (_u *UserUpdate) ClearPhone() *UserUpdate {
	_u.mutation.ClearPhone()
	return _u
}

// SetGender sets the "gender" field.
func (_u *UserUpdate) SetGender(v string) *UserUpdate {
	_u.mutation.SetGender(v)
	return _u
}

// SetNillableGender sets the "gender" field if the given value is not nil.
func (_u *UserUpdate) SetNillableGender(v *string) *UserUpdate {
	if v != nil {
		_u.SetGender(*v)
	}
	return _u
}

// ClearGender clears the value of the "gender" field.
func (_u *UserUpdate) ClearGender() *UserUpdate {
	_u.mutation.ClearGender()
	return _u
}

// SetBirthDate sets the "birth_date" field.
func (_u *UserUpdate) SetBirthDate(v string) *UserUpdate {
	_u.mutation.SetBirthDate(v)
	return _u
}

// SetNillableBirthDate sets the "birth_date" field if the given value is not nil.
func (_u *UserUpdate) SetNillableBirthDate(v *string) *UserUpdate {
	if v != nil {
		_u.SetBirthDate(*v)
	}
	return _u
}

// ClearBirthDate clears the value of the "birth_date" field.
func (_u *UserUpdate) ClearBirthDate() *UserUpdate {
	_u.mutation.ClearBirthDate()
	return _u
}

// SetDepartmentID sets the "department_id" field.
func (_u *UserUpdate) SetDepartmentID(v int) *UserUpdate {
	_u.mutation.ResetDepartmentID()
	_u.mutation.SetDepartmentID(v)
	return _u
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_u *UserUpdate) SetNillableDepartmentID(v *int) *UserUpdate {
	if v != nil {
		_u.SetDepartmentID(*v)
	}
	return _u
}

// AddDepartmentID adds value to the "department_id" field.
func (_u *UserUpdate) AddDepartmentID(v int) *UserUpdate {
	_u.mutation.AddDepartmentID(v)
	return _u
}

// ClearDepartmentID clears the value of the "department_id" field.
func (_u *UserUpdate) ClearDepartmentID() *UserUpdate {
	_u.mutation.ClearDepartmentID()
	return _u
}

// SetPreferences sets the "preferences" field.
func (_u *UserUpdate) SetPreferences(v map[string]interface{}) *UserUpdate {
	_u.mutation.SetPreferences(v)
	return _u
}

// ClearPreferences clears the value of the "preferences" field.
func (_u *UserUpdate) ClearPreferences() *UserUpdate {
	_u.mutation.ClearPreferences()
	return _u
}

// SetFavoriteMenus sets the "favorite_menus" field.
func (_u *UserUpdate) SetFavoriteMenus(v []int) *UserUpdate {
	_u.mutation.SetFavoriteMenus(v)
	return _u
}

// AppendFavoriteMenus appends value to the "favorite_menus" field.
func (_u *UserUpdate) AppendFavoriteMenus(v []int) *UserUpdate {
	_u.mutation.AppendFavoriteMenus(v)
	return _u
}

// ClearFavoriteMenus clears the value of the "favorite_menus" field.
func (_u *UserUpdate) ClearFavoriteMenus() *UserUpdate {
	_u.mutation.ClearFavoriteMenus()
	return _u
}

// SetUserDataScope sets the "user_data_scope" field.
func (_u *UserUpdate) SetUserDataScope(v string) *UserUpdate {
	_u.mutation.SetUserDataScope(v)
	return _u
}

// SetNillableUserDataScope sets the "user_data_scope" field if the given value is not nil.
func (_u *UserUpdate) SetNillableUserDataScope(v *string) *UserUpdate {
	if v != nil {
		_u.SetUserDataScope(*v)
	}
	return _u
}

// ClearUserDataScope clears the value of the "user_data_scope" field.
func (_u *UserUpdate) ClearUserDataScope() *UserUpdate {
	_u.mutation.ClearUserDataScope()
	return _u
}

// SetPasswordUpdatedAt sets the "password_updated_at" field.
func (_u *UserUpdate) SetPasswordUpdatedAt(v time.Time) *UserUpdate {
	_u.mutation.SetPasswordUpdatedAt(v)
	return _u
}

// SetNillablePasswordUpdatedAt sets the "password_updated_at" field if the given value is not nil.
func (_u *UserUpdate) SetNillablePasswordUpdatedAt(v *time.Time) *UserUpdate {
	if v != nil {
		_u.SetPasswordUpdatedAt(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UserUpdate) SetCreatedAt(v time.Time) *UserUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UserUpdate) SetNillableCreatedAt(v *time.Time) *UserUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdate) SetUpdatedAt(v time.Time) *UserUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdate) Mutation() *UserMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdate) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := user.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "User.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Nickname(); ok {
		if err := user.NicknameValidator(v); err != nil {
			return &ValidationError{Name: "nickname", err: fmt.Errorf(`ent: validator failed for field "User.nickname": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.Nickname(); ok {
		_spec.SetField(user.FieldNickname, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(user.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Avatar(); ok {
		_spec.SetField(user.FieldAvatar, field.TypeString, value)
	}
	if _u.mutation.AvatarCleared() {
		_spec.ClearField(user.FieldAvatar, field.TypeString)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(user.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(user.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(user.FieldPhone, field.TypeString)
	}
	if value, ok := _u.mutation.Gender(); ok {
		_spec.SetField(user.FieldGender, field.TypeString, value)
	}
	if _u.mutation.GenderCleared() {
		_spec.ClearField(user.FieldGender, field.TypeString)
	}
	if value, ok := _u.mutation.BirthDate(); ok {
		_spec.SetField(user.FieldBirthDate, field.TypeString, value)
	}
	if _u.mutation.BirthDateCleared() {
		_spec.ClearField(user.FieldBirthDate, field.TypeString)
	}
	if value, ok := _u.mutation.DepartmentID(); ok {
		_spec.SetField(user.FieldDepartmentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDepartmentID(); ok {
		_spec.AddField(user.FieldDepartmentID, field.TypeInt, value)
	}
	if _u.mutation.DepartmentIDCleared() {
		_spec.ClearField(user.FieldDepartmentID, field.TypeInt)
	}
	if value, ok := _u.mutation.Preferences(); ok {
		_spec.SetField(user.FieldPreferences, field.TypeJSON, value)
	}
	if _u.mutation.PreferencesCleared() {
		_spec.ClearField(user.FieldPreferences, field.TypeJSON)
	}
	if value, ok := _u.mutation.FavoriteMenus(); ok {
		_spec.SetField(user.FieldFavoriteMenus, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedFavoriteMenus(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, user.FieldFavoriteMenus, value)
		})
	}
	if _u.mutation.FavoriteMenusCleared() {
		_spec.ClearField(user.FieldFavoriteMenus, field.TypeJSON)
	}
	if value, ok := _u.mutation.UserDataScope(); ok {
		_spec.SetField(user.FieldUserDataScope, field.TypeString, value)
	}
	if _u.mutation.UserDataScopeCleared() {
		_spec.ClearField(user.FieldUserDataScope, field.TypeString)
	}
	if value, ok := _u.mutation.PasswordUpdatedAt(); ok {
		_spec.SetField(user.FieldPasswordUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserMutation
}

// SetUsername sets the "username" field.
func (_u *UserUpdateOne) SetUsername(v string) *UserUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableUsername(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetNickname sets the "nickname" field.
func (_u *UserUpdateOne) SetNickname(v string) *UserUpdateOne {
	_u.mutation.SetNickname(v)
	return _u
}

// SetNillableNickname sets the "nickname" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableNickname(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetNickname(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *UserUpdateOne) SetPasswordHash(v string) *UserUpdateOne {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePasswordHash(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *UserUpdateOne) SetStatus(v string) *UserUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableStatus(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAvatar sets the "avatar" field.
func (_u *UserUpdateOne) SetAvatar(v string) *UserUpdateOne {
	_u.mutation.SetAvatar(v)
	return _u
}

// SetNillableAvatar sets the "avatar" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableAvatar(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetAvatar(*v)
	}
	return _u
}

// ClearAvatar clears the value of the "avatar" field.
func (_u *UserUpdateOne) ClearAvatar() *UserUpdateOne {
	_u.mutation.ClearAvatar()
	return _u
}

// SetEmail sets the "email" field.
func (_u *UserUpdateOne) SetEmail(v string) *UserUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableEmail(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *UserUpdateOne) ClearEmail() *UserUpdateOne {
	_u.mutation.ClearEmail()
	return _u
}

// SetPhone sets the "phone" field.
func (_u *UserUpdateOne) SetPhone(v string) *UserUpdateOne {
	_u.mutation.SetPhone(v)
	return _u
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePhone(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetPhone(*v)
	}
	return _u
}

// ClearPhone clears the value of the "phone" field.
func (_u *UserUpdateOne) ClearPhone() *UserUpdateOne {
	_u.mutation.ClearPhone()
	return _u
}

// SetGender sets the "gender" field.
func (_u *UserUpdateOne) SetGender(v string) *UserUpdateOne {
	_u.mutation.SetGender(v)
	return _u
}

// SetNillableGender sets the "gender" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableGender(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetGender(*v)
	}
	return _u
}

// ClearGender clears the value of the "gender" field.
func (_u *UserUpdateOne) ClearGender() *UserUpdateOne {
	_u.mutation.ClearGender()
	return _u
}

// SetBirthDate sets the "birth_date" field.
func (_u *UserUpdateOne) SetBirthDate(v string) *UserUpdateOne {
	_u.mutation.SetBirthDate(v)
	return _u
}

// SetNillableBirthDate sets the "birth_date" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableBirthDate(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetBirthDate(*v)
	}
	return _u
}

// ClearBirthDate clears the value of the "birth_date" field.
func (_u *UserUpdateOne) ClearBirthDate() *UserUpdateOne {
	_u.mutation.ClearBirthDate()
	return _u
}

// SetDepartmentID sets the "department_id" field.
func (_u *UserUpdateOne) SetDepartmentID(v int) *UserUpdateOne {
	_u.mutation.ResetDepartmentID()
	_u.mutation.SetDepartmentID(v)
	return _u
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableDepartmentID(v *int) *UserUpdateOne {
	if v != nil {
		_u.SetDepartmentID(*v)
	}
	return _u
}

// AddDepartmentID adds value to the "department_id" field.
func (_u *UserUpdateOne) AddDepartmentID(v int) *UserUpdateOne {
	_u.mutation.AddDepartmentID(v)
	return _u
}

// ClearDepartmentID clears the value of the "department_id" field.
func (_u *UserUpdateOne) ClearDepartmentID() *UserUpdateOne {
	_u.mutation.ClearDepartmentID()
	return _u
}

// SetPreferences sets the "preferences" field.
func (_u *UserUpdateOne) SetPreferences(v map[string]interface{}) *UserUpdateOne {
	_u.mutation.SetPreferences(v)
	return _u
}

// ClearPreferences clears the value of the "preferences" field.
func (_u *UserUpdateOne) ClearPreferences() *UserUpdateOne {
	_u.mutation.ClearPreferences()
	return _u
}

// SetFavoriteMenus sets the "favorite_menus" field.
func (_u *UserUpdateOne) SetFavoriteMenus(v []int) *UserUpdateOne {
	_u.mutation.SetFavoriteMenus(v)
	return _u
}

// AppendFavoriteMenus appends value to the "favorite_menus" field.
func (_u *UserUpdateOne) AppendFavoriteMenus(v []int) *UserUpdateOne {
	_u.mutation.AppendFavoriteMenus(v)
	return _u
}

// ClearFavoriteMenus clears the value of the "favorite_menus" field.
func (_u *UserUpdateOne) ClearFavoriteMenus() *UserUpdateOne {
	_u.mutation.ClearFavoriteMenus()
	return _u
}

// SetUserDataScope sets the "user_data_scope" field.
func (_u *UserUpdateOne) SetUserDataScope(v string) *UserUpdateOne {
	_u.mutation.SetUserDataScope(v)
	return _u
}

// SetNillableUserDataScope sets the "user_data_scope" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableUserDataScope(v *string) *UserUpdateOne {
	if v != nil {
		_u.SetUserDataScope(*v)
	}
	return _u
}

// ClearUserDataScope clears the value of the "user_data_scope" field.
func (_u *UserUpdateOne) ClearUserDataScope() *UserUpdateOne {
	_u.mutation.ClearUserDataScope()
	return _u
}

// SetPasswordUpdatedAt sets the "password_updated_at" field.
func (_u *UserUpdateOne) SetPasswordUpdatedAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetPasswordUpdatedAt(v)
	return _u
}

// SetNillablePasswordUpdatedAt sets the "password_updated_at" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillablePasswordUpdatedAt(v *time.Time) *UserUpdateOne {
	if v != nil {
		_u.SetPasswordUpdatedAt(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *UserUpdateOne) SetCreatedAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *UserUpdateOne) SetNillableCreatedAt(v *time.Time) *UserUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserUpdateOne) SetUpdatedAt(v time.Time) *UserUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the UserMutation object of the builder.
func (_u *UserUpdateOne) Mutation() *UserMutation {
	return _u.mutation
}

// Where appends a list predicates to the UserUpdate builder.
func (_u *UserUpdateOne) Where(ps ...predicate.User) *UserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserUpdateOne) Select(field string, fields ...string) *UserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated User entity.
func (_u *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserUpdateOne) SaveX(ctx context.Context) *User {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := user.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserUpdateOne) check() error {
	if v, ok := _u.mutation.Username(); ok {
		if err := user.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "User.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Nickname(); ok {
		if err := user.NicknameValidator(v); err != nil {
			return &ValidationError{Name: "nickname", err: fmt.Errorf(`ent: validator failed for field "User.nickname": %w`, err)}
		}
	}
	return nil
}

func (_u *UserUpdateOne) sqlSave(ctx context.Context) (_node *User, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(user.Table, user.Columns, sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "User.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, user.FieldID)
		for _, f := range fields {
			if !user.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != user.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(user.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.Nickname(); ok {
		_spec.SetField(user.FieldNickname, field.TypeString, value)
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(user.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(user.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Avatar(); ok {
		_spec.SetField(user.FieldAvatar, field.TypeString, value)
	}
	if _u.mutation.AvatarCleared() {
		_spec.ClearField(user.FieldAvatar, field.TypeString)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(user.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(user.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.Phone(); ok {
		_spec.SetField(user.FieldPhone, field.TypeString, value)
	}
	if _u.mutation.PhoneCleared() {
		_spec.ClearField(user.FieldPhone, field.TypeString)
	}
	if value, ok := _u.mutation.Gender(); ok {
		_spec.SetField(user.FieldGender, field.TypeString, value)
	}
	if _u.mutation.GenderCleared() {
		_spec.ClearField(user.FieldGender, field.TypeString)
	}
	if value, ok := _u.mutation.BirthDate(); ok {
		_spec.SetField(user.FieldBirthDate, field.TypeString, value)
	}
	if _u.mutation.BirthDateCleared() {
		_spec.ClearField(user.FieldBirthDate, field.TypeString)
	}
	if value, ok := _u.mutation.DepartmentID(); ok {
		_spec.SetField(user.FieldDepartmentID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDepartmentID(); ok {
		_spec.AddField(user.FieldDepartmentID, field.TypeInt, value)
	}
	if _u.mutation.DepartmentIDCleared() {
		_spec.ClearField(user.FieldDepartmentID, field.TypeInt)
	}
	if value, ok := _u.mutation.Preferences(); ok {
		_spec.SetField(user.FieldPreferences, field.TypeJSON, value)
	}
	if _u.mutation.PreferencesCleared() {
		_spec.ClearField(user.FieldPreferences, field.TypeJSON)
	}
	if value, ok := _u.mutation.FavoriteMenus(); ok {
		_spec.SetField(user.FieldFavoriteMenus, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedFavoriteMenus(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, user.FieldFavoriteMenus, value)
		})
	}
	if _u.mutation.FavoriteMenusCleared() {
		_spec.ClearField(user.FieldFavoriteMenus, field.TypeJSON)
	}
	if value, ok := _u.mutation.UserDataScope(); ok {
		_spec.SetField(user.FieldUserDataScope, field.TypeString, value)
	}
	if _u.mutation.UserDataScopeCleared() {
		_spec.ClearField(user.FieldUserDataScope, field.TypeString)
	}
	if value, ok := _u.mutation.PasswordUpdatedAt(); ok {
		_spec.SetField(user.FieldPasswordUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(user.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(user.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &User{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
