// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/fudanda/arcbase/backend/ent/userpermission"
)

// UserPermission is the model entity for the UserPermission schema.
type UserPermission struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// Permission holds the value of the "permission" field.
	Permission   string `json:"permission,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserPermission) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case userpermission.FieldID, userpermission.FieldUserID:
			values[i] = new(sql.NullInt64)
		case userpermission.FieldPermission:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserPermission fields.
func (_m *UserPermission) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userpermission.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case userpermission.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case userpermission.FieldPermission:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field permission", values[i])
			} else if value.Valid {
				_m.Permission = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserPermission.
// This includes values selected through modifiers, order, etc.
func (_m *UserPermission) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UserPermission.
// Note that you need to call UserPermission.Unwrap() before calling this method if this UserPermission
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserPermission) Update() *UserPermissionUpdateOne {
	return NewUserPermissionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserPermission entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserPermission) Unwrap() *UserPermission {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserPermission is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserPermission) String() string {
	var builder strings.Builder
	builder.WriteString("UserPermission(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("permission=")
	builder.WriteString(_m.Permission)
	builder.WriteByte(')')
	return builder.String()
}

// UserPermissions is a parsable slice of UserPermission.
type UserPermissions []*UserPermission
