// Code generated by ent, DO NOT EDIT.

package filestorageconfig

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/fudanda/arcbase/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEQ(FieldName, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEQ(FieldProvider, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEQ(FieldStatus, v))
}

// IsDefault applies equality check predicate on the "is_default" field. It's identical to IsDefaultEQ.
func IsDefault(v bool) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEQ(FieldIsDefault, v))
}

// LocalRootPath applies equality check predicate on the "local_root_path" field. It's identical to LocalRootPathEQ.
func LocalRootPath(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEQ(FieldLocalRootPath, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEQ(FieldRemark, v))
}

// S3Region applies equality check predicate on the "s3_region" field. It's identical to S3RegionEQ.
func S3Region(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEQ(FieldS3Region, v))
}

// S3Endpoint applies equality check predicate on the "s3_endpoint" field. It's identical to S3EndpointEQ.
func S3Endpoint(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEQ(FieldS3Endpoint, v))
}

// S3Bucket applies equality check predicate on the "s3_bucket" field. It's identical to S3BucketEQ.
func S3Bucket(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEQ(FieldS3Bucket, v))
}

// S3AccessKeyID applies equality check predicate on the "s3_access_key_id" field. It's identical to S3AccessKeyIDEQ.
func S3AccessKeyID(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEQ(FieldS3AccessKeyID, v))
}

// S3SecretCipher applies equality check predicate on the "s3_secret_cipher" field. It's identical to S3SecretCipherEQ.
func S3SecretCipher(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEQ(FieldS3SecretCipher, v))
}

// S3ForcePathStyle applies equality check predicate on the "s3_force_path_style" field. It's identical to S3ForcePathStyleEQ.
func S3ForcePathStyle(v bool) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEQ(FieldS3ForcePathStyle, v))
}

// BasePath applies equality check predicate on the "base_path" field. It's identical to BasePathEQ.
func BasePath(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEQ(FieldBasePath, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldContainsFold(FieldName, v))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldContainsFold(FieldProvider, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldContainsFold(FieldStatus, v))
}

// IsDefaultEQ applies the EQ predicate on the "is_default" field.
func IsDefaultEQ(v bool) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEQ(FieldIsDefault, v))
}

// IsDefaultNEQ applies the NEQ predicate on the "is_default" field.
func IsDefaultNEQ(v bool) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldNEQ(FieldIsDefault, v))
}

// LocalRootPathEQ applies the EQ predicate on the "local_root_path" field.
func LocalRootPathEQ(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEQ(FieldLocalRootPath, v))
}

// LocalRootPathNEQ applies the NEQ predicate on the "local_root_path" field.
func LocalRootPathNEQ(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldNEQ(FieldLocalRootPath, v))
}

// LocalRootPathIn applies the In predicate on the "local_root_path" field.
func LocalRootPathIn(vs ...string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldIn(FieldLocalRootPath, vs...))
}

// LocalRootPathNotIn applies the NotIn predicate on the "local_root_path" field.
func LocalRootPathNotIn(vs ...string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldNotIn(FieldLocalRootPath, vs...))
}

// LocalRootPathGT applies the GT predicate on the "local_root_path" field.
func LocalRootPathGT(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldGT(FieldLocalRootPath, v))
}

// LocalRootPathGTE applies the GTE predicate on the "local_root_path" field.
func LocalRootPathGTE(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldGTE(FieldLocalRootPath, v))
}

// LocalRootPathLT applies the LT predicate on the "local_root_path" field.
func LocalRootPathLT(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldLT(FieldLocalRootPath, v))
}

// LocalRootPathLTE applies the LTE predicate on the "local_root_path" field.
func LocalRootPathLTE(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldLTE(FieldLocalRootPath, v))
}

// LocalRootPathContains applies the Contains predicate on the "local_root_path" field.
func LocalRootPathContains(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldContains(FieldLocalRootPath, v))
}

// LocalRootPathHasPrefix applies the HasPrefix predicate on the "local_root_path" field.
func LocalRootPathHasPrefix(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldHasPrefix(FieldLocalRootPath, v))
}

// LocalRootPathHasSuffix applies the HasSuffix predicate on the "local_root_path" field.
func LocalRootPathHasSuffix(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldHasSuffix(FieldLocalRootPath, v))
}

// LocalRootPathEqualFold applies the EqualFold predicate on the "local_root_path" field.
func LocalRootPathEqualFold(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEqualFold(FieldLocalRootPath, v))
}

// LocalRootPathContainsFold applies the ContainsFold predicate on the "local_root_path" field.
func LocalRootPathContainsFold(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldContainsFold(FieldLocalRootPath, v))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldContainsFold(FieldRemark, v))
}

// S3RegionEQ applies the EQ predicate on the "s3_region" field.
func S3RegionEQ(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEQ(FieldS3Region, v))
}

// S3RegionNEQ applies the NEQ predicate on the "s3_region" field.
func S3RegionNEQ(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldNEQ(FieldS3Region, v))
}

// S3RegionIn applies the In predicate on the "s3_region" field.
func S3RegionIn(vs ...string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldIn(FieldS3Region, vs...))
}

// S3RegionNotIn applies the NotIn predicate on the "s3_region" field.
func S3RegionNotIn(vs ...string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldNotIn(FieldS3Region, vs...))
}

// S3RegionGT applies the GT predicate on the "s3_region" field.
func S3RegionGT(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldGT(FieldS3Region, v))
}

// S3RegionGTE applies the GTE predicate on the "s3_region" field.
func S3RegionGTE(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldGTE(FieldS3Region, v))
}

// S3RegionLT applies the LT predicate on the "s3_region" field.
func S3RegionLT(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldLT(FieldS3Region, v))
}

// S3RegionLTE applies the LTE predicate on the "s3_region" field.
func S3RegionLTE(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldLTE(FieldS3Region, v))
}

// S3RegionContains applies the Contains predicate on the "s3_region" field.
func S3RegionContains(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldContains(FieldS3Region, v))
}

// S3RegionHasPrefix applies the HasPrefix predicate on the "s3_region" field.
func S3RegionHasPrefix(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldHasPrefix(FieldS3Region, v))
}

// S3RegionHasSuffix applies the HasSuffix predicate on the "s3_region" field.
func S3RegionHasSuffix(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldHasSuffix(FieldS3Region, v))
}

// S3RegionEqualFold applies the EqualFold predicate on the "s3_region" field.
func S3RegionEqualFold(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEqualFold(FieldS3Region, v))
}

// S3RegionContainsFold applies the ContainsFold predicate on the "s3_region" field.
func S3RegionContainsFold(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldContainsFold(FieldS3Region, v))
}

// S3EndpointEQ applies the EQ predicate on the "s3_endpoint" field.
func S3EndpointEQ(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEQ(FieldS3Endpoint, v))
}

// S3EndpointNEQ applies the NEQ predicate on the "s3_endpoint" field.
func S3EndpointNEQ(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldNEQ(FieldS3Endpoint, v))
}

// S3EndpointIn applies the In predicate on the "s3_endpoint" field.
func S3EndpointIn(vs ...string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldIn(FieldS3Endpoint, vs...))
}

// S3EndpointNotIn applies the NotIn predicate on the "s3_endpoint" field.
func S3EndpointNotIn(vs ...string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldNotIn(FieldS3Endpoint, vs...))
}

// S3EndpointGT applies the GT predicate on the "s3_endpoint" field.
func S3EndpointGT(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldGT(FieldS3Endpoint, v))
}

// S3EndpointGTE applies the GTE predicate on the "s3_endpoint" field.
func S3EndpointGTE(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldGTE(FieldS3Endpoint, v))
}

// S3EndpointLT applies the LT predicate on the "s3_endpoint" field.
func S3EndpointLT(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldLT(FieldS3Endpoint, v))
}

// S3EndpointLTE applies the LTE predicate on the "s3_endpoint" field.
func S3EndpointLTE(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldLTE(FieldS3Endpoint, v))
}

// S3EndpointContains applies the Contains predicate on the "s3_endpoint" field.
func S3EndpointContains(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldContains(FieldS3Endpoint, v))
}

// S3EndpointHasPrefix applies the HasPrefix predicate on the "s3_endpoint" field.
func S3EndpointHasPrefix(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldHasPrefix(FieldS3Endpoint, v))
}

// S3EndpointHasSuffix applies the HasSuffix predicate on the "s3_endpoint" field.
func S3EndpointHasSuffix(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldHasSuffix(FieldS3Endpoint, v))
}

// S3EndpointEqualFold applies the EqualFold predicate on the "s3_endpoint" field.
func S3EndpointEqualFold(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEqualFold(FieldS3Endpoint, v))
}

// S3EndpointContainsFold applies the ContainsFold predicate on the "s3_endpoint" field.
func S3EndpointContainsFold(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldContainsFold(FieldS3Endpoint, v))
}

// S3BucketEQ applies the EQ predicate on the "s3_bucket" field.
func S3BucketEQ(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEQ(FieldS3Bucket, v))
}

// S3BucketNEQ applies the NEQ predicate on the "s3_bucket" field.
func S3BucketNEQ(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldNEQ(FieldS3Bucket, v))
}

// S3BucketIn applies the In predicate on the "s3_bucket" field.
func S3BucketIn(vs ...string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldIn(FieldS3Bucket, vs...))
}

// S3BucketNotIn applies the NotIn predicate on the "s3_bucket" field.
func S3BucketNotIn(vs ...string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldNotIn(FieldS3Bucket, vs...))
}

// S3BucketGT applies the GT predicate on the "s3_bucket" field.
func S3BucketGT(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldGT(FieldS3Bucket, v))
}

// S3BucketGTE applies the GTE predicate on the "s3_bucket" field.
func S3BucketGTE(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldGTE(FieldS3Bucket, v))
}

// S3BucketLT applies the LT predicate on the "s3_bucket" field.
func S3BucketLT(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldLT(FieldS3Bucket, v))
}

// S3BucketLTE applies the LTE predicate on the "s3_bucket" field.
func S3BucketLTE(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldLTE(FieldS3Bucket, v))
}

// S3BucketContains applies the Contains predicate on the "s3_bucket" field.
func S3BucketContains(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldContains(FieldS3Bucket, v))
}

// S3BucketHasPrefix applies the HasPrefix predicate on the "s3_bucket" field.
func S3BucketHasPrefix(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldHasPrefix(FieldS3Bucket, v))
}

// S3BucketHasSuffix applies the HasSuffix predicate on the "s3_bucket" field.
func S3BucketHasSuffix(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldHasSuffix(FieldS3Bucket, v))
}

// S3BucketEqualFold applies the EqualFold predicate on the "s3_bucket" field.
func S3BucketEqualFold(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEqualFold(FieldS3Bucket, v))
}

// S3BucketContainsFold applies the ContainsFold predicate on the "s3_bucket" field.
func S3BucketContainsFold(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldContainsFold(FieldS3Bucket, v))
}

// S3AccessKeyIDEQ applies the EQ predicate on the "s3_access_key_id" field.
func S3AccessKeyIDEQ(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEQ(FieldS3AccessKeyID, v))
}

// S3AccessKeyIDNEQ applies the NEQ predicate on the "s3_access_key_id" field.
func S3AccessKeyIDNEQ(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldNEQ(FieldS3AccessKeyID, v))
}

// S3AccessKeyIDIn applies the In predicate on the "s3_access_key_id" field.
func S3AccessKeyIDIn(vs ...string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldIn(FieldS3AccessKeyID, vs...))
}

// S3AccessKeyIDNotIn applies the NotIn predicate on the "s3_access_key_id" field.
func S3AccessKeyIDNotIn(vs ...string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldNotIn(FieldS3AccessKeyID, vs...))
}

// S3AccessKeyIDGT applies the GT predicate on the "s3_access_key_id" field.
func S3AccessKeyIDGT(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldGT(FieldS3AccessKeyID, v))
}

// S3AccessKeyIDGTE applies the GTE predicate on the "s3_access_key_id" field.
func S3AccessKeyIDGTE(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldGTE(FieldS3AccessKeyID, v))
}

// S3AccessKeyIDLT applies the LT predicate on the "s3_access_key_id" field.
func S3AccessKeyIDLT(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldLT(FieldS3AccessKeyID, v))
}

// S3AccessKeyIDLTE applies the LTE predicate on the "s3_access_key_id" field.
func S3AccessKeyIDLTE(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldLTE(FieldS3AccessKeyID, v))
}

// S3AccessKeyIDContains applies the Contains predicate on the "s3_access_key_id" field.
func S3AccessKeyIDContains(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldContains(FieldS3AccessKeyID, v))
}

// S3AccessKeyIDHasPrefix applies the HasPrefix predicate on the "s3_access_key_id" field.
func S3AccessKeyIDHasPrefix(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldHasPrefix(FieldS3AccessKeyID, v))
}

// S3AccessKeyIDHasSuffix applies the HasSuffix predicate on the "s3_access_key_id" field.
func S3AccessKeyIDHasSuffix(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldHasSuffix(FieldS3AccessKeyID, v))
}

// S3AccessKeyIDEqualFold applies the EqualFold predicate on the "s3_access_key_id" field.
func S3AccessKeyIDEqualFold(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEqualFold(FieldS3AccessKeyID, v))
}

// S3AccessKeyIDContainsFold applies the ContainsFold predicate on the "s3_access_key_id" field.
func S3AccessKeyIDContainsFold(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldContainsFold(FieldS3AccessKeyID, v))
}

// S3SecretCipherEQ applies the EQ predicate on the "s3_secret_cipher" field.
func S3SecretCipherEQ(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEQ(FieldS3SecretCipher, v))
}

// S3SecretCipherNEQ applies the NEQ predicate on the "s3_secret_cipher" field.
func S3SecretCipherNEQ(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldNEQ(FieldS3SecretCipher, v))
}

// S3SecretCipherIn applies the In predicate on the "s3_secret_cipher" field.
func S3SecretCipherIn(vs ...string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldIn(FieldS3SecretCipher, vs...))
}

// S3SecretCipherNotIn applies the NotIn predicate on the "s3_secret_cipher" field.
func S3SecretCipherNotIn(vs ...string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldNotIn(FieldS3SecretCipher, vs...))
}

// S3SecretCipherGT applies the GT predicate on the "s3_secret_cipher" field.
func S3SecretCipherGT(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldGT(FieldS3SecretCipher, v))
}

// S3SecretCipherGTE applies the GTE predicate on the "s3_secret_cipher" field.
func S3SecretCipherGTE(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldGTE(FieldS3SecretCipher, v))
}

// S3SecretCipherLT applies the LT predicate on the "s3_secret_cipher" field.
func S3SecretCipherLT(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldLT(FieldS3SecretCipher, v))
}

// S3SecretCipherLTE applies the LTE predicate on the "s3_secret_cipher" field.
func S3SecretCipherLTE(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldLTE(FieldS3SecretCipher, v))
}

// S3SecretCipherContains applies the Contains predicate on the "s3_secret_cipher" field.
func S3SecretCipherContains(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldContains(FieldS3SecretCipher, v))
}

// S3SecretCipherHasPrefix applies the HasPrefix predicate on the "s3_secret_cipher" field.
func S3SecretCipherHasPrefix(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldHasPrefix(FieldS3SecretCipher, v))
}

// S3SecretCipherHasSuffix applies the HasSuffix predicate on the "s3_secret_cipher" field.
func S3SecretCipherHasSuffix(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldHasSuffix(FieldS3SecretCipher, v))
}

// S3SecretCipherEqualFold applies the EqualFold predicate on the "s3_secret_cipher" field.
func S3SecretCipherEqualFold(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEqualFold(FieldS3SecretCipher, v))
}

// S3SecretCipherContainsFold applies the ContainsFold predicate on the "s3_secret_cipher" field.
func S3SecretCipherContainsFold(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldContainsFold(FieldS3SecretCipher, v))
}

// S3ForcePathStyleEQ applies the EQ predicate on the "s3_force_path_style" field.
func S3ForcePathStyleEQ(v bool) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEQ(FieldS3ForcePathStyle, v))
}

// S3ForcePathStyleNEQ applies the NEQ predicate on the "s3_force_path_style" field.
func S3ForcePathStyleNEQ(v bool) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldNEQ(FieldS3ForcePathStyle, v))
}

// BasePathEQ applies the EQ predicate on the "base_path" field.
func BasePathEQ(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEQ(FieldBasePath, v))
}

// BasePathNEQ applies the NEQ predicate on the "base_path" field.
func BasePathNEQ(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldNEQ(FieldBasePath, v))
}

// BasePathIn applies the In predicate on the "base_path" field.
func BasePathIn(vs ...string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldIn(FieldBasePath, vs...))
}

// BasePathNotIn applies the NotIn predicate on the "base_path" field.
func BasePathNotIn(vs ...string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldNotIn(FieldBasePath, vs...))
}

// BasePathGT applies the GT predicate on the "base_path" field.
func BasePathGT(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldGT(FieldBasePath, v))
}

// BasePathGTE applies the GTE predicate on the "base_path" field.
func BasePathGTE(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldGTE(FieldBasePath, v))
}

// BasePathLT applies the LT predicate on the "base_path" field.
func BasePathLT(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldLT(FieldBasePath, v))
}

// BasePathLTE applies the LTE predicate on the "base_path" field.
func BasePathLTE(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldLTE(FieldBasePath, v))
}

// BasePathContains applies the Contains predicate on the "base_path" field.
func BasePathContains(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldContains(FieldBasePath, v))
}

// BasePathHasPrefix applies the HasPrefix predicate on the "base_path" field.
func BasePathHasPrefix(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldHasPrefix(FieldBasePath, v))
}

// BasePathHasSuffix applies the HasSuffix predicate on the "base_path" field.
func BasePathHasSuffix(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldHasSuffix(FieldBasePath, v))
}

// BasePathEqualFold applies the EqualFold predicate on the "base_path" field.
func BasePathEqualFold(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEqualFold(FieldBasePath, v))
}

// BasePathContainsFold applies the ContainsFold predicate on the "base_path" field.
func BasePathContainsFold(v string) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldContainsFold(FieldBasePath, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.FileStorageConfig) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.FileStorageConfig) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.FileStorageConfig) predicate.FileStorageConfig {
	return predicate.FileStorageConfig(sql.NotPredicates(p))
}
