// Code generated by ent, DO NOT EDIT.

package loginattempt

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/fudanda/zenith-admin/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldLTE(FieldID, id))
}

// Key applies equality check predicate on the "key" field. It's identical to KeyEQ.
func Key(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldEQ(FieldKey, v))
}

// UsernameHash applies equality check predicate on the "username_hash" field. It's identical to UsernameHashEQ.
func UsernameHash(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldEQ(FieldUsernameHash, v))
}

// Failures applies equality check predicate on the "failures" field. It's identical to FailuresEQ.
func Failures(v int) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldEQ(FieldFailures, v))
}

// LockedUntil applies equality check predicate on the "locked_until" field. It's identical to LockedUntilEQ.
func LockedUntil(v time.Time) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldEQ(FieldLockedUntil, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldEQ(FieldUpdatedAt, v))
}

// KeyEQ applies the EQ predicate on the "key" field.
func KeyEQ(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldEQ(FieldKey, v))
}

// KeyNEQ applies the NEQ predicate on the "key" field.
func KeyNEQ(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldNEQ(FieldKey, v))
}

// KeyIn applies the In predicate on the "key" field.
func KeyIn(vs ...string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldIn(FieldKey, vs...))
}

// KeyNotIn applies the NotIn predicate on the "key" field.
func KeyNotIn(vs ...string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldNotIn(FieldKey, vs...))
}

// KeyGT applies the GT predicate on the "key" field.
func KeyGT(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldGT(FieldKey, v))
}

// KeyGTE applies the GTE predicate on the "key" field.
func KeyGTE(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldGTE(FieldKey, v))
}

// KeyLT applies the LT predicate on the "key" field.
func KeyLT(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldLT(FieldKey, v))
}

// KeyLTE applies the LTE predicate on the "key" field.
func KeyLTE(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldLTE(FieldKey, v))
}

// KeyContains applies the Contains predicate on the "key" field.
func KeyContains(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldContains(FieldKey, v))
}

// KeyHasPrefix applies the HasPrefix predicate on the "key" field.
func KeyHasPrefix(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldHasPrefix(FieldKey, v))
}

// KeyHasSuffix applies the HasSuffix predicate on the "key" field.
func KeyHasSuffix(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldHasSuffix(FieldKey, v))
}

// KeyEqualFold applies the EqualFold predicate on the "key" field.
func KeyEqualFold(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldEqualFold(FieldKey, v))
}

// KeyContainsFold applies the ContainsFold predicate on the "key" field.
func KeyContainsFold(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldContainsFold(FieldKey, v))
}

// UsernameHashEQ applies the EQ predicate on the "username_hash" field.
func UsernameHashEQ(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldEQ(FieldUsernameHash, v))
}

// UsernameHashNEQ applies the NEQ predicate on the "username_hash" field.
func UsernameHashNEQ(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldNEQ(FieldUsernameHash, v))
}

// UsernameHashIn applies the In predicate on the "username_hash" field.
func UsernameHashIn(vs ...string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldIn(FieldUsernameHash, vs...))
}

// UsernameHashNotIn applies the NotIn predicate on the "username_hash" field.
func UsernameHashNotIn(vs ...string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldNotIn(FieldUsernameHash, vs...))
}

// UsernameHashGT applies the GT predicate on the "username_hash" field.
func UsernameHashGT(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldGT(FieldUsernameHash, v))
}

// UsernameHashGTE applies the GTE predicate on the "username_hash" field.
func UsernameHashGTE(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldGTE(FieldUsernameHash, v))
}

// UsernameHashLT applies the LT predicate on the "username_hash" field.
func UsernameHashLT(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldLT(FieldUsernameHash, v))
}

// UsernameHashLTE applies the LTE predicate on the "username_hash" field.
func UsernameHashLTE(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldLTE(FieldUsernameHash, v))
}

// UsernameHashContains applies the Contains predicate on the "username_hash" field.
func UsernameHashContains(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldContains(FieldUsernameHash, v))
}

// UsernameHashHasPrefix applies the HasPrefix predicate on the "username_hash" field.
func UsernameHashHasPrefix(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldHasPrefix(FieldUsernameHash, v))
}

// UsernameHashHasSuffix applies the HasSuffix predicate on the "username_hash" field.
func UsernameHashHasSuffix(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldHasSuffix(FieldUsernameHash, v))
}

// UsernameHashEqualFold applies the EqualFold predicate on the "username_hash" field.
func UsernameHashEqualFold(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldEqualFold(FieldUsernameHash, v))
}

// UsernameHashContainsFold applies the ContainsFold predicate on the "username_hash" field.
func UsernameHashContainsFold(v string) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldContainsFold(FieldUsernameHash, v))
}

// FailuresEQ applies the EQ predicate on the "failures" field.
func FailuresEQ(v int) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldEQ(FieldFailures, v))
}

// FailuresNEQ applies the NEQ predicate on the "failures" field.
func FailuresNEQ(v int) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldNEQ(FieldFailures, v))
}

// FailuresIn applies the In predicate on the "failures" field.
func FailuresIn(vs ...int) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldIn(FieldFailures, vs...))
}

// FailuresNotIn applies the NotIn predicate on the "failures" field.
func FailuresNotIn(vs ...int) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldNotIn(FieldFailures, vs...))
}

// FailuresGT applies the GT predicate on the "failures" field.
func FailuresGT(v int) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldGT(FieldFailures, v))
}

// FailuresGTE applies the GTE predicate on the "failures" field.
func FailuresGTE(v int) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldGTE(FieldFailures, v))
}

// FailuresLT applies the LT predicate on the "failures" field.
func FailuresLT(v int) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldLT(FieldFailures, v))
}

// FailuresLTE applies the LTE predicate on the "failures" field.
func FailuresLTE(v int) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldLTE(FieldFailures, v))
}

// LockedUntilEQ applies the EQ predicate on the "locked_until" field.
func LockedUntilEQ(v time.Time) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldEQ(FieldLockedUntil, v))
}

// LockedUntilNEQ applies the NEQ predicate on the "locked_until" field.
func LockedUntilNEQ(v time.Time) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldNEQ(FieldLockedUntil, v))
}

// LockedUntilIn applies the In predicate on the "locked_until" field.
func LockedUntilIn(vs ...time.Time) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldIn(FieldLockedUntil, vs...))
}

// LockedUntilNotIn applies the NotIn predicate on the "locked_until" field.
func LockedUntilNotIn(vs ...time.Time) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldNotIn(FieldLockedUntil, vs...))
}

// LockedUntilGT applies the GT predicate on the "locked_until" field.
func LockedUntilGT(v time.Time) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldGT(FieldLockedUntil, v))
}

// LockedUntilGTE applies the GTE predicate on the "locked_until" field.
func LockedUntilGTE(v time.Time) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldGTE(FieldLockedUntil, v))
}

// LockedUntilLT applies the LT predicate on the "locked_until" field.
func LockedUntilLT(v time.Time) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldLT(FieldLockedUntil, v))
}

// LockedUntilLTE applies the LTE predicate on the "locked_until" field.
func LockedUntilLTE(v time.Time) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldLTE(FieldLockedUntil, v))
}

// LockedUntilIsNil applies the IsNil predicate on the "locked_until" field.
func LockedUntilIsNil() predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldIsNull(FieldLockedUntil))
}

// LockedUntilNotNil applies the NotNil predicate on the "locked_until" field.
func LockedUntilNotNil() predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldNotNull(FieldLockedUntil))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LoginAttempt) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LoginAttempt) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LoginAttempt) predicate.LoginAttempt {
	return predicate.LoginAttempt(sql.NotPredicates(p))
}
