import { definePermissions } from '../core/permissions';

/**
 * report 域权限码注册表：code → 按钮标题 / 所属页面（菜单 name）。
 * 种子 button 节点由此生成（@arcbase/shared/seed），契约操作 / 路由门禁 / 前端按钮以 `Permission` 类型引用。
 * `uiOnly` = 服务端没有任何接口检查该码（纯前端门控或待清理）。
 */
export const REPORT_PERMISSIONS = definePermissions({
  'report:datasource:list': { label: '查询', menu: 'ReportDatasources' },
  'report:datasource:create': { label: '新增数据源', menu: 'ReportDatasources' },
  'report:datasource:update': { label: '编辑数据源', menu: 'ReportDatasources' },
  'report:datasource:delete': { label: '删除数据源', menu: 'ReportDatasources' },
  'report:dataset:list': { label: '查询', menu: 'ReportDatasets' },
  'report:dataset:create': { label: '新增数据集', menu: 'ReportDatasets' },
  'report:dataset:update': { label: '编辑数据集', menu: 'ReportDatasets' },
  'report:dataset:delete': { label: '删除数据集', menu: 'ReportDatasets' },
  'report:dashboard:list': { label: '查询', menu: 'ReportDashboards' },
  'report:dashboard:create': { label: '新增仪表盘', menu: 'ReportDashboards' },
  'report:dashboard:update': { label: '编辑仪表盘', menu: 'ReportDashboards' },
  'report:dashboard:delete': { label: '删除仪表盘', menu: 'ReportDashboards' },
  'report:subscription:list': { label: '查询', menu: 'ReportSubscriptions' },
  'report:subscription:create': { label: '新增订阅', menu: 'ReportSubscriptions' },
  'report:subscription:update': { label: '编辑订阅', menu: 'ReportSubscriptions' },
  'report:subscription:delete': { label: '删除订阅', menu: 'ReportSubscriptions' },
  'report:print:list': { label: '查询', menu: 'ReportPrintTemplates' },
  'report:print:create': { label: '新增打印报表', menu: 'ReportPrintTemplates' },
  'report:print:update': { label: '编辑打印报表', menu: 'ReportPrintTemplates' },
  'report:print:delete': { label: '删除打印报表', menu: 'ReportPrintTemplates' },
  'report:alert:list': { label: '查询', menu: 'ReportAlerts' },
  'report:alert:create': { label: '新增预警', menu: 'ReportAlerts' },
  'report:alert:update': { label: '编辑预警', menu: 'ReportAlerts' },
  'report:alert:delete': { label: '删除预警', menu: 'ReportAlerts' },
  'report:metric:list': { label: '查询', menu: 'ReportMetrics' },
  'report:metric:create': { label: '新增指标', menu: 'ReportMetrics' },
  'report:metric:update': { label: '编辑指标', menu: 'ReportMetrics' },
  'report:metric:delete': { label: '删除指标', menu: 'ReportMetrics' },
  'report:metric:evaluate': { label: '评估指标', menu: 'ReportMetrics' },
  'report:metric:publish': { label: '发布指标', menu: 'ReportMetrics' },
  'report:dq:list': { label: '查询', menu: 'ReportQuality' },
  'report:dq:create': { label: '新增质量规则', menu: 'ReportQuality' },
  'report:dq:update': { label: '编辑质量规则', menu: 'ReportQuality' },
  'report:dq:delete': { label: '删除质量规则', menu: 'ReportQuality' },
  'report:dq:run': { label: '执行质量规则', menu: 'ReportQuality' },
  'report:dq:export': { label: '导出质量记录', menu: 'ReportQuality' },
  'report:folder:list': { label: '查询', menu: 'ReportGovernance' },
  'report:folder:create': { label: '新增资源目录', menu: 'ReportGovernance' },
  'report:folder:update': { label: '编辑资源目录', menu: 'ReportGovernance' },
  'report:folder:delete': { label: '删除资源目录', menu: 'ReportGovernance' },
  'report:resource:acl': { label: '管理资源权限', menu: 'ReportGovernance' },
  'report:resource:access': { label: '查看有效权限', menu: 'ReportGovernance' },
  'report:resource:transfer': { label: '转移资源所有权', menu: 'ReportGovernance' },
  'report:approval:list': { label: '查看发布审批', menu: 'ReportGovernance' },
  'report:approval:request': { label: '申请发布审批', menu: 'ReportGovernance' },
  'report:approval:approve': { label: '处理发布审批', menu: 'ReportGovernance' },
  'report:environment:list': { label: '查看报表环境', menu: 'ReportGovernance' },
  'report:environment:create': { label: '新增报表环境', menu: 'ReportGovernance' },
  'report:environment:update': { label: '编辑报表环境', menu: 'ReportGovernance' },
  'report:environment:delete': { label: '删除报表环境', menu: 'ReportGovernance' },
  'report:environment:promote': { label: '环境发布回滚', menu: 'ReportGovernance' },
  'report:materialization:list': { label: '查看物化快照', menu: 'ReportGovernance' },
  'report:materialization:refresh': { label: '刷新物化快照', menu: 'ReportGovernance' },
  'report:materialization:purge': { label: '清理物化快照', menu: 'ReportGovernance' },
  'report:query-quota:list': { label: '查看查询配额', menu: 'ReportGovernance' },
  'report:query-quota:create': { label: '新增查询配额', menu: 'ReportGovernance' },
  'report:query-quota:update': { label: '编辑查询配额', menu: 'ReportGovernance' },
  'report:query-quota:delete': { label: '删除查询配额', menu: 'ReportGovernance' },
  'report:query-cost:list': { label: '查看查询成本', menu: 'ReportGovernance' },
  'report:sla:list': { label: '查看 SLA', menu: 'ReportGovernance' },
  'report:sla:create': { label: '新增 SLA', menu: 'ReportGovernance' },
  'report:sla:update': { label: '编辑 SLA', menu: 'ReportGovernance' },
  'report:sla:delete': { label: '删除 SLA', menu: 'ReportGovernance' },
  'report:sla:evaluate': { label: '评估 SLA', menu: 'ReportGovernance' },
  'report:query-cost:export': { label: '导出查询成本', menu: 'ReportGovernance' },
  'report:asset:list': { label: '查询', menu: 'ReportAssets' },
  'report:asset:usage': { label: '查看资产用量', menu: 'ReportAssets' },
  'report:deprecation:list': { label: '查看弃用公告', menu: 'ReportAssets' },
  'report:deprecation:create': { label: '新增弃用公告', menu: 'ReportAssets' },
  'report:deprecation:update': { label: '编辑弃用公告', menu: 'ReportAssets' },
  'report:deprecation:publish': { label: '发布弃用公告', menu: 'ReportAssets' },
  'report:deprecation:delete': { label: '删除弃用公告', menu: 'ReportAssets' },
  'report:asset-template:list': { label: '查看资产模板', menu: 'ReportAssets' },
  'report:asset-template:create': { label: '新增资产模板', menu: 'ReportAssets' },
  'report:asset-template:update': { label: '编辑资产模板', menu: 'ReportAssets' },
  'report:asset-template:apply': { label: '应用资产模板', menu: 'ReportAssets' },
  'report:asset-template:delete': { label: '删除资产模板', menu: 'ReportAssets' },
  'report:asset:export': { label: '导出资产目录', menu: 'ReportAssets' },
  'report:chatbi:list': { label: '查询', menu: 'ReportChatBi' },
  'report:chatbi:create': { label: '创建问数会话', menu: 'ReportChatBi' },
  'report:chatbi:update': { label: '编辑问数会话', menu: 'ReportChatBi' },
  'report:chatbi:delete': { label: '删除问数会话', menu: 'ReportChatBi' },
  'report:chatbi:ask': { label: '执行智能问数', menu: 'ReportChatBi' },
  'report:chatbi:save': { label: '保存问数结果', menu: 'ReportChatBi' },
  'report:chatbi:audit': { label: '查看问数审计', menu: 'ReportChatBi' },
  'report:chatbi:manage': { label: '管理问数配额', menu: 'ReportChatBi' },
  'report:fill:template:list': { label: '查询', menu: 'ReportFillTemplates' },
  'report:fill:template:create': { label: '新增填报模板', menu: 'ReportFillTemplates' },
  'report:fill:template:update': { label: '编辑填报模板', menu: 'ReportFillTemplates' },
  'report:fill:template:publish': { label: '发布/下线模板', menu: 'ReportFillTemplates' },
  'report:fill:template:clone': { label: '克隆填报模板', menu: 'ReportFillTemplates' },
  'report:fill:template:delete': { label: '删除填报模板', menu: 'ReportFillTemplates' },
  'report:fill:record:list': { label: '查询', menu: 'ReportFillRecords' },
  'report:fill:record:create': { label: '创建填报记录', menu: 'ReportFillRecords' },
  'report:fill:record:update': { label: '编辑填报记录', menu: 'ReportFillRecords' },
  'report:fill:record:submit': { label: '提交填报记录', menu: 'ReportFillRecords' },
  'report:fill:record:cancel': { label: '撤回填报记录', menu: 'ReportFillRecords' },
  'report:fill:record:review': { label: '审核填报记录', menu: 'ReportFillRecords' },
  'report:fill:record:export': { label: '导出填报记录', menu: 'ReportFillRecords' },
});
