// Code generated by create-zenith. DO NOT EDIT.
import type { ZenithAdminModule } from '@zenith/admin';
import type { AnyOperation } from '@zenith/shared/core';
export const modules: ZenithAdminModule[] = [];
export const operations: AnyOperation[] = [];
