// Code generated by create-arcbase. DO NOT EDIT.
import type { ArcBaseAdminModule } from '@arcbase/admin';
import type { AnyOperation } from '@arcbase/shared/core';
export const modules: ArcBaseAdminModule[] = [];
export const operations: AnyOperation[] = [];
