import type { ShortLink } from '../short-link/contracts';
import { SEED_DATE } from './_base';

/**
 * 短链演示数据：DB seed 与 MSW mock 共用。
 * shortUrl 按本地默认 PUBLIC_BASE_URL 拼装，DB seed 时忽略该派生字段。
 */
export const SEED_SHORT_LINKS: ShortLink[] = [
  {
    id: 1,
    code: 'welcome',
    shortUrl: 'http://localhost:3300/s/welcome',
    targetUrl: 'https://www.example.com/campaign/landing?from=arcbase',
    title: '演示活动落地页',
    redirectType: '302',
    status: 'enabled',
    expiresAt: null,
    expired: false,
    maxVisits: null,
    password: null,
    utmSource: 'arcbase',
    utmMedium: 'shortlink',
    utmCampaign: 'demo',
    utmTerm: null,
    utmContent: null,
    bizType: 'custom',
    bizRef: null,
    remark: '带 UTM 参数的演示短链',
    totalPv: 0,
    lastVisitAt: null,
    createdAt: SEED_DATE,
    updatedAt: SEED_DATE,
  },
  {
    id: 2,
    code: 'guide',
    shortUrl: 'http://localhost:3300/s/guide',
    targetUrl: 'https://www.example.com/help/quick-start',
    title: '快速上手指南',
    redirectType: '302',
    status: 'enabled',
    expiresAt: null,
    expired: false,
    maxVisits: null,
    password: null,
    utmSource: null,
    utmMedium: null,
    utmCampaign: null,
    utmTerm: null,
    utmContent: null,
    bizType: 'custom',
    bizRef: null,
    remark: null,
    totalPv: 0,
    lastVisitAt: null,
    createdAt: SEED_DATE,
    updatedAt: SEED_DATE,
  },
  {
    id: 3,
    code: 'vip2026',
    shortUrl: 'http://localhost:3300/s/vip2026',
    targetUrl: 'https://www.example.com/files/internal-report',
    title: '内部资料（密码访问）',
    redirectType: '302',
    status: 'enabled',
    expiresAt: null,
    expired: false,
    maxVisits: 1000,
    password: '8888',
    utmSource: null,
    utmMedium: null,
    utmCampaign: null,
    utmTerm: null,
    utmContent: null,
    bizType: 'custom',
    bizRef: null,
    remark: '演示密码访问与次数上限',
    totalPv: 0,
    lastVisitAt: null,
    createdAt: SEED_DATE,
    updatedAt: SEED_DATE,
  },
];
