import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createServer } from 'node:net';
import { mkdir, readFile } from 'node:fs/promises';
import { chromium } from 'playwright';

const webRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const viteBin = resolve(dirname(createRequire(import.meta.url).resolve('vite/package.json')), 'bin/vite.js');
const port = await new Promise((done) => {
  const server = createServer();
  server.listen(0, '127.0.0.1', () => { const port = server.address().port; server.close(() => done(port)); });
});
const production = process.env.ARCBASE_BROWSER_PRODUCTION === 'true';
const base = production ? process.env.ARCBASE_BROWSER_API_URL : `http://127.0.0.1:${port}`;
const viteArgs = production ? ['preview', '--outDir', 'dist-go', '--port', String(port)] : [];
const vite = production ? null : spawn(process.execPath, [viteBin, ...viteArgs, '--mode', 'go-foundation', '--host', '127.0.0.1', '--strictPort'], {
  cwd: webRoot, windowsHide: true, stdio: ['ignore', 'pipe', 'pipe'],
  env: { ...process.env, VITE_PORT: String(port), VITE_API_PROXY_TARGET: process.env.ARCBASE_BROWSER_API_URL },
});
let viteOutput=''; vite?.stdout.on('data',(chunk)=>{viteOutput+=chunk}); vite?.stderr.on('data',(chunk)=>{viteOutput+=chunk});
let browser;
const screenshots = process.env.ARCBASE_ACCEPTANCE_SCREENSHOTS;
async function screenshot(page, name) {
  if (!screenshots) return;
  await mkdir(screenshots, { recursive: true });
  await page.screenshot({ path: resolve(screenshots, `${name}.png`), fullPage: true });
}
const apiRequests = [];
const failures = [];
const consoleMessages=[];
const responses = [];
try {
  const deadline = Date.now() + 60000;
  while (true) {
    try { if ((await fetch(`${base}/dash/login`)).ok) break; } catch { /* server warming */ }
    if (Date.now() > deadline) throw new Error('Vite did not start');
    await new Promise((done) => setTimeout(done, 200));
  }
  browser = await chromium.launch({ headless: true });
  const context = await browser.newContext({ acceptDownloads: true, ignoreHTTPSErrors: process.env.ARCBASE_BROWSER_HTTPS === 'true' });
  const externalRequests = [];
  await context.route('**/*', async (route) => {
    const url = new URL(route.request().url());
    if (url.origin !== new URL(base).origin && ['http:', 'https:'].includes(url.protocol)) {
      externalRequests.push(url.hostname);
      await route.abort();
    } else {
      await route.continue();
    }
  });
  const page = await context.newPage();
  page.on('console',(message)=>{if(message.type()==='error') consoleMessages.push(message.text())});
  page.on('pageerror', (err) => failures.push(err.message));
  page.on('request', (req) => { const path = new URL(req.url()).pathname; if (path.startsWith('/api/')) apiRequests.push(path); });
  page.on('response', (res) => { const path = new URL(res.url()).pathname; if (path.startsWith('/api/')) responses.push(`${res.request().method()} ${res.status()} ${path}`); if (path.startsWith('/api/') && res.status() >= 400 && res.status() !== 401) failures.push(`${res.status()} ${path}`); });
  await page.goto(`${base}/dash/login`);
  const image = page.getByAltText('登录验证码');
  await image.waitFor();
  assert.ok((await page.title()).includes('ArcBase'), 'original login exposes the ArcBase brand');
  const svg = Buffer.from((await image.getAttribute('src')).split(',')[1], 'base64').toString();
  const answer = svg.match(/>([A-F0-9]{6})<\/text>/)?.[1];
  assert.ok(answer, 'real Go captcha image');
  await page.getByPlaceholder('请输入用户名/手机号').fill(process.env.ARCBASE_BROWSER_USERNAME);
  await page.getByPlaceholder('请输入密码', { exact: true }).fill(process.env.ARCBASE_BROWSER_PASSWORD);
  await page.getByPlaceholder('请输入验证码').fill(answer);
  await page.getByRole('button', { name: '登录', exact: true }).click();
  await page.waitForURL(/\/dash\/?$/);
  await page.getByText('系统用户总数', { exact: true }).waitFor();
  assert.equal(await page.getByText('公告', { exact: true }).count(), 0, 'unmigrated cards are unmounted');
  assert.ok((await context.cookies()).some((cookie) => cookie.name === 'arcbase_session' && cookie.httpOnly), 'HttpOnly session');
  if (process.env.ARCBASE_BROWSER_HTTPS === 'true') {
    const cookie = (await context.cookies()).find((cookie) => cookie.name === 'arcbase_session');
    assert.equal(cookie.secure, true, 'production HTTPS session is Secure');
    assert.equal(cookie.sameSite, 'Lax', 'production session uses SameSite');
  }
  assert.equal(await page.evaluate(() => Object.keys(localStorage).some((key) => /(?:^|_)token$|refresh_token/.test(key))), false, 'no browser token storage');
  await page.reload();
  await page.getByText('系统用户总数', { exact: true }).waitFor();
  await screenshot(page, 'admin-home');

  assert.equal(await page.locator('#login-tenant-code').count(), 0, 'single organization has no tenant selector');
  await page.goto(`${base}/dash/system/departments`);
  await page.getByRole('button', { name: '新增', exact: true }).click();
  await page.getByPlaceholder('请输入部门名称').fill('浏览器部门');
  await page.getByPlaceholder('请输入部门编码').fill('browser_department');
  await page.getByRole('button', { name: 'confirm', exact: true }).click();
  const departmentRow = page.getByRole('row').filter({ hasText: '浏览器部门' });
  await departmentRow.waitFor();
  await departmentRow.getByText('编辑', { exact: true }).click();
  await page.getByRole('button',{name:'confirm',exact:true}).click({trial:true});
  await page.getByPlaceholder('请输入部门名称').fill('浏览器部门已编辑');
  await page.getByRole('button', { name: 'confirm', exact: true }).click();
  await page.getByRole('row').filter({ hasText: '浏览器部门已编辑' }).waitFor();
  await page.reload();
  await page.getByRole('row').filter({ hasText: '浏览器部门已编辑' }).waitFor();
  const departmentDownload = page.waitForEvent('download');
  await page.locator('.export-button__trigger').click();
  await page.getByText('导出 CSV',{exact:true}).click();
  const departmentCSV = await departmentDownload;
  assert.match(await readFile(await departmentCSV.path(), 'utf8'), /浏览器部门已编辑/, 'original department export');
  await page.getByRole('row').filter({ hasText: '浏览器部门已编辑' }).getByText('删除', { exact: true }).click();
  await page.getByRole('button', { name: /^(confirm|确\s*定)$/ }).click();
  await page.getByRole('row').filter({ hasText: '浏览器部门已编辑' }).waitFor({ state: 'hidden' });

  await page.goto(`${base}/dash/system/positions`);
  await page.getByRole('button', { name: '新增', exact: true }).click();
  await page.getByPlaceholder('请输入岗位名称').fill('浏览器岗位');
  await page.getByPlaceholder('请输入岗位编码').fill('browser_position');
  await page.getByRole('button', { name: 'confirm', exact: true }).click();
  const row = page.getByRole('row').filter({ hasText: '浏览器岗位' });
  await row.waitFor();
  await row.getByText('编辑', { exact: true }).click();
  await page.getByRole('button',{name:'confirm',exact:true}).click({trial:true});
  await page.getByPlaceholder('请输入岗位名称').fill('浏览器岗位已编辑');
  await page.getByRole('button', { name: 'confirm', exact: true }).click();
  await page.getByRole('row').filter({ hasText: '浏览器岗位已编辑' }).waitFor();
  await page.reload();
  const edited = page.getByRole('row').filter({ hasText: '浏览器岗位已编辑' });
  await edited.waitFor();
  await edited.getByText('成员', { exact: true }).click();
  await page.locator('.semi-transfer-left .semi-checkbox').last().click();
  await page.locator('.semi-transfer-right').getByText(process.env.ARCBASE_BROWSER_USERNAME, { exact: true }).waitFor();
  await page.getByRole('button', { name: '保存', exact: true }).click();

  const downloadPromise = page.waitForEvent('download');
  await page.locator('.export-button__trigger').click();
  await page.getByText('导出 CSV',{exact:true}).click();
  const download = await downloadPromise;
  assert.match(await readFile(await download.path(), 'utf8'), /浏览器岗位已编辑/, 'synchronous real CSV');
  await edited.locator('.semi-checkbox').click();
  assert.equal(await edited.getByRole('checkbox').isChecked(), true);
  await page.getByRole('button', { name: /批量删除/ }).click();
  await page.getByRole('button', { name: /^(confirm|确\s*定)$/ }).click();
  await edited.waitFor({ state: 'hidden' });

  await page.goto(`${base}/dash/system/users`);
  await page.getByRole('button', { name: '新增', exact: true }).click();
  await page.getByPlaceholder('请输入用户名', { exact: true }).fill('browser_user');
  await page.getByPlaceholder('请输入昵称', { exact: true }).fill('浏览器用户');
  await page.getByPlaceholder('请输入密码', { exact: true }).fill('BrowserPassword123!');
  await page.getByRole('button', { name: 'confirm', exact: true }).click();
  const userRow = page.getByRole('row').filter({ hasText: 'browser_user' });
  await userRow.waitFor();
  await userRow.getByText('编辑', { exact: true }).click();
  await page.getByRole('button',{name:'confirm',exact:true}).click({trial:true});
  await page.getByPlaceholder('请输入昵称', { exact: true }).fill('浏览器用户已编辑');
  await page.getByRole('button', { name: 'confirm', exact: true }).click();
  await page.getByRole('row').filter({ hasText: '浏览器用户已编辑' }).waitFor();
  await page.reload();
  await page.getByRole('row').filter({ hasText: '浏览器用户已编辑' }).waitFor();
  await page.getByRole('row').filter({hasText:'浏览器用户已编辑'}).getByText('关联信息',{exact:true}).click();
  await page.getByText('操作审计',{exact:true}).first().waitFor();
  assert.equal(await page.getByRole('tab',{name:'业务时间线',exact:true}).count(),0);
  await page.keyboard.press('Escape');
  await userRow.getByRole('button',{name:'更多操作',exact:true}).click();
  await page.getByText('菜单权限',{exact:true}).click();
  await page.getByRole('button',{name:'全选',exact:true}).click();
  const directPermissions=page.waitForResponse(res=>/\/api\/v1\/users\/\d+\/menus$/.test(new URL(res.url()).pathname) && res.request().method()==='PUT');
  await page.getByRole('button',{name:'保存',exact:true}).click();
  assert.equal((await directPermissions).status(),200);
  await userRow.getByRole('button',{name:'更多操作',exact:true}).click();
  await page.getByText('数据权限',{exact:true}).click();
  const dataScopeSaved=page.waitForResponse(res=>/\/api\/v1\/users\/\d+\/data-permission$/.test(new URL(res.url()).pathname) && res.request().method()==='PUT');
  await page.getByRole('button',{name:'confirm',exact:true}).click();
  assert.equal((await dataScopeSaved).status(),200);
  await page.getByRole('button',{name:/^导入/}).click();
  const templateDownload=page.waitForEvent('download');
  await page.getByText('下载导入模板',{exact:true}).click();
  assert.equal((await readFile(await (await templateDownload).path())).subarray(0,2).toString(),'PK','real XLSX template');
  // Wait for clickToHide's exit animation before reopening the same dropdown.
  await page.getByRole('menuitem',{name:'下载导入模板',exact:true}).waitFor({state:'hidden'});
  await page.getByRole('button',{name:/^导入/}).click();
  await page.getByText('预检文件（仅校验不落库）',{exact:true}).click();
  await page.locator('input[accept=".xlsx"]').setInputFiles(process.env.ARCBASE_BROWSER_IMPORT_FILE);
  await page.getByText('预检通过，未写入',{exact:true}).waitFor();
  await page.getByRole('button',{name:'完成',exact:true}).click();
  await page.getByRole('button',{name:/^导入/}).click();
  await page.getByText('上传文件导入',{exact:true}).click();
  await page.locator('input[accept=".xlsx"]').setInputFiles(process.env.ARCBASE_BROWSER_IMPORT_FILE);
  await page.getByText('已创建',{exact:true}).waitFor();
  await page.getByRole('button',{name:'完成',exact:true}).click();
  await page.getByRole('row').filter({hasText:'浏览器导入用户'}).waitFor();
  const userWorkbook=page.waitForEvent('download');
  await page.getByRole('button',{name:'导出',exact:true}).click();
  assert.equal((await readFile(await (await userWorkbook).path())).subarray(0,2).toString(),'PK','real XLSX export');
  await page.goto(`${base}/dash/system/roles`);
  await page.getByRole('button', { name: '新增', exact: true }).click();
  await page.getByPlaceholder('请输入角色名称').fill('浏览器角色');
  await page.getByPlaceholder('请输入角色编码').fill('browser_role');
  await page.getByRole('button', { name: 'confirm', exact: true }).click();
  const roleRow=page.getByRole('row').filter({hasText:'浏览器角色'}); await roleRow.waitFor();
  await roleRow.getByText('编辑',{exact:true}).click();
  await page.getByRole('button',{name:'confirm',exact:true}).click({trial:true});
  await page.getByPlaceholder('请输入角色名称').fill('浏览器角色已编辑');
  const roleEdited=page.waitForResponse(res=>/\/api\/v1\/roles\/\d+$/.test(new URL(res.url()).pathname) && res.request().method()==='PUT');
  await page.getByRole('button',{name:'confirm',exact:true}).click();
  const roleEditResponse=await roleEdited;
  assert.equal(roleEditResponse.status(),200);
  assert.equal((await roleEditResponse.json()).data.name,'浏览器角色已编辑');
  await roleRow.getByText('菜单权限',{exact:true}).click();
  await page.getByRole('button',{name:'全选',exact:true}).click();
  const rolePermissions=page.waitForResponse(res=>/\/api\/v1\/roles\/\d+\/menus$/.test(new URL(res.url()).pathname) && res.request().method()==='PUT');
  await page.getByRole('button',{name:'confirm',exact:true}).click();
  assert.equal((await rolePermissions).status(),200);
  await roleRow.getByRole('button',{name:'更多操作',exact:true}).click();
  await page.getByText('分配用户',{exact:true}).click();
  await page.locator('.semi-transfer-left .semi-checkbox').filter({hasText:'browser_user'}).click();
  const roleMembersSaved=page.waitForResponse(res=>/\/api\/v1\/roles\/\d+\/users$/.test(new URL(res.url()).pathname) && res.request().method()==='PUT');
  await page.getByRole('button',{name:'保存',exact:true}).click();
  assert.equal((await roleMembersSaved).status(),200);
  await page.goto(`${base}/dash/system/user-groups`);
  await page.getByRole('button', { name: '新增', exact: true }).click();
  await page.getByPlaceholder('请输入用户组名称').fill('浏览器用户组');
  await page.getByPlaceholder('字母数字下划线').fill('browser_group');
  await page.getByRole('button', { name: '确定', exact: true }).click();
  const groupRow=page.getByRole('row').filter({hasText:'浏览器用户组'});
  await groupRow.waitFor();
  await groupRow.getByText('编辑',{exact:true}).click();
  await page.getByRole('button',{name:'确定',exact:true}).click({trial:true});
  await page.getByPlaceholder('请输入用户组名称').fill('浏览器用户组已编辑');
  const groupEdited=page.waitForResponse(res=>/\/api\/v1\/user-groups\/\d+$/.test(new URL(res.url()).pathname) && res.request().method()==='PUT');
  await page.getByRole('button',{name:'确定',exact:true}).click();
  assert.equal((await groupEdited).status(),200);
  await groupRow.getByText('成员',{exact:true}).click();
  await page.locator('.semi-transfer-left .semi-checkbox').filter({hasText:'browser_user'}).click();
  const groupMembersSaved=page.waitForResponse(res=>/\/api\/v1\/user-groups\/\d+\/members$/.test(new URL(res.url()).pathname) && res.request().method()==='PUT');
  await page.getByRole('button',{name:'保存',exact:true}).click();
  assert.equal((await groupMembersSaved).status(),200);
  await groupRow.getByText('角色',{exact:true}).last().click();
  await page.getByText('请选择角色',{exact:true}).click();
  await page.getByText('浏览器角色已编辑（browser_role）',{exact:true}).click();
  await page.keyboard.press('Escape');
  const groupRolesSaved=page.waitForResponse(res=>/\/api\/v1\/user-groups\/\d+\/roles$/.test(new URL(res.url()).pathname) && res.request().method()==='PUT');
  await page.getByRole('button',{name:'confirm',exact:true}).click();
  assert.equal((await groupRolesSaved).status(),200);
  await page.getByRole('button',{name:'新增',exact:true}).click();
  await page.getByPlaceholder('请输入用户组名称').fill('浏览器动态组');
  await page.getByPlaceholder('字母数字下划线').fill('browser_dynamic');
  await page.getByText('动态（按规则自动维护）',{exact:true}).click();
  await page.getByText('选择用户（可选）',{exact:true}).first().click();
  await page.getByText('浏览器用户已编辑 (browser_user)',{exact:true}).click();
  await page.keyboard.press('Escape');
  const rulePreview=page.waitForResponse(res=>new URL(res.url()).pathname==='/api/v1/user-groups/rule-preview');
  await page.getByRole('button',{name:'预览成员变化',exact:true}).click();
  assert.equal((await rulePreview).status(),200);
  const dynamicCreated=page.waitForResponse(res=>new URL(res.url()).pathname==='/api/v1/user-groups' && res.request().method()==='POST');
  await page.getByRole('button',{name:'确定',exact:true}).click();
  assert.equal((await dynamicCreated).status(),200);
  const dynamicRow=page.getByRole('row').filter({hasText:'浏览器动态组'});
  await dynamicRow.getByText('成员',{exact:true}).click();
  await page.locator('.semi-sidesheet').getByText('浏览器用户已编辑（browser_user）',{exact:true}).waitFor();
  const synced=page.waitForResponse(res=>/\/api\/v1\/user-groups\/\d+\/sync$/.test(new URL(res.url()).pathname));
  await page.getByRole('button',{name:'立即同步',exact:true}).click();
  assert.equal((await synced).status(),200);
  await page.getByRole('button',{name:'关闭',exact:true}).click();
  await page.goto(`${base}/dash/system/menus`);
  await page.getByText('用户管理',{exact:true}).last().waitFor();
  await page.getByRole('button',{name:'新增',exact:true}).click();
  await page.locator('.semi-modal').getByText('按钮',{exact:true}).click();
  await page.getByPlaceholder('请输入菜单名称').fill('浏览器按钮');
  await page.getByPlaceholder('如：system:user:list').fill('system:user:list');
  const buttonCreated=page.waitForResponse(res=>new URL(res.url()).pathname==='/api/v1/menus' && res.request().method()==='POST');
  await page.getByRole('button',{name:'confirm',exact:true}).click();
  assert.equal((await buttonCreated).status(),201);
  const buttonRow=page.getByRole('row').filter({hasText:'浏览器按钮'});
  await buttonRow.waitFor();
  await buttonRow.getByText('编辑',{exact:true}).click();
  await page.getByRole('button',{name:'confirm',exact:true}).click({trial:true});
  await page.getByPlaceholder('请输入菜单名称').fill('浏览器按钮已编辑');
  const buttonEdited=page.waitForResponse(res=>/\/api\/v1\/menus\/\d+$/.test(new URL(res.url()).pathname) && res.request().method()==='PUT');
  await page.getByRole('button',{name:'confirm',exact:true}).click();
  assert.equal((await buttonEdited).status(),200);
  const buttonDeleted=page.waitForResponse(res=>/\/api\/v1\/menus\/\d+$/.test(new URL(res.url()).pathname) && res.request().method()==='DELETE');
  await page.getByRole('row').filter({hasText:'浏览器按钮已编辑'}).getByText('删除',{exact:true}).click();
  await page.getByRole('button',{name:/^(confirm|确\s*定)$/}).click();
  assert.equal((await buttonDeleted).status(),200);
  await page.goto(`${base}/dash/system/dicts`);
  await page.locator('.nav-list-panel__header').getByRole('button',{name:'更多操作',exact:true}).click();
  await page.getByText('新增字典',{exact:true}).click();
  await page.getByPlaceholder('请输入字典名称').fill('浏览器字典');
  await page.getByPlaceholder('请输入字典编码').fill('browser_dict');
  await page.getByRole('button',{name:'confirm',exact:true}).click();
  await page.getByText('浏览器字典',{exact:true}).first().click();
  await page.getByRole('button',{name:'新增',exact:true}).last().click();
  await page.getByPlaceholder('请输入标签').fill('浏览器字典项');
  await page.getByPlaceholder('请输入键值').fill('browser_item');
  await page.getByPlaceholder('请输入备注').fill('真实备注');
  await page.getByRole('button',{name:'confirm',exact:true}).click();
  await page.getByRole('row').filter({hasText:'浏览器字典项'}).waitFor();
  await page.reload();
  await page.getByRole('row').filter({hasText:'浏览器字典项'}).waitFor();
  await page.goto(`${base}/dash/system/identity-security`);
  await page.getByText('最小长度',{exact:true}).waitFor();
  assert.equal(await page.getByText('启用 MFA',{exact:true}).count(),0);
  const securitySaved=page.waitForResponse(res=>new URL(res.url()).pathname==='/api/v1/settings/identity-security' && res.request().method()==='PUT');
  await page.getByRole('button',{name:'保存',exact:true}).click();
  assert.equal((await securitySaved).status(),200);
  await page.goto(`${base}/dash/system/settings`);
  await page.getByText('设置模块',{exact:true}).waitFor();
  await page.locator('.semi-select').click();
  await page.getByText('高（干扰强、识别难度高）',{exact:true}).click();
  const authSettingsSaved=page.waitForResponse(res=>new URL(res.url()).pathname==='/api/v1/settings/auth' && res.request().method()==='PUT');
  await page.getByRole('button',{name:'保存',exact:true}).click();
  assert.equal((await authSettingsSaved).status(),200);
  await page.reload();
  await page.locator('.semi-select').getByText('高（干扰强、识别难度高）',{exact:true}).waitFor();
  await page.goto(`${base}/dash/system/sessions`);
  await page.getByRole('row').filter({hasText:process.env.ARCBASE_BROWSER_USERNAME}).waitFor();
  await page.goto(`${base}/dash/system/login-logs`);
  await page.getByRole('row').filter({hasText:process.env.ARCBASE_BROWSER_USERNAME}).waitFor();
  const loginStats=page.waitForResponse(res=>new URL(res.url()).pathname==='/api/v1/login-logs/stats');
  await page.getByRole('tab',{name:'统计分析',exact:true}).click();
  assert.equal((await loginStats).status(),200);
  await page.goto(`${base}/dash/system/operation-logs`);
  await page.getByRole('row').filter({hasText:'创建字典项'}).waitFor();
  const operationStats=page.waitForResponse(res=>new URL(res.url()).pathname==='/api/v1/operation-logs/stats');
  await page.getByRole('tab',{name:'统计分析',exact:true}).click();
  assert.equal((await operationStats).status(),200);
  await page.goto(`${base}/dash/system/file-configs`);
  await page.getByRole('button',{name:'新增',exact:true}).click();
  await page.getByPlaceholder('请输入配置名称').fill('浏览器本地文件');
  await page.getByPlaceholder('例如 storage/local 或 D:/uploads').fill(process.env.ARCBASE_BROWSER_STORAGE);
  await page.getByRole('switch').click();
  const testStorage=page.waitForResponse(res=>new URL(res.url()).pathname==='/api/v1/file-storage-configs/test');
  await page.getByRole('button',{name:'测试连接',exact:true}).click();
  assert.equal((await testStorage).status(),200);
  const configSaved=page.waitForResponse(res=>new URL(res.url()).pathname==='/api/v1/file-storage-configs' && res.request().method()==='POST');
  await page.getByRole('button',{name:'保存',exact:true}).click();
  assert.equal((await configSaved).status(),200);
  await page.getByRole('row').filter({hasText:'浏览器本地文件'}).waitFor();
  await page.goto(`${base}/dash/system/files`);
  await page.getByRole('button',{name:'上传文件',exact:true}).waitFor();
  const normalUpload=page.waitForResponse(res=>new URL(res.url()).pathname==='/api/v1/files/upload' && res.request().method()==='POST');
  await page.locator('input[type=file]').setInputFiles({name:'browser.txt',mimeType:'text/plain',buffer:Buffer.from('真实文件内容')});
  assert.equal((await normalUpload).status(),200);
  await page.getByText('browser.txt',{exact:true}).first().waitFor();
  await page.getByRole('button',{name:'关闭',exact:true}).last().click();
  const chunkUpload=page.waitForResponse(res=>new URL(res.url()).pathname==='/api/v1/files/upload/complete');
  await page.locator('input[type=file]').setInputFiles({name:'browser-chunk.txt',mimeType:'text/plain',buffer:Buffer.alloc(6*1024*1024,65)});
  assert.equal((await chunkUpload).status(),200);
  await page.getByRole('button',{name:'关闭',exact:true}).last().click();
  await page.reload();
  await page.getByText('browser-chunk.txt',{exact:true}).first().waitFor();
  const normalFileRow=page.getByRole('row').filter({hasText:'browser.txt'});
  await normalFileRow.getByText('预览',{exact:true}).click();
  await page.getByText('真实文件内容',{exact:true}).waitFor();
  await page.keyboard.press('Escape');
  const fileDownloaded=page.waitForEvent('download');
  await normalFileRow.getByText('下载',{exact:true}).click();
  assert.equal(await readFile(await (await fileDownloaded).path(),'utf8'),'真实文件内容');
  await normalFileRow.locator('.semi-checkbox').click();
  const filesZipped=page.waitForEvent('download');
  await page.getByRole('button',{name:/批量下载/}).click();
  assert.equal((await readFile(await (await filesZipped).path())).subarray(0,2).toString(),'PK');
  const filesDeleted=page.waitForResponse(res=>new URL(res.url()).pathname.startsWith('/api/v1/files/') && res.request().method()==='DELETE');
  await page.getByRole('button',{name:/批量删除/}).click();
  await page.getByRole('button',{name:/^(confirm|确\s*定)$/}).click();
  assert.equal((await filesDeleted).status(),200);
  await normalFileRow.waitFor({state:'hidden'});
  await page.goto(`${base}/dash/profile`);
  await page.getByPlaceholder('请输入昵称').fill('浏览器管理员');
  const profileSaved=page.waitForResponse(res=>new URL(res.url()).pathname==='/api/v1/auth/profile' && res.request().method()==='PUT');
  await page.getByRole('button',{name:'保存修改',exact:true}).click();
  assert.equal((await profileSaved).status(),200);
  await page.reload();
  assert.equal(await page.getByPlaceholder('请输入昵称').inputValue(),'浏览器管理员');
  await page.getByRole('button',{name:'更换头像',exact:true}).last().click();
  await page.locator('input[type=file]').setInputFiles(process.env.ARCBASE_BROWSER_AVATAR_FILE);
  const avatarUploaded=page.waitForResponse(res=>new URL(res.url()).pathname==='/api/v1/auth/avatar' && res.request().method()==='POST');
  const avatarSaved=page.waitForResponse(res=>new URL(res.url()).pathname==='/api/v1/auth/profile' && res.request().method()==='PUT');
  await page.getByRole('button',{name:'确认并上传',exact:true}).click();
  assert.equal((await avatarUploaded).status(),200);
  assert.equal((await avatarSaved).status(),200);
  await page.reload();
  await page.getByPlaceholder('请输入昵称').waitFor();
  await page.locator('img[src*="/api/v1/files/"]').first().waitFor();
  const personalSessions=page.waitForResponse(res=>new URL(res.url()).pathname==='/api/v1/auth/my-sessions');
  await page.getByRole('tab',{name:'我的设备',exact:true}).click();
  assert.equal((await personalSessions).status(),200);
  const personalLogins=page.waitForResponse(res=>new URL(res.url()).pathname==='/api/v1/auth/my-login-logs');
  await page.getByRole('tab',{name:'登录记录',exact:true}).click();
  assert.equal((await personalLogins).status(),200);
  const personalOperations=page.waitForResponse(res=>new URL(res.url()).pathname==='/api/v1/auth/my-operation-logs');
  await page.getByRole('tab',{name:'操作记录',exact:true}).click();
  assert.equal((await personalOperations).status(),200);
  await page.setViewportSize({width:390,height:844});
  await page.reload();
  await page.getByRole('tab',{name:'操作记录',exact:true}).waitFor();
  assert.ok((await page.locator('body').boundingBox()).width<=390,'original narrow-screen layout');
  await screenshot(page, 'profile-narrow');
  await page.setViewportSize({width:1280,height:720});
  await page.goto(`${base}/dash/system/positions`);
  await page.getByRole('button',{name:'新增',exact:true}).waitFor();

  const csrfStatus = await page.evaluate(async () => (await fetch('/api/v1/positions', { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: 'forbidden', code: 'forbidden' }) })).status);
  assert.equal(csrfStatus, 403, 'CSRF is enforced by Go');
  // The intentional rejection is an acceptance assertion, not a page failure.
  const csrfFailure = failures.indexOf('403 /api/v1/positions');
  assert.ok(csrfFailure >= 0);
  failures.splice(csrfFailure, 1);
  await page.getByTitle('切换主题').click();
  const preferencesSaved = page.waitForResponse((res) => new URL(res.url()).pathname === '/api/v1/auth/preferences' && res.request().method() === 'PUT');
  await page.getByText('深色', { exact: true }).click();
  assert.equal((await preferencesSaved).status(), 200);
  await page.reload();
  await page.getByRole('button', { name: '新增', exact: true }).waitFor();
  assert.equal(await page.locator('body').getAttribute('theme-mode'), 'dark', 'theme restored from PostgreSQL');
  const restrictedFixture = await page.evaluate(async (password) => {
    const me = await (await fetch('/api/v1/auth/me')).json();
    const call = async (method, path, data) => {
      const response = await fetch(`/api/v1${path}`, { method, headers: { 'Content-Type': 'application/json', 'X-CSRF-Token': me.data.csrfToken }, body: data === undefined ? undefined : JSON.stringify(data) });
      if (!response.ok) throw new Error(`Restricted fixture ${method} ${path}: ${response.status}`);
      return (await response.json()).data;
    };
    const menus = await call('GET', '/menus/flat');
    const role = await call('POST', '/roles', { name: '受限浏览器角色', code: 'foundation_limited', dataScope: 'self' });
    await call('PUT', `/roles/${role.id}/menus`, { menuIds: menus.filter((menu) => ['system:user:list', 'system:user:update'].includes(menu.permission)).map((menu) => menu.id) });
    const user = await call('POST', '/users', { username: 'foundation-limited', nickname: '受限浏览器用户', password, roleIds: [role.id] });
    const hidden = await call('POST', '/users', { username: 'foundation-hidden', nickname: '范围外浏览器用户', password });
    return { roleId: role.id, userId: user.id, hiddenId: hidden.id };
  }, process.env.ARCBASE_BROWSER_PASSWORD);
  const limitedContext = await browser.newContext({ ignoreHTTPSErrors: process.env.ARCBASE_BROWSER_HTTPS === 'true' });
  const limitedPage = await limitedContext.newPage();
  limitedPage.on('response', (response) => { const path = new URL(response.url()).pathname; if (path.startsWith('/api/')) responses.push(`LIMITED ${response.request().method()} ${response.status()} ${path}`); });
  await limitedPage.goto(`${base}/dash/login`);
  const limitedImage = limitedPage.getByAltText('登录验证码');
  await limitedImage.waitFor();
  const limitedSVG = Buffer.from((await limitedImage.getAttribute('src')).split(',')[1], 'base64').toString();
  const limitedAnswer = limitedSVG.match(/>([A-F0-9]{4,8})<\/text>/)?.[1];
  assert.ok(limitedAnswer, 'saved high-complexity captcha is used on the next real login');
  await limitedPage.getByPlaceholder('请输入用户名/手机号').fill('foundation-limited');
  await limitedPage.getByPlaceholder('请输入密码', { exact: true }).fill(process.env.ARCBASE_BROWSER_PASSWORD);
  await limitedPage.getByPlaceholder('请输入验证码').fill(limitedAnswer);
  await limitedPage.getByRole('button', { name: '登录', exact: true }).click();
  await limitedPage.waitForURL(/\/dash\/?$/);
  await limitedPage.goto(`${base}/dash/system/users`);
  const scopedData = await limitedPage.evaluate(async () => (await (await fetch('/api/v1/users')).json()).data);
  assert.equal(scopedData.total, 1, 'self data scope excludes other accounts');
  const limitedRow = limitedPage.getByRole('row').filter({ hasText: 'foundation-limited' });
  await limitedRow.waitFor();
  assert.equal(await limitedPage.getByRole('button', { name: '新增', exact: true }).count(), 0, 'create button requires create permission');
  assert.equal(await limitedPage.getByText('角色管理', { exact: true }).count(), 0, 'unauthorized menu is absent');
  assert.equal(responses.some((response) => /^LIMITED GET 403 \/api\/v1\/(positions\/all|departments\/flat|roles\/all|menus)$/.test(response)), false, 'page does not query unauthorized catalogs');
  await limitedRow.getByText('编辑', { exact: true }).click();
  await limitedPage.getByRole('button', { name: /^(confirm|确\s*定)$/ }).click({ trial: true });
  await limitedPage.getByPlaceholder('请输入昵称').fill('受限用户已编辑');
  const limitedSaved = limitedPage.waitForResponse((response) => new URL(response.url()).pathname === `/api/v1/users/${restrictedFixture.userId}` && response.request().method() === 'PUT');
  await limitedPage.getByRole('button', { name: /^(confirm|确\s*定)$/ }).click();
  assert.equal((await limitedSaved).status(), 200, 'ordinary user can edit within granted scope');
  await limitedPage.getByRole('row').filter({ hasText: '受限用户已编辑' }).waitFor();
  await limitedPage.locator('.semi-modal').waitFor({ state: 'hidden' });
  await screenshot(limitedPage, 'restricted-users');
  const denials = await limitedPage.evaluate(async ({ userId, hiddenId, roleId }) => {
    const me = await (await fetch('/api/v1/auth/me')).json();
    const call = async (method, path, data) => (await fetch(`/api/v1${path}`, { method, headers: { 'Content-Type': 'application/json', 'X-CSRF-Token': me.data.csrfToken }, body: data === undefined ? undefined : JSON.stringify(data) })).status;
    return [await call('GET', `/users/${hiddenId}`), await call('PUT', `/users/${hiddenId}`, { nickname: 'denied' }), await call('PUT', `/roles/${roleId}/menus`, { menuIds: [] }), await call('PUT', `/users/${userId}/data-permission`, { dataScope: 'all', deptScopeIds: [] }), await call('GET', '/files')];
  }, restrictedFixture);
  assert.deepEqual(denials, [404, 404, 403, 403, 403], 'server enforces scope and prevents privilege escalation');
  await page.evaluate(async (roleId) => {
    const me = await (await fetch('/api/v1/auth/me')).json();
    const response = await fetch(`/api/v1/roles/${roleId}`, { method: 'PUT', headers: { 'Content-Type': 'application/json', 'X-CSRF-Token': me.data.csrfToken }, body: JSON.stringify({ status: 'disabled' }) });
    if (!response.ok) throw new Error(`Role disable: ${response.status}`);
  }, restrictedFixture.roleId);
  assert.equal(await limitedPage.evaluate(async () => (await fetch('/api/v1/users')).status), 403, 'disabled role is effective without logout');
  await page.evaluate(async (userId) => {
    const me = await (await fetch('/api/v1/auth/me')).json();
    const response = await fetch(`/api/v1/sessions/user/${userId}`, { method: 'DELETE', headers: { 'X-CSRF-Token': me.data.csrfToken } });
    if (!response.ok) throw new Error(`Force offline: ${response.status}`);
  }, restrictedFixture.userId);
  assert.equal(await limitedPage.evaluate(async () => (await fetch('/api/v1/auth/me')).status), 401, 'force offline immediately invalidates ordinary session');
  await limitedPage.reload();
  await limitedPage.waitForURL(/\/dash\/login/);
  await limitedContext.close();
  await page.locator('.admin-header__user').click();
  await page.getByText('退出登录', { exact: true }).click();
  await page.getByRole('button', { name: /^(confirm|确\s*定)$/ }).click();
  await page.waitForURL(/\/dash\/login/);
  await page.reload();
  await image.waitFor();
  assert.ok(apiRequests.every((path) => path.startsWith('/api/v1/')), `legacy API requests: ${apiRequests.filter((path) => !path.startsWith('/api/v1/')).join(', ')}`);
  assert.deepEqual(failures, []);
  assert.deepEqual(externalRequests, [], 'standalone dashboard and original file preview use embedded resources');
  console.log('PASS: original login/shell, departments, positions, users, roles, groups/dynamic rules, menus, dictionaries, settings/security saves, sessions/logs, uploads/chunks/downloads/deletion, profile/avatar/personal logs/devices, narrow screen, sync XLSX import/preflight and CSV/XLSX exports, CSRF, persisted theme, logout; restricted real login, scoped edit, hidden buttons/menus, denied escalation, disabled role and forced offline; all API requests use /api/v1');
} catch (err) {
  console.error(err.stack); console.error(viteOutput.slice(-5000)); console.error(consoleMessages.join("\n"));
  console.error(responses.join('\n'));
  console.error(failures.join('\n'));
  if (browser) {
    const page = browser.contexts().at(-1)?.pages().at(-1);
    if (page) console.error((await page.locator('body').innerText()).slice(-2200));
    if (page) console.error(await page.getByRole('button').evaluateAll((buttons) => buttons.map((button) => ({ text: button.textContent, label: button.getAttribute('aria-label') }))));
  }
  process.exitCode = 1;
} finally {
  await browser?.close();
  vite?.kill();
}
