// Code generated by ent, DO NOT EDIT.

package managedfile

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/fudanda/zenith-admin/backend/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldLTE(FieldID, id))
}

// StorageConfigID applies equality check predicate on the "storage_config_id" field. It's identical to StorageConfigIDEQ.
func StorageConfigID(v int) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldEQ(FieldStorageConfigID, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldEQ(FieldTenantID, v))
}

// UploaderID applies equality check predicate on the "uploader_id" field. It's identical to UploaderIDEQ.
func UploaderID(v int) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldEQ(FieldUploaderID, v))
}

// OriginalName applies equality check predicate on the "original_name" field. It's identical to OriginalNameEQ.
func OriginalName(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldEQ(FieldOriginalName, v))
}

// ObjectKey applies equality check predicate on the "object_key" field. It's identical to ObjectKeyEQ.
func ObjectKey(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldEQ(FieldObjectKey, v))
}

// Size applies equality check predicate on the "size" field. It's identical to SizeEQ.
func Size(v int64) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldEQ(FieldSize, v))
}

// MimeType applies equality check predicate on the "mime_type" field. It's identical to MimeTypeEQ.
func MimeType(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldEQ(FieldMimeType, v))
}

// Extension applies equality check predicate on the "extension" field. It's identical to ExtensionEQ.
func Extension(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldEQ(FieldExtension, v))
}

// Visibility applies equality check predicate on the "visibility" field. It's identical to VisibilityEQ.
func Visibility(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldEQ(FieldVisibility, v))
}

// ContentHash applies equality check predicate on the "content_hash" field. It's identical to ContentHashEQ.
func ContentHash(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldEQ(FieldContentHash, v))
}

// DeletePending applies equality check predicate on the "delete_pending" field. It's identical to DeletePendingEQ.
func DeletePending(v bool) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldEQ(FieldDeletePending, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldEQ(FieldUpdatedAt, v))
}

// StorageConfigIDEQ applies the EQ predicate on the "storage_config_id" field.
func StorageConfigIDEQ(v int) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldEQ(FieldStorageConfigID, v))
}

// StorageConfigIDNEQ applies the NEQ predicate on the "storage_config_id" field.
func StorageConfigIDNEQ(v int) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldNEQ(FieldStorageConfigID, v))
}

// StorageConfigIDIn applies the In predicate on the "storage_config_id" field.
func StorageConfigIDIn(vs ...int) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldIn(FieldStorageConfigID, vs...))
}

// StorageConfigIDNotIn applies the NotIn predicate on the "storage_config_id" field.
func StorageConfigIDNotIn(vs ...int) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldNotIn(FieldStorageConfigID, vs...))
}

// StorageConfigIDGT applies the GT predicate on the "storage_config_id" field.
func StorageConfigIDGT(v int) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldGT(FieldStorageConfigID, v))
}

// StorageConfigIDGTE applies the GTE predicate on the "storage_config_id" field.
func StorageConfigIDGTE(v int) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldGTE(FieldStorageConfigID, v))
}

// StorageConfigIDLT applies the LT predicate on the "storage_config_id" field.
func StorageConfigIDLT(v int) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldLT(FieldStorageConfigID, v))
}

// StorageConfigIDLTE applies the LTE predicate on the "storage_config_id" field.
func StorageConfigIDLTE(v int) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldLTE(FieldStorageConfigID, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v int) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v int) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v int) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v int) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldNotNull(FieldTenantID))
}

// UploaderIDEQ applies the EQ predicate on the "uploader_id" field.
func UploaderIDEQ(v int) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldEQ(FieldUploaderID, v))
}

// UploaderIDNEQ applies the NEQ predicate on the "uploader_id" field.
func UploaderIDNEQ(v int) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldNEQ(FieldUploaderID, v))
}

// UploaderIDIn applies the In predicate on the "uploader_id" field.
func UploaderIDIn(vs ...int) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldIn(FieldUploaderID, vs...))
}

// UploaderIDNotIn applies the NotIn predicate on the "uploader_id" field.
func UploaderIDNotIn(vs ...int) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldNotIn(FieldUploaderID, vs...))
}

// UploaderIDGT applies the GT predicate on the "uploader_id" field.
func UploaderIDGT(v int) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldGT(FieldUploaderID, v))
}

// UploaderIDGTE applies the GTE predicate on the "uploader_id" field.
func UploaderIDGTE(v int) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldGTE(FieldUploaderID, v))
}

// UploaderIDLT applies the LT predicate on the "uploader_id" field.
func UploaderIDLT(v int) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldLT(FieldUploaderID, v))
}

// UploaderIDLTE applies the LTE predicate on the "uploader_id" field.
func UploaderIDLTE(v int) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldLTE(FieldUploaderID, v))
}

// OriginalNameEQ applies the EQ predicate on the "original_name" field.
func OriginalNameEQ(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldEQ(FieldOriginalName, v))
}

// OriginalNameNEQ applies the NEQ predicate on the "original_name" field.
func OriginalNameNEQ(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldNEQ(FieldOriginalName, v))
}

// OriginalNameIn applies the In predicate on the "original_name" field.
func OriginalNameIn(vs ...string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldIn(FieldOriginalName, vs...))
}

// OriginalNameNotIn applies the NotIn predicate on the "original_name" field.
func OriginalNameNotIn(vs ...string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldNotIn(FieldOriginalName, vs...))
}

// OriginalNameGT applies the GT predicate on the "original_name" field.
func OriginalNameGT(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldGT(FieldOriginalName, v))
}

// OriginalNameGTE applies the GTE predicate on the "original_name" field.
func OriginalNameGTE(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldGTE(FieldOriginalName, v))
}

// OriginalNameLT applies the LT predicate on the "original_name" field.
func OriginalNameLT(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldLT(FieldOriginalName, v))
}

// OriginalNameLTE applies the LTE predicate on the "original_name" field.
func OriginalNameLTE(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldLTE(FieldOriginalName, v))
}

// OriginalNameContains applies the Contains predicate on the "original_name" field.
func OriginalNameContains(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldContains(FieldOriginalName, v))
}

// OriginalNameHasPrefix applies the HasPrefix predicate on the "original_name" field.
func OriginalNameHasPrefix(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldHasPrefix(FieldOriginalName, v))
}

// OriginalNameHasSuffix applies the HasSuffix predicate on the "original_name" field.
func OriginalNameHasSuffix(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldHasSuffix(FieldOriginalName, v))
}

// OriginalNameEqualFold applies the EqualFold predicate on the "original_name" field.
func OriginalNameEqualFold(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldEqualFold(FieldOriginalName, v))
}

// OriginalNameContainsFold applies the ContainsFold predicate on the "original_name" field.
func OriginalNameContainsFold(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldContainsFold(FieldOriginalName, v))
}

// ObjectKeyEQ applies the EQ predicate on the "object_key" field.
func ObjectKeyEQ(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldEQ(FieldObjectKey, v))
}

// ObjectKeyNEQ applies the NEQ predicate on the "object_key" field.
func ObjectKeyNEQ(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldNEQ(FieldObjectKey, v))
}

// ObjectKeyIn applies the In predicate on the "object_key" field.
func ObjectKeyIn(vs ...string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldIn(FieldObjectKey, vs...))
}

// ObjectKeyNotIn applies the NotIn predicate on the "object_key" field.
func ObjectKeyNotIn(vs ...string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldNotIn(FieldObjectKey, vs...))
}

// ObjectKeyGT applies the GT predicate on the "object_key" field.
func ObjectKeyGT(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldGT(FieldObjectKey, v))
}

// ObjectKeyGTE applies the GTE predicate on the "object_key" field.
func ObjectKeyGTE(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldGTE(FieldObjectKey, v))
}

// ObjectKeyLT applies the LT predicate on the "object_key" field.
func ObjectKeyLT(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldLT(FieldObjectKey, v))
}

// ObjectKeyLTE applies the LTE predicate on the "object_key" field.
func ObjectKeyLTE(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldLTE(FieldObjectKey, v))
}

// ObjectKeyContains applies the Contains predicate on the "object_key" field.
func ObjectKeyContains(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldContains(FieldObjectKey, v))
}

// ObjectKeyHasPrefix applies the HasPrefix predicate on the "object_key" field.
func ObjectKeyHasPrefix(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldHasPrefix(FieldObjectKey, v))
}

// ObjectKeyHasSuffix applies the HasSuffix predicate on the "object_key" field.
func ObjectKeyHasSuffix(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldHasSuffix(FieldObjectKey, v))
}

// ObjectKeyEqualFold applies the EqualFold predicate on the "object_key" field.
func ObjectKeyEqualFold(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldEqualFold(FieldObjectKey, v))
}

// ObjectKeyContainsFold applies the ContainsFold predicate on the "object_key" field.
func ObjectKeyContainsFold(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldContainsFold(FieldObjectKey, v))
}

// SizeEQ applies the EQ predicate on the "size" field.
func SizeEQ(v int64) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldEQ(FieldSize, v))
}

// SizeNEQ applies the NEQ predicate on the "size" field.
func SizeNEQ(v int64) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldNEQ(FieldSize, v))
}

// SizeIn applies the In predicate on the "size" field.
func SizeIn(vs ...int64) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldIn(FieldSize, vs...))
}

// SizeNotIn applies the NotIn predicate on the "size" field.
func SizeNotIn(vs ...int64) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldNotIn(FieldSize, vs...))
}

// SizeGT applies the GT predicate on the "size" field.
func SizeGT(v int64) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldGT(FieldSize, v))
}

// SizeGTE applies the GTE predicate on the "size" field.
func SizeGTE(v int64) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldGTE(FieldSize, v))
}

// SizeLT applies the LT predicate on the "size" field.
func SizeLT(v int64) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldLT(FieldSize, v))
}

// SizeLTE applies the LTE predicate on the "size" field.
func SizeLTE(v int64) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldLTE(FieldSize, v))
}

// MimeTypeEQ applies the EQ predicate on the "mime_type" field.
func MimeTypeEQ(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldEQ(FieldMimeType, v))
}

// MimeTypeNEQ applies the NEQ predicate on the "mime_type" field.
func MimeTypeNEQ(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldNEQ(FieldMimeType, v))
}

// MimeTypeIn applies the In predicate on the "mime_type" field.
func MimeTypeIn(vs ...string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldIn(FieldMimeType, vs...))
}

// MimeTypeNotIn applies the NotIn predicate on the "mime_type" field.
func MimeTypeNotIn(vs ...string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldNotIn(FieldMimeType, vs...))
}

// MimeTypeGT applies the GT predicate on the "mime_type" field.
func MimeTypeGT(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldGT(FieldMimeType, v))
}

// MimeTypeGTE applies the GTE predicate on the "mime_type" field.
func MimeTypeGTE(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldGTE(FieldMimeType, v))
}

// MimeTypeLT applies the LT predicate on the "mime_type" field.
func MimeTypeLT(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldLT(FieldMimeType, v))
}

// MimeTypeLTE applies the LTE predicate on the "mime_type" field.
func MimeTypeLTE(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldLTE(FieldMimeType, v))
}

// MimeTypeContains applies the Contains predicate on the "mime_type" field.
func MimeTypeContains(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldContains(FieldMimeType, v))
}

// MimeTypeHasPrefix applies the HasPrefix predicate on the "mime_type" field.
func MimeTypeHasPrefix(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldHasPrefix(FieldMimeType, v))
}

// MimeTypeHasSuffix applies the HasSuffix predicate on the "mime_type" field.
func MimeTypeHasSuffix(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldHasSuffix(FieldMimeType, v))
}

// MimeTypeIsNil applies the IsNil predicate on the "mime_type" field.
func MimeTypeIsNil() predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldIsNull(FieldMimeType))
}

// MimeTypeNotNil applies the NotNil predicate on the "mime_type" field.
func MimeTypeNotNil() predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldNotNull(FieldMimeType))
}

// MimeTypeEqualFold applies the EqualFold predicate on the "mime_type" field.
func MimeTypeEqualFold(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldEqualFold(FieldMimeType, v))
}

// MimeTypeContainsFold applies the ContainsFold predicate on the "mime_type" field.
func MimeTypeContainsFold(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldContainsFold(FieldMimeType, v))
}

// ExtensionEQ applies the EQ predicate on the "extension" field.
func ExtensionEQ(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldEQ(FieldExtension, v))
}

// ExtensionNEQ applies the NEQ predicate on the "extension" field.
func ExtensionNEQ(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldNEQ(FieldExtension, v))
}

// ExtensionIn applies the In predicate on the "extension" field.
func ExtensionIn(vs ...string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldIn(FieldExtension, vs...))
}

// ExtensionNotIn applies the NotIn predicate on the "extension" field.
func ExtensionNotIn(vs ...string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldNotIn(FieldExtension, vs...))
}

// ExtensionGT applies the GT predicate on the "extension" field.
func ExtensionGT(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldGT(FieldExtension, v))
}

// ExtensionGTE applies the GTE predicate on the "extension" field.
func ExtensionGTE(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldGTE(FieldExtension, v))
}

// ExtensionLT applies the LT predicate on the "extension" field.
func ExtensionLT(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldLT(FieldExtension, v))
}

// ExtensionLTE applies the LTE predicate on the "extension" field.
func ExtensionLTE(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldLTE(FieldExtension, v))
}

// ExtensionContains applies the Contains predicate on the "extension" field.
func ExtensionContains(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldContains(FieldExtension, v))
}

// ExtensionHasPrefix applies the HasPrefix predicate on the "extension" field.
func ExtensionHasPrefix(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldHasPrefix(FieldExtension, v))
}

// ExtensionHasSuffix applies the HasSuffix predicate on the "extension" field.
func ExtensionHasSuffix(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldHasSuffix(FieldExtension, v))
}

// ExtensionIsNil applies the IsNil predicate on the "extension" field.
func ExtensionIsNil() predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldIsNull(FieldExtension))
}

// ExtensionNotNil applies the NotNil predicate on the "extension" field.
func ExtensionNotNil() predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldNotNull(FieldExtension))
}

// ExtensionEqualFold applies the EqualFold predicate on the "extension" field.
func ExtensionEqualFold(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldEqualFold(FieldExtension, v))
}

// ExtensionContainsFold applies the ContainsFold predicate on the "extension" field.
func ExtensionContainsFold(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldContainsFold(FieldExtension, v))
}

// VisibilityEQ applies the EQ predicate on the "visibility" field.
func VisibilityEQ(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldEQ(FieldVisibility, v))
}

// VisibilityNEQ applies the NEQ predicate on the "visibility" field.
func VisibilityNEQ(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldNEQ(FieldVisibility, v))
}

// VisibilityIn applies the In predicate on the "visibility" field.
func VisibilityIn(vs ...string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldIn(FieldVisibility, vs...))
}

// VisibilityNotIn applies the NotIn predicate on the "visibility" field.
func VisibilityNotIn(vs ...string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldNotIn(FieldVisibility, vs...))
}

// VisibilityGT applies the GT predicate on the "visibility" field.
func VisibilityGT(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldGT(FieldVisibility, v))
}

// VisibilityGTE applies the GTE predicate on the "visibility" field.
func VisibilityGTE(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldGTE(FieldVisibility, v))
}

// VisibilityLT applies the LT predicate on the "visibility" field.
func VisibilityLT(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldLT(FieldVisibility, v))
}

// VisibilityLTE applies the LTE predicate on the "visibility" field.
func VisibilityLTE(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldLTE(FieldVisibility, v))
}

// VisibilityContains applies the Contains predicate on the "visibility" field.
func VisibilityContains(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldContains(FieldVisibility, v))
}

// VisibilityHasPrefix applies the HasPrefix predicate on the "visibility" field.
func VisibilityHasPrefix(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldHasPrefix(FieldVisibility, v))
}

// VisibilityHasSuffix applies the HasSuffix predicate on the "visibility" field.
func VisibilityHasSuffix(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldHasSuffix(FieldVisibility, v))
}

// VisibilityEqualFold applies the EqualFold predicate on the "visibility" field.
func VisibilityEqualFold(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldEqualFold(FieldVisibility, v))
}

// VisibilityContainsFold applies the ContainsFold predicate on the "visibility" field.
func VisibilityContainsFold(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldContainsFold(FieldVisibility, v))
}

// ContentHashEQ applies the EQ predicate on the "content_hash" field.
func ContentHashEQ(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldEQ(FieldContentHash, v))
}

// ContentHashNEQ applies the NEQ predicate on the "content_hash" field.
func ContentHashNEQ(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldNEQ(FieldContentHash, v))
}

// ContentHashIn applies the In predicate on the "content_hash" field.
func ContentHashIn(vs ...string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldIn(FieldContentHash, vs...))
}

// ContentHashNotIn applies the NotIn predicate on the "content_hash" field.
func ContentHashNotIn(vs ...string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldNotIn(FieldContentHash, vs...))
}

// ContentHashGT applies the GT predicate on the "content_hash" field.
func ContentHashGT(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldGT(FieldContentHash, v))
}

// ContentHashGTE applies the GTE predicate on the "content_hash" field.
func ContentHashGTE(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldGTE(FieldContentHash, v))
}

// ContentHashLT applies the LT predicate on the "content_hash" field.
func ContentHashLT(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldLT(FieldContentHash, v))
}

// ContentHashLTE applies the LTE predicate on the "content_hash" field.
func ContentHashLTE(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldLTE(FieldContentHash, v))
}

// ContentHashContains applies the Contains predicate on the "content_hash" field.
func ContentHashContains(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldContains(FieldContentHash, v))
}

// ContentHashHasPrefix applies the HasPrefix predicate on the "content_hash" field.
func ContentHashHasPrefix(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldHasPrefix(FieldContentHash, v))
}

// ContentHashHasSuffix applies the HasSuffix predicate on the "content_hash" field.
func ContentHashHasSuffix(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldHasSuffix(FieldContentHash, v))
}

// ContentHashIsNil applies the IsNil predicate on the "content_hash" field.
func ContentHashIsNil() predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldIsNull(FieldContentHash))
}

// ContentHashNotNil applies the NotNil predicate on the "content_hash" field.
func ContentHashNotNil() predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldNotNull(FieldContentHash))
}

// ContentHashEqualFold applies the EqualFold predicate on the "content_hash" field.
func ContentHashEqualFold(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldEqualFold(FieldContentHash, v))
}

// ContentHashContainsFold applies the ContainsFold predicate on the "content_hash" field.
func ContentHashContainsFold(v string) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldContainsFold(FieldContentHash, v))
}

// DeletePendingEQ applies the EQ predicate on the "delete_pending" field.
func DeletePendingEQ(v bool) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldEQ(FieldDeletePending, v))
}

// DeletePendingNEQ applies the NEQ predicate on the "delete_pending" field.
func DeletePendingNEQ(v bool) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldNEQ(FieldDeletePending, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ManagedFile {
	return predicate.ManagedFile(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ManagedFile) predicate.ManagedFile {
	return predicate.ManagedFile(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ManagedFile) predicate.ManagedFile {
	return predicate.ManagedFile(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ManagedFile) predicate.ManagedFile {
	return predicate.ManagedFile(sql.NotPredicates(p))
}
